### ISSUE TITLE
Document Racket based TravisCI projects

### ISSUE THREAD

**Issue by LeifAndersen** [travis-ci/docs-travis-ci-com#1007]
There are many Racket programs that use TravisCI, including [Racket itself][1]. Frequently, they use [this script][2] to simulate native integration, and even [new Racket packages][3] come with this build script.

It seems like having Racket project instructions where all of the other languages are would be helpful to have. I'd be happy to write it up if needed.

Thoughts?

[1]: https://travis-ci.org/racket/racket
[2]: https://github.com/greghendershott/travis-racket
[3]: http://docs.racket-lang.org/pkg/cmdline.html?q=raco%20pkg%20new#%28part._raco-pkg-new%29

**Comment by plaindocs** [comment]
Hi @LeifAndersen - thanks for bringing this up.

We have some [guidelines](https://docs.travis-ci.com/user/languages/community-supported-languages/) for adding a new language to Travis CI. Do you think you'd be able to find a couple more people to support it?

**Comment by LeifAndersen** [comment]
Yes, we absolutely can. We will write up docs and submit a PR, thank you for sending me that link. Should we just post here who can support it?

Thanks again.

**Comment by plaindocs** [comment]
That sounds great! 

We mention community maintainers in the documentation, so people can mention them in GitHub issues. See the [Dart Community Docs](https://docs.travis-ci.com/user/languages/dart) for an example.

I think everything else you need to know is in those guidelines, but do let me know if any of it isn't clear.

**Comment by LeifAndersen** [comment]
FWIW I am still going to write docs for Racket (unless someone else has beat me to it), and I have a few other people that are willing to help maintain them (once I've written them). I've just a bit busy as of late, but plan to get it done in June. (As I will have then finished the two papers I've been working on.)

Anyway, thanks again for your feedback.
