### ISSUE TITLE
How Can I unsubscribe from an email list ?

### ISSUE THREAD

**Issue by ItamarGronich** [travis-ci/docs-travis-ci-com#1012]
I seem to be getting emails from builds at work to my private email account. How do i unsubscribe from this ?

**Comment by BanzaiMan** [comment]
Could you check the git configuration you are using for the repositories for your work? https://docs.travis-ci.com/user/notifications/#Changing-the-email-address-for-build-notifications

**Comment by ItamarGronich** [comment]
Yeah, well I'd like a way to manually override this in the mail itself.
Like an unsubscribe link.
Suppose for a second someone , who I have no connection with, adds me to a
list​. Shouldn't I have control over that kind of thing?

Thanks for the quick response by the way.

**Comment by bogdanap** [comment]
There is now an unsubscribe link in all our outgoing emails.

**Comment by maxmcd** [comment]
@bogdanap how does one re-subscribe if this link is clicked unintentionally?

**Comment by bogdanap** [comment]
Hi @maxmcd! If you unsubscribed by mistake, you can send an email to the lovely folks at support@travis-ci.com and they can help get you back on the list. 😄
