### ISSUE TITLE
In PHP docs, mention that `phpunit` is pre-installed, may cause problems if it is also installed via Composer

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/docs-travis-ci-com#1016]
The user may choose to install a different version of `phpunit` via Composer. Invoking `phpunit` by itself could cause problems, such as ones mentioned in https://github.com/travis-ci/travis-ci/issues/7226 and https://github.com/travis-ci/travis-ci/issues/7455.

The path to it is configurable, and it is probably best to leave it to the user to invoke `phpunit` correctly if the user chooses to use `phpunit` that we do not provide.

**Comment by dregad** [comment]
Make sure to mention that the installed PHPUnit version is determined by the PHP version.
