### ISSUE TITLE
Elastic Beanstalk deploy documentation seems out of sync with dpl documentation

### ISSUE THREAD

**Issue by wearhere** [travis-ci/docs-travis-ci-com#1023]
`dpl` was changed to require the `bucket_name` option [here](https://github.com/travis-ci/dpl/pull/188). However https://docs.travis-ci.com/user/deployment/elasticbeanstalk/#Optional-settings says that that option is optional.

**Comment by plaindocs** [comment]
Thanks for reporting @wearhere .

I think https://github.com/travis-ci/docs-travis-ci-com/pull/1021 which I've just merged in fixes your issue. Please reopen or file a new issue if you notice any further changes.

**Comment by wearhere** [comment]
Indeed thanks!
