### ISSUE TITLE
Build stages and breaking the build

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1025]
Here's a suggestion about how we explain in the doc what would break a build.

At the moment, the information on what would make a build as failed/errored is somehow divided between these two sections:
* https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build
* https://docs.travis-ci.com/user/customizing-the-build#Deploying-your-Code

We've received some feedback about this, and it seems that this information seems to be difficult to locate inside the docs.

One interesting suggestion that we received was to move this information a bit so that it's closer to the build lifecycle docs and include the difference and intention of each stage. What do you think?

**Comment by plaindocs** [comment]
**Absolutely**.

Do you want to take a crack at it or shall I just go ahead and make a PR?

**Comment by iriberri** [comment]
@MariadeAnton @plaindocs - this is the issue I mentioned yesterday that was pending in my docs TODO list, which probably makes sense to tackle together with any reorganization of "Customizing the build".
