### ISSUE TITLE
Prism JS plugin to display filename

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#1038]
Hidden away at the bottom of this page:

http://prismjs.com/plugins/show-language/

is the options of using `data-language` CSS attribute to display a filename for the code example.

It requires adding the plugin to Prism, and then tweaking the CSS to make the display of the filename more distinct, but would allow us to cut out quite a lot of boiler plate "put this into your .travis.yml" type text.

It does however require some fairly ugly css in the markdown such as

<pre>
```
Some normal code here
```
{:  data-language=".travis.yml"}
</pre>

@lislis @MariadeAnton thoughts?

**Comment by lislis** [comment]
@plaindocs I'm quite fond of code snippets saying what language or file it stems from +1
If you can live with the ugly markdown, I can live with tweaking the CSS for display 💃

**Comment by plaindocs** [comment]
Sounds good to me.

**Comment by plaindocs** [comment]
@lislis wanna take a look at this and let me know what you need from my side?

**Comment by lislis** [comment]
@plaindocs sorry, I forgot about this one.
Here you go https://github.com/travis-ci/docs-travis-ci-com/pull/1209

**Comment by BanzaiMan** [comment]
This was merged.
