### ISSUE TITLE
Missing /repo/{slug|id}/requests endpoint in API Docs

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1047]
We document how to trigger builds programatically in https://docs.travis-ci.com/user/triggering-builds/, and I can see that this section is also being taken into account in the PR for API V3: https://github.com/travis-ci/docs-travis-ci-com/pull/996

However, this endpoint (`/repo/{slug|id}/requests`) seems to be missing in the Repositories section of the API Docs: https://docs.travis-ci.com/api#repositories

**Comment by plaindocs** [comment]
Although it doesn't say so, I *think* that is already API V3?

Good catch, I'll look into this.

**Comment by plaindocs** [comment]
Yep, confirming that that is a V3 endpoint, closing this.
