### ISSUE TITLE
Question: What are the benefits of caching Gradle dependencies?

### ISSUE THREAD

**Issue by chao1995** [travis-ci/docs-travis-ci-com#1058]
In [documentation about caching dependencies](https://docs.travis-ci.com/user/caching/#Things-not-to-cache), it mentions:

> The cache’s purpose is to make installing language-specific dependencies easy and fast, so everything related to tools like Bundler, pip, Composer, npm, Gradle, Maven, is what should go into the cache.
<br>Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source:

I am using Gradle in my Java project and below [recommended configuration](https://docs.travis-ci.com/user/languages/java/#Caching).

```
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
```

It seems what Gradle caches is those `.jar` files, which should fall in the category "quick to install".

So my question is, why Travis recommends caching Gradle dependencies if `.jar` files are quick to install but slow to download?

**Comment by 1HVhD25fCP1pMXAo1bdxZtb3L6qQR9MqGD** [comment]
Moilui0609@gmail.com mickatiff@hotmail.fr.com mickatiff57@gmail.com
mickabt40609@gmail.com mickatiff@hotmail.fr.com
