### ISSUE TITLE
does travisCI only work with github

### ISSUE THREAD

**Issue by madhugilla** [travis-ci/docs-travis-ci-com#1063]
Hi,
Questions

1) Does https://travis-ci.org/ work only if the sourcecode is present in GitHub ??
2) Is it the same for Prviate Repos ??
3) If TravisCI works with other soruce control providers with GIT, can you please provide few links on how to configure the same ??

Tx

**Comment by BanzaiMan** [comment]
Hello. We provide best developer experiences with GitHub.

We may provide integration with other hosted git services, but at this time, we do not have that work on our roadmap. Thank you.
