### ISSUE TITLE
GitHub Pages deployment: document behavior

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1064]
Hey there!

It seems that the current behavior of the GitHub Pages deploy may be a bit confusing or cause some inconveniences. At the moment, this deployment deletes the content on the target branch and uploads all the files generated in build time: https://github.com/travis-ci/dpl/blob/bdc795f335e23c3f470fbda89aa4a173d79dd424/lib/dpl/provider/pages.rb#L52-L62

However, this means that the previous files available in the `gh-pages` branch (or the configured branch) will be replaced and the history will be lost. This may be assumed by some people, but I think it could be worth it to add a note explaining how this deploy works to make sure nobody loses their files by error.

What do you think?

**Comment by webknjaz** [comment]
Ref: travis-ci/travis-ci#7562
Ref: webknjaz/dpl#1
Ref: travis-ci/docs-travis-ci-com#1015

**Comment by webknjaz** [comment]
@iriberri perhaps you could team up with @remyabel (travis-ci/travis-ci#7562) and craft some better docs improvement ^^

**Comment by danielo515** [comment]
Independently of incremental publishing feature becoming true or not, you should clearly state that this overrides any content on your target branch, which is unrecoverable. This was a bad surprise for me, hopefully I had a backup, but not everyone will have such luck.

**Comment by plaindocs** [comment]
Closed by #1184
