### ISSUE TITLE
Travis Uses Wrong Node Version

### ISSUE THREAD

**Issue by gpresland** [travis-ci/docs-travis-ci-com#1083]
Travis is not following the config file and is using a totally different version of Node.

My `.travis.yml`
```
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
install:
  - npm install
script:
  - npm run test
```

Config generated for the build:
```
{
  "language": "node_js",
  "node_js": "7",
  "install": [
    "npm install"
  ],
  "script": [
    "npm run test"
  ],
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
```

Build fails, and job log shows:
```
$ node --version
v0.10.36
```

Documentation followed from https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions.

**Comment by BanzaiMan** [comment]
This is due to https://github.com/travis-ci/travis-ci/issues/7571, which is caused by https://github.com/nodejs/nodejs.org/issues/1191. Please try again once npmjs.org is back up.
