### ISSUE TITLE
Review jobs/builds wording on "limiting concurrent builds"

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1087]
In the https://docs.travis-ci.com/user/customizing-the-build/#Limiting-Concurrent-Builds section, we're still using the legacy "builds" word to refer to a job. I think we should review this and make a couple updates :) 💛

**Comment by MariadeAnton** [comment]
Thank you, @iriberri - I totally agree :) 

I think this is part of the proposed consistency improvements at https://github.com/travis-pro/team-sapphire/issues/562#issuecomment-283072652 :) 

Are you okay if we close this as duplicated? feel free to add there any more details missing!

**Comment by iriberri** [comment]
Sure, @MariadeAnton. Thanks for linking the other issue here!

**Comment by plaindocs** [comment]
Hi @iriberri , do you fancy updating that section using the text from the Beginners Guide (https://github.com/travis-ci/docs-travis-ci-com/pull/1176) as a reference?
