### ISSUE TITLE
trigger debug builds: Where are the docs for this?

### ISSUE THREAD

**Issue by ntwb** [travis-ci/docs-travis-ci-com#1104]
Via https://blog.travis-ci.com/2017-04-06-api-v3-is-here

> Our API can be used to automate many of your Travis CI build processes. Examples include:
> ...
> trigger debug builds

I've searched for the docs on this but couldn't find any, so two questions:

1. Is this available for use in `.travis.yml` or is it an API only feature?
2. Are there any docs published?

**Comment by plaindocs** [comment]
Thanks for point that out @ntwb 

We have developer docs here https://developer.travis-ci.org/ , but we're also working on linking to them more obviously from our other docs.

If you want to trigger builds this doc covers that https://docs.travis-ci.com/user/triggering-builds/

**Comment by ntwb** [comment]
Thanks though I still don't see anything in regard to **debug** (searched both pages)

Also to reiterate my first question: Can I trigger a **debug** build by adding a flag/option in my `.travis.yml` file?

**Comment by plaindocs** [comment]
https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by ntwb** [comment]
This is awesome, thanks a bunch @plaindocs 💐
