### ISSUE TITLE
Update documentation for iphonesimulator9.3

### ISSUE THREAD

**Issue by fulldecent** [travis-ci/docs-travis-ci-com#1106]
*👍  I am a paying customer.*

This page claims Travis works with `iphonesimulator9.3`:

https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-8

This build uses the current prescribed advice but cannot access `iphonesimulator9.3`:

https://travis-ci.org/fulldecent/FDWaveformView/builds/222185254#L371

> xcodebuild: error: SDK "iphonesimulator9.3" cannot be located.

Documentation should be updated to include the correct prescription.

**Comment by staguer** [comment]
Is iPhone iOS 9 support gone? Would be nice to have it back, at least until iOS 11 is released.

**Comment by plaindocs** [comment]
@emdantrim any idea on this?

**Comment by emdantrim** [comment]
I didn't make that documentation, and I didn't make the build image that it reflects. It looks to me like the SDK is definitely not present on the current iteration of the image, though.

@fulldecent did this previously work on the `xcode8` image, or is this your first time building on that image?

**Comment by fulldecent** [comment]
This was my first time building on the image. I have since switched to 10.3 and that is working.

**Comment by fulldecent** [comment]
This is fixed now, closing
