### ISSUE TITLE
How to define a multi-arch build?

### ISSUE THREAD

**Issue by mouse07410** [travis-ci/docs-travis-ci-com#1109]
This is not a bug report, but a plea for help.

I have a few (open-source) projects currently using Travis CI. My goal is to test-build the following environments:
 
- Linux:
   - build with clang and gcc with "-m64" (test 64-bit builds)
   - build with clang and gcc with "-m32" (test 32-bit builds)
- Mac OS X (Xcode-8.3)
   - build with clang and gcc

Ideally, for the above OS I'd like to build several makefile-defined targets (`static`, `shared`, `asan`, `coverage`).

And it would be great if (on Linux?) I could build for ARM platforms (cross-compile).

I know how to build for 32-bit and 64-bit on Linux - this works:
```
language: c
compiler:
  - gcc
  - clang
env:
  - BUILD=x86_64-linux-gnu
    CFLAGS=-m64 LDFLAGS=-m64
  - BUILD=i686-linux-gnu
    CFLAGS=-m32 LDFLAGS=-m32
. . . . .
```

I know how to build for Linux and Mac OS X - this works:
```
language: cpp

os:
  - linux
  - osx

.  .  .  .  . 
```

But (a) I am unable to combine the two - aka make Linux targets build on 32-bit and 64-bit *and* have MacOS builds (attempt to directly combine the above two examples failed, of course - Travis refused to parse the resulting `.travis.yml` file), and (b) I seem unable to invoke those other targets (that normally are invoked via `make coverage`, `make asan`, `make test`, etc.).

I went through the online docs, but either it is too terse, or I am too dense - regardless, I failed to accomplish the above.

Would appreciate any help. Especially seeing an example of how this can be done.

Thanks!

**Comment by plaindocs** [comment]
Hi @mouse07410 

Please drop support@travi-ci.com a line, they will be able to help you out, and we'll update the docs after that.
