### ISSUE TITLE
"OS X" is misspelled as "OSX" in several places in the documentation and its new name is "macOS" anyway.

### ISSUE THREAD

**Issue by shlomif** [travis-ci/docs-travis-ci-com#1117]
Hi! https://docs.travis-ci.com/user/languages/python/ reads "OSX" which was never correct - the name was "OS X" and it was now renamed as "macOS", see http://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-programming-macOS . Should it be renamed, and if so - to what? I should note that "OS" appears in several other places.

**Comment by plaindocs** [comment]
@emdantrim this is probably something we should fix right?

**Comment by emdantrim** [comment]
@plaindocs sure! though, at some point or another we should also make it so that `os: osx` and `os: macos` route to the same place, which has been part of our hesitation on updating the nomenclature across all of our documentation and application.

**Comment by plaindocs** [comment]
Yeah, so we're staying consistent on "OS X" (not "OSX") until we switch to "macos" across the board.  Fix for misspellings above.

**Comment by shlomif** [comment]
On Tue, 06 Jun 2017 04:57:17 -0700
Plaindocs <notifications@github.com> wrote:

> Closed #1117.
> 

Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://shlomifishswiki.branchable.com/Self-Sufficiency/

I thought I was wrong once, but I was mistaken.
    — Via Dave Mitchell

Please reply to list if it's a mailing list post - http://shlom.in/reply .
