### ISSUE TITLE
Check and update images

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#1128]
We've got a ton of images that haven't been checked for a while, 

* [x] images/admin_only_toggle.png
* [x] images/anika-hs.png
* [x] images/atom_feed_add.png
* [x] images/atom_feed_view.png
* [ ] images/autocancellation-example.png
* [x] images/autocancellation.png
* [x] images/awesome_customers.jpg
* [x] images/bluebox.png
* [x] images/blueboxteam.png
* [x] images/blueboxteam-small.png
* [x] images/caches-item.png
* [x] images/cli-cache.png
* [x] images/cloudcontrol.png
* [ ] images/coveralls-button.png
* [x] images/cron-adding.png
* [x] images/cron-created.png
* [x] images/cron-deleting.png
* [x] images/cron-section.png
* [ ] images/deploy.png
* [ ] images/dscape.png
* [ ] images/encrypt.png
* [ ] images/heroku.png
* [ ] images/hipchat_token_screen.png
* [ ] images/hiro-animated.gif
* [ ] images/hiro-hs.png
* [ ] images/justine-hs.png
* [ ] images/launchpad-slug.png
* [ ] images/logo-engineyard.png
* [ ] images/logo.svg
* [ ] images/made-in-berlin-badge.png
* [ ] images/new-tricks.png
* [ ] images/nodejitsu.png
* [ ] images/personal-token.jpg
* [ ] images/piotr-hs.png
* [ ] images/qos.001.jpg
* [ ] images/saucelabs.png
* [ ] images/settings-env-vars.png
* [ ] images/settings-ssh-key.png
* [ ] images/srcclr-travis.png
* [ ] images/stats.001.png
* [ ] images/stats.002.png
* [ ] images/stats.003.png
* [ ] images/stats.004.png
* [ ] images/stats.005.png
* [ ] images/stats.006.png
* [ ] images/stats.007.png
* [ ] images/Tim_Lucas_200px.jpg
* [ ] images/token.jpg
* [ ] images/travis-and-pusher-in-love.jpeg
* [ ] images/travis-branches.png
* [ ] images/travis-loves-code-climate.png
* [ ] images/travis-mascot-200px.png
* [ ] images/travis-mascot-400px.png
* [ ] images/travis-mascot-600px.png

## images/apps:
* [ ] atom.jpg
* [ ] bickle.jpg
* [ ] brackets.jpg
* [ ] build-checker-app.png
* [ ] buildnotify.jpg
* [ ] catlight-tray.png
* [ ] ccmenu.jpg
* [ ] cctray.jpg
* [ ] chrome-github-status.jpg
* [ ] chrome-github-travis.jpg
* [ ] chrome-my-travis.jpg
* [ ] ci-status.png
* [ ] cli.jpg
* [ ] comradetravis.jpg
* [ ] cron.jpg
* [ ] ducksboard.jpg
* [ ] falken.jpg
* [ ] firefox-travis-lite.jpg
* [ ] git.png
* [ ] jarvis.jpg
* [ ] mantis.jpg
* [ ] node-build-monitor.jpg
* [ ] nodegh.jpg
* [ ] node-travis-encrypt.jpg
* [ ] project-monitor.jpg
* [ ] screensaver-ninja.gif
* [ ] siren-android.jpg
* [ ] siren-ios.jpg
* [ ] siren-windows.jpg
* [ ] siren-windows-phone.jpg
* [ ] status-gravatar.jpg
* [ ] team-dashboard.jpg
* [ ] travalizit.jpg
* [ ] travis7.jpg
* [ ] travis-build-watcher.jpg
* [ ] travis-encrypt.jpg
* [ ] travisify-node.jpg
* [ ] travisify-ruby.jpg
* [ ] travis-inside.jpg
* [ ] travis-jr.jpg
* [ ] travis-light.jpg
* [ ] travis-lite.jpg
* [ ] travis-surveillance.jpg
* [ ] travis-tools.jpg
* [ ] travis-wall.jpg
* [ ] travis-web.jpg
* [ ] tron.png
* [ ] vim.jpg
* [ ] weblint.jpg

## images/error:
* [ ] 404-hills-left.svg
* [ ] 404-hills-right.svg
* [ ] excavator.svg
* [ ] pensive-travis.svg

##  images/screenshots:
* [ ] concurrent-builds-how-to.png

## images/ui:
* [ ] cones.svg
* [ ] docs-desktop.svg
* [ ] footer-logo.svg
* [ ] icon-arrowtabs.svg
* [ ] icon-flag.svg
* [ ] search.svg
* [ ] travis-logo.svg

**Comment by minhtrangcherry** [comment]
Helps me

**Comment by iriberri** [comment]
I was going to open a ticket on outdated screenshots but it's probably better to reuse this one.

We got a report about the screenshot in https://docs.travis-ci.com/user/private-dependencies/#User-Key (`settings-ssh-key.png`), which is indeed pretty old.
