### ISSUE TITLE
Simulators list in Objective-C docs page is not appearing

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1146]
https://docs.travis-ci.com/user/languages/objective-c

![image](https://cloud.githubusercontent.com/assets/1730320/25701028/c1f8850e-30ca-11e7-9871-988ed547f2dd.png)

I just noticed that the Simulators list is empty, but it should be showing the data available here: https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/_data/xcodes.yml. It looks like this is caused by the new structure of the yml file.

**Comment by plaindocs** [comment]
Oops! Good catch @iriberri !

@emdantrim do you have time to take a look?

**Comment by cotsog** [comment]
@emdantrim: sorry, it might be my fault => https://github.com/travis-ci/docs-travis-ci-com/commit/310088a8d3e4c28bfc3c9138345dd10b6db8cc07

I thought the simulators were now under each image.

**Comment by plaindocs** [comment]
Yeah, someone needs to tweak

```
{% for simulator in site.data.xcodes.simulators %}

### {{ simulator.name }}

The following devices are provided by the {{ simulator.name }} simulator:

{% for device in simulator.devices %}

- {{ device }}
  {% endfor %}

{% endfor %}
```

to match the new structure.

**Comment by emdantrim** [comment]
Simulators are under each image, but the devices that each OS simulator supports are listed in the "Simulators" section. It's supposed to be more of a reference.

This is something that's more inherited by the way that the `objective-c` page used to be laid out. so if this all looks counter-intuitive to you (it does look counter-intuitive to me!) then we should definitely change how it is laid out.

**Comment by plaindocs** [comment]
Right. So the thing here is to first figure out what makes sense to tell people. I don't use or develop on mac, so have almost *no idea* how people expect to digest this info on what simulators have what devices.

once we know that we can figure out if we need to tweak the json or just the templating code. Make sense?

**Comment by emdantrim** [comment]
@plaindocs I'm absolutely +1 on that. I think that @cotsog is in the best position to determine whether or not we need this stuff listed or if users should assume that all simulators will be available for every version of iOS. I suspect that they'll probably know which devices support which iOS versions, though.

**Comment by plaindocs** [comment]
@BanzaiMan ^

**Comment by plaindocs** [comment]
Shall I just remove the Simulators section for now, and @cotsog can figure out if we should add it back?

**Comment by BanzaiMan** [comment]
What simulators are available will depend on the choice of the Xcode image, and this list is already generated in osx-ci-environment.md. Why not just link there? https://docs.travis-ci.com/user/osx-ci-environment#Xcode-version

**Comment by BanzaiMan** [comment]
I don't think duplication (even if it's automated) is useful here.
