### ISSUE TITLE
Tests failing after Travis environment update

### ISSUE THREAD

**Issue by cqx931** [travis-ci/docs-travis-ci-com#1152]
Ant tests now fail due to missing junit.jar.
![image](https://cloud.githubusercontent.com/assets/3056154/25740667/0a5a9e0a-31ba-11e7-897a-5ed6a80f2a5a.png)

https://travis-ci.org/dhowe/RiTa/builds/229034737

If I go back to the previous default image, the tests are passing.
https://travis-ci.org/dhowe/RiTa/builds/229036438

**Comment by iriberri** [comment]
Hi @cqx931, thanks for reporting this issue!

I'm closing this issue and moving it to our public tracker at [travis-ci/travis-ci](https://github.com/travis-ci/travis-ci/issues). We will continue taking care of this report here: https://github.com/travis-ci/travis-ci/issues/7706
