### ISSUE TITLE
[Objective-C] Use xcodebuild instead of xctool for Xcode > 8

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1186]
See also: https://github.com/travis-ci/docs-travis-ci-com/issues/805#issuecomment-262256179

[Travis CI uses `xctool` by default](https://docs.travis-ci.com/user/languages/objective-c#Default-Test-Script) to execute the tests in the Objective-C environment, [but xctool has deprecated support for building iOS projects](https://github.com/facebook/xctool/issues/704) although it seems it can be used to run tests.

For Xcode > 8, we are recommending our users to use xcodebuild with xcpretty instead. Could we include this in the Objective-C/ OS X documentation?

Example of the workaround:

```patch
---
  script:
-   - xctool -project MyProject.xcodeproj -scheme MyProject build test -sdk iphonesimulator
+  - xcodebuild -project MyProject.xcodeproj -scheme MyProject -sdk iphonesimulator build test | xcpretty
```

**Comment by plaindocs** [comment]
I can't see anything like that in our current docs. We also use keys such as 

```
language: objective-c
xcode_project: MyNewProject.xcodeproj # path to your xcodeproj folder
xcode_scheme: MyNewProjectTests
```

@iriberri would you be able to submit a PR to rewrite the entire Default Test Script section?

**Comment by iriberri** [comment]
Thanks for taking a look at this, @plaindocs!

I could give this a try with what I've learnt lately. However, I'm not really an expert in OS X builds, perhaps @cotsog could bring some extra light here? 💛

**Comment by matrush** [comment]
As of today, the `xctool` already mark `build` action as deprecated, should we replace `xctool` with `xcodebuild` in `objective_c.rb`?

**Comment by plaindocs** [comment]
Ping @iriberri @cotsog any volunteers to update these docs?

**Comment by YF-Tung** [comment]
I am getting this error too, looking forward to a fix!

**Comment by YF-Tung** [comment]
Great! I did use `xcodebuild` instead then, but it's great that it's fixed!

**Comment by mjm** [comment]
Be sure to add `set -o pipefail && ` in front of your xcodebuild command. Otherwise, the shell will assume that because `xcpretty` exits with a successful code, everything was fine, and if your build fails, your Travis job will still pass.

**Comment by cotsog** [comment]
Good catch! I updated my recipe above accordingly. Thanks!

**Comment by mjm** [comment]
No workaround needed here anymore! https://blog.travis-ci.com/2018-08-15-deprecating-xctool

Closing this issue.
