### ISSUE TITLE
Remove iOS simulators from docs / clarify iOS simulator documentation

### ISSUE THREAD

**Issue by emdantrim** [travis-ci/docs-travis-ci-com#1241]
Created in the wake and context of #1146.

Can we remove simulators from the [osx-ci-environment](https://docs.travis-ci.com/user/osx-ci-environment#Xcode-version) page as well? I can't imagine that they're terribly useful there either.

We would probably be safe saying something like "all possible simulators will be present in each image".
There are specifics (i.e. device pairs, so like, "iPhone 7 running iOS 10.whatever paired with Apple Watch 38mm running WatchOS 2.whatever") that are not mentioned in the documentation anyway. Repeating the same lines over and over in the documentation just kind of makes it seem generally dense, and if I'm correct, if people want to use the simulators, they need to specifically target simulator UUIDs, which we also don't put in the documentation -- so, they'll end up needing to run a build to see what the UUIDs are, anyway (and including those in documentation sounds like it'd be really dense and awkward, too.)

Alternatively, we should investigate building some better, more technical approach to displaying this information. A bulleted list in the middle of information presented in prose sorta seems to me like a disservice. Perhaps this could be rolled into / introduced alongside the more programmatic generation of information that is happening along with the Linux build environment updates that :blue_heart: has been working on.

**Comment by solarce** [comment]
I don't have a good opinion on how to better display or its useful to display at all, so I am 👍 on removing it if there's not a solution that feels _good_ for keeping them in the docs.

**Comment by Lyoness** [comment]
Yeah, an output of  build may be the way to go to show simulators present, and `diff` to show differences between minor xcode version updates.
