### ISSUE TITLE
All mongodb tests pass locally, two fail on travis.

### ISSUE THREAD

**Issue by e-oj** [travis-ci/docs-travis-ci-com#1266]
I'm having an Issue where all my MongoDB tests pass locally but two tests continue to fail on travis. Here's my .yml
```
language: node_js
node_js:
  - "node"
  - "7"
  - "6"
cache:
  directories:
    - "node_modules"
services: mongodb
before_script:
  - sleep 15
```

I thought it might be the MongoDB version  so I ran the tests locally with new and old versions of MongoDB and they all pass so I'm stuck. Any help would be appreciated. Thanks.

**Comment by BanzaiMan** [comment]
Sorry to hear about the troubles you are having. However, this repository is for documentation, not troubleshooting.

You may be able to reproduce the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally).

I'm closing this now.

Thanks.
