### ISSUE TITLE
Document how to select minimal vs full Trusty build image

### ISSUE THREAD

**Issue by edmorley** [travis-ci/docs-travis-ci-com#1267]
The documentation for the beta Trusty environment ([here](https://docs.travis-ci.com/user/trusty-ci-environment/#Image-differences-from-Precise)) says:

> For our Trusty based environments, we’re making a smaller set of images that includes:
> * minimal image which contains a small subset of interpreters, as well as docker and packer.
> * considerably larger image which contains (almost) all runtimes and services present in Precise environments.

However I can't find a mention of how Travis chooses between each of those images, and what the larger image contains that the smaller doesn't?

Initially I thought perhaps selecting the smaller image was performed by not specifying a `language` key in `.travis.yml` at all, however doing so resulted in the job installing ruby instead, which was a bit puzzling:
https://travis-ci.org/mozilla/treeherder/builds/242954322#L226

My use-case is trying to select the smaller image to speed up job times, since I'm experimenting with using Docker Compose (so that we can test against Ubuntu 16.04) - which means we don't need anything but Docker/Compose installed.

Many thanks!

**Comment by MariadeAnton** [comment]
you're absolutely right, @edmorley - thanks for bringing this up!

You can use the minimal image by selecting `language: minimal` or `language: generic`. 

We'll update this in the docs too :)

**Comment by edmorley** [comment]
Hmm so I've tried out the various {generic, minimal, bash, shell, sh} language combinations on Trusty using both containers and sudo:
https://travis-ci.org/edmorley/travis-testing/builds/250035772

...and for completeness, the same as that but using Precise:
https://travis-ci.org/edmorley/travis-testing/builds/250035931

Notably:
* All of {generic, bash, shell, sh} seem identical and don't have any language specific functionality (other that what's pre-installed in the base image)
* However the minimal runs ruby-specific commands (such as `rvm use default`):
  - container: https://travis-ci.org/edmorley/travis-testing/jobs/250035781
  - gce sudo: https://travis-ci.org/edmorley/travis-testing/jobs/250035783

@meatballhat, is this intentional?

I see also that in travis-ci/packer-templates#454, generic is soon going to result in sugilite (the big image) instead, so should probably be excluded from any documentation added here.

**Comment by edmorley** [comment]
Oh right I see now, there are two places `lang` controls -- the initial image selection from job-board, and then also the runtime scripts run by travis-build here:
https://github.com/travis-ci/travis-build/blob/75a27e5e4a41246790ea54a5227514cf8a9374bf/lib/travis/build.rb#L26-L47

The travis-build aliases are out of sync with the image language tags here:
https://github.com/travis-ci/packer-templates/blob/57d68e763001fa88f55bddc9b16d3259ebc925cf/cookbooks/travis_ci_connie/attributes/default.rb#L64-L68

`generic` works, since that's the class name:
https://github.com/travis-ci/travis-build/blob/75a27e5e4a41246790ea54a5227514cf8a9374bf/lib/travis/build/script/generic.rb

But `minimal` falls back to the default:
https://github.com/travis-ci/travis-build/blob/75a27e5e4a41246790ea54a5227514cf8a9374bf/lib/travis/build/script/ruby.rb

I'll open a PR against travis-build.

**Comment by BanzaiMan** [comment]
@meatballhat @MariadeAnton Did we ever support `language: minimal`?

**Comment by edmorley** [comment]
I'd only been using `minimal` since it was mentioned above, and it's listed in the package configs:
https://github.com/travis-ci/packer-templates/blob/fb7eee054b0c4bb3e02d5d3db78a2d95170916f1/cookbooks/travis_ci_connie/attributes/default.rb#L67

Also, since travis-ci/packer-templates/pull/454, `generic` results in the larger sugilite image, so if one wants the smallest image possible with the least time spent during travis-build, the options are to use one of the identical langs: `{bash, shell, sh}`.

If it's desired to deprecate `minimal`, that would be fine with me, it would just be good to (a) remove it from the packer config, (b) make the docs clear that it will result in a larger/more time consuming image.

**Comment by edmorley** [comment]
For anyone reading via email notifications, I've edited the above a bit more to make sense, but you'll need to view the live version.

**Comment by MariadeAnton** [comment]
Just adding a note here to confirm what I've updated in the comment above.  Since  the update on July, 12th `language: generic` points to the full/bigger image: https://docs.travis-ci.com/user/build-environment-updates/2017-07-12/

And to use the minimal one we can use `language: minimal` :) 

Thanks for all of your investigation, Ed!

**Comment by edmorley** [comment]
Looks like the stale bot needs to look at the `docs` and/or `ready-to-doc` labels too.

**Comment by edmorley** [comment]
To repeat my comment from above:

> Looks like the stale bot needs to look at the `docs` and/or `ready-to-doc` labels too.

**Comment by plaindocs** [comment]
Updated stale bot in 210f9ff0
