### ISSUE TITLE
Specifying Node.js versions #

### ISSUE THREAD

**Issue by m67hoff** [travis-ci/docs-travis-ci-com#1296]
Hy I'm new to Travos - and I stumbled on the node version example in:

https://docs.travis-ci.com/user/languages/javascript-with-nodejs
 it seems the  version  in   "6"  is not supported

**Comment by plaindocs** [comment]
Hi, thanks for the info. I can't find anything unexpected with node version "6". 

Please email support@travis-ci.com if you need further help with this.
