### ISSUE TITLE
after_failure not run after failure?

### ISSUE THREAD

**Issue by lwaldron** [travis-ci/docs-travis-ci-com#1297]
I have the following in my .travis.yml file for an R package at https://github.com/waldronlab/curatedMetagenomicDataCuration. The .push_gh_pages.sh script gets run after a successful package check, but not after a package check where the unit tests produce any error. I would like this script to be run for both success and failure.

```
after_script:
  - ./.push_gh_pages.sh
after_failure:
  - ./.push_gh_pages.sh
```

**Comment by BanzaiMan** [comment]
This is not a documentation issue.

**Comment by BanzaiMan** [comment]
In https://travis-ci.org/waldronlab/curatedMetagenomicDataCuration/builds/250058492#L798, you see that your build is failing during the `script` phase. It is most likely an issue with your R project, and it should be addressed in https://github.com/travis-ci/travis-ci/issues/new following the community support guidelines.

**Comment by lwaldron** [comment]
Sorry @BanzaiMan for posting in the wrong forum, I've posted there now. Yes, I have the script failing intentionally to demonstrate that the `after_failure` script does not get run.
