### ISSUE TITLE
"android list sdk" is deprecated

### ISSUE THREAD

**Issue by justincpollard** [travis-ci/docs-travis-ci-com#1299]
The Android documentation (https://docs.travis-ci.com/user/languages/android/) suggests running `android list sdk --no-ui --all --extended` to determine the exact component names and descriptions to use in `.travis.yaml`. However, that command is deprecated:

```
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
"android" SDK commands can be translated to sdkmanager commands on a best-effort basis.
Continue? (This prompt can be suppressed with the --use-sdk-wrapper command-line argument
or by setting the USE_SDK_WRAPPER environment variable) [y/N]: y
/Users/justinpollard/Dev/android-sdk/tools/android: line 115: ${trysdkresponse,,}: bad substitution
Invalid or unsupported command "list sdk --no-ui --all --extended"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
```

Instead, it seems that the new command is `tools/bin/sdkmanager --list`. There may be other required options, but this seems close to what the replacement should be.

**Comment by davivel** [comment]
The deprecation came with SDK Tools 25.2.3. Related to travis-ci/issues/7331

**Comment by iriberri** [comment]
Hi @justincpollard , thank you so much for opening this issue.

We're currently working on a new Beta Android image on Trusty in which indeed the `android` command tool is deprecated and `sdkmanager` is used instead.

We're tracking this release at https://github.com/travis-ci/travis-ci/issues/5370#issuecomment-308987973, and at this specific comment I mention the steps that you can follow to test the new image.

That said, I'm noting this down and adding this issue to our internal ticket to make sure that the Android docs get updated accordingly when this new image if officially released - thank you so much for pointing this out.
