### ISSUE TITLE
Document "region" option for opsworks

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/docs-travis-ci-com#1302]
https://github.com/travis-ci/dpl/blob/v1.8.39/lib/dpl/provider/ops_works.rb#L29 shows that the OpsWorks provider takes the `region` option, but this is not documented in https://docs.travis-ci.com/user/deployment/opsworks (nor https://github.com/travis-ci/dpl/#opsworks)

**Comment by anttitevanlinna** [comment]
I was fighting this issue for 2 hours. Only debugging with AWS cli gave me the insight that the region is really a mandatory parameter in getting deployments working.

**Comment by plaindocs** [comment]
Related to https://github.com/travis-ci/dpl/issues/191
