### ISSUE TITLE
Two new note types

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#1311]
Hey @MariadeAnton and @lislis 

What do you think of adding two new note classes like the [Beta note](https://docs.travis-ci.com/user/build-stages/)

One for [Private Features](https://docs.travis-ci.com/user/languages/ruby/#Caching-Bundler)

and 

One for the notice we're going to have about moving distro specific stuff to the evnironment reference. Something like

> We're moving all version numbers and other distro specific information over to
>  our reference pages at:
>  * [Precise](/user/reference/precise/)
>  * [Trusty](/user/reference/trusty/)
>  * [OS X](/user/reference/osx/)

**Comment by MariadeAnton** [comment]
That sounds like a great idea to me - like "Debug build" or "Debug job" right? :)
