### ISSUE TITLE
broken table in docs

### ISSUE THREAD

**Issue by duckinator** [travis-ci/docs-travis-ci-com#1317]
On the [Common Build Problems](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally) page, there's a table that's supposed to contain Docker Hub images, but it actually contains nothing.

I'm trying to find which image to use for debugging a Ruby build locally.

Screenshot:

![screenshot_2017-07-14_11-06-09](https://user-images.githubusercontent.com/39698/28217851-a24b9aa6-6884-11e7-85bd-c85754fa9106.png)

And [all of the images on Docker Hub](https://hub.docker.com/u/travisci/) don't have descriptions, so I can't even find it out on there.

**Comment by BanzaiMan** [comment]
Thanks for the report!
