### ISSUE TITLE
Missing info on newer pypy versions

### ISSUE THREAD

**Issue by Faboor** [travis-ci/docs-travis-ci-com#1337]
The section Languages -> Python -> [PyPy Support](https://docs.travis-ci.com/user/languages/python/#PyPy-Support) is missing information about the 'new' format for specifying pypy3 versions.
I am not quite sure what the proper specs for this should be, but newer pypy versions for Python 3 are specified for example as `python: 'pypy3.5-5.8.0'` (which is what I am currently using in my project). However I have seen some travis devs use ` python: "pypy3.5-5.7.1-beta"` about a month ago as well.

In any case, trying to figure out how to use pypy3.5 v5.8 took me some trial and error because of missing info in that page section.

(https://docs.travis-ci.com/user/languages/python/#PyPy-Support)

**Comment by BanzaiMan** [comment]
Related: #1249.
