### ISSUE TITLE
CSS for bullets in numbered lists

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#1350]
Hey @lislis

Bullet lists in numbered lists in the docs look slightly off balance. Is this something you might be able to fix? Pretty please.

Example in https://github.com/travis-ci/docs-travis-ci-com/pull/1176

**Comment by plaindocs** [comment]
I can't seem to attach an image to this issue.

**Comment by plaindocs** [comment]
http://awesomescreenshot.com/0686cmqn25

**Comment by lislis** [comment]
@plaindocs something like this? https://github.com/travis-ci/docs-travis-ci-com/pull/1351
