### ISSUE TITLE
Token partially visible in Image

### ISSUE THREAD

**Issue by jmks** [travis-ci/docs-travis-ci-com#1384]
On the `Embedding Status Images` page, the token is sanitized in the `Image URL` but not in the `Markdown` URL.

<img width="811" alt="screen shot 2017-08-21 at 6 19 14 pm" src="https://user-images.githubusercontent.com/4923990/29540729-f6a39824-869d-11e7-93db-2712a72aa8a6.png">

**Comment by BanzaiMan** [comment]
It should also change the deprecated `magnum.travis-ci.com` to the current `travis-ci.com`.
