### ISSUE TITLE
Update for trusty and separate version info into Environment reference

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#1422]
Hey awesome community maintainers!

We're making a clearer separation of reference info in Precise / Trusty vs howto information in the language pages, with a view to increasing maintainability. We've also added a rather lovely summary table to the languages pages.

This [PR for Node.js](https://github.com/travis-ci/docs-travis-ci-com/pull/1388/files) summarizes most of the changes, but in short:

1. Move all version info *out* of the language page into the Precise, Trusty and OS X reference pages.
1. Simplify language pages so the information is howto guides, as environment agnostic as possible. 
1. Reference the format in node.js

Could *you* help us do the same to the following community languages:

- [ ] C# @joshua-anderson, @akoeplinger and @nterry
- [ ] Crystal @asterite, @jhass, @waj, and @will
- [ ] D @ibuclaw, @klickverbot and @MartinNowak 
- [ ] Dart @nex3 and @a14n
- [ ] Haxe @andyli @waneck @Simn
- [ ] Julia @tkelman @ninjin @staticfloat @simonbyrne
- [ ] Nix @domenkozar @garbas and @matthewbauer
- [ ] R @craigcitro, @hadley, and @jimhester

Please comment here with the PR, and I'll check the languages off as we merge.

Thanks in advance!

**Comment by plaindocs** [comment]
And as a bonus request (do I get those?) if you feel like switching the maintainer data to the page metadata like in this [Perl6 PR](https://github.com/travis-ci/docs-travis-ci-com/pull/1423/files) that would be even more awesome.  <3

**Comment by tkelman** [comment]
There's no difference for Julia between precise and trusty.

**Comment by Joshua-Anderson** [comment]
For C# the only difference is that dotnet core is only supported by trusty. Moving C# from precise to trusty should be forwards compatible.

**Comment by MartinNowak** [comment]
D will also work with easily with older and newer gcc/clang/g++/clang++ compilers and binutils versions. So no trusty/precise/xenial issues on that side.

**Comment by andyli** [comment]
The Haxe support already works well with both precise and trusty at the moment. However, upstream is going to remove precise support soon. I will add that info once that happen (when Haxe 4 is released).

**Comment by plaindocs** [comment]
Thanks people!

**Comment by nex3** [comment]
I believe there's no difference for Dart.
