### ISSUE TITLE
How deploy to different servers depends on branches

### ISSUE THREAD

**Issue by khotey** [travis-ci/docs-travis-ci-com#1459]
I have 3 branches, production, stage, development and 3 server respectively. Can I configure if I push to development branch travis deploy to development server , If to stage branch deploy to stage server and etc. by server url ?

**Comment by BanzaiMan** [comment]
Define multiple deployment providers, each deploying on exactly one branch. https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A
