### ISSUE TITLE
Builds, Jobs, Stages, etc semantic overhaul

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#1476]
Make sure the rest of the docs are consistent with the definitions in [core concepts](https://docs.travis-ci.com/user/for-beginners/#Builds%2C-Jobs%2C-Stages-and-Phases):

* [ ] addons.md
* [ ] angular.md
* [ ] apps.md
* [ ] best-practices-security.md
* [ ] bower.md
* [ ] browser-extensions.md
* [ ] browserstack.md
* [ ] build-environment-updates.md
* [ ] build-feeds.md
* [ ] build-hacks.md
* [ ] build-stages.md
* [ ] caching.md
* [ ] cc-menu.md
* [ ] chrome.md
* [ ] code-climate.md
* [ ] common-build-problems.md
* [ ] conditional-builds-stages-jobs.md
* [ ] coveralls.md
* [ ] coverity-scan.md
* [ ] cron-jobs.md
* [ ] customizing-the-build.md
* [ ] database-setup.md
* [ ] deployment.md
* [ ] developer.md
* [ ] docker.md
* [ ] encrypting-files.md
* [ ] encryption-keys.md
* [ ] environment-variables.md
* [ ] firefox.md
* [ ] for-beginners.md
* [ ] getting-started.md
* [ ] github-oauth-scopes.md
* [ ] gui-and-headless-browsers.md
* [ ] hostname.md
* [ ] hosts.md
* [ ] ibm-power.md
* [ ] installing-dependencies.md
* [ ] ip-addresses.md
* [ ] jwt.md
* [ ] languages.md
* [ ] language-specific.md
* [ ] migrating-from-legacy.md
* [ ] multi-os.md
* [ ] notifications.md
* [ ] overview.md
* [ ] precise-to-trusty-migration-guide.md
* [ ] private-dependencies.md
* [ ] pull-requests.md
* [ ] repository-providers.md
* [ ] running-build-in-debug-mode.md
* [ ] sauce-connect.md
* [ ] sonarcloud.md
* [ ] sourceclear.md
* [ ] speeding-up-the-build.md
* [ ] ssh-known-hosts.md
* [ ] status-images.md
* [ ] travis-lint.md
* [ ] travis-pro.md
* [ ] triggering-builds.md
* [ ] uploading-artifacts.md
* [ ] vagrant.md
* [ ] what-is-travis.md
* [ ] .
* [ ] ./coveralls.md
* [ ] ./precise-to-trusty-migration-guide.md
* [ ] ./pull-requests.md
* [ ] ./cc-menu.md
* [ ] ./deployment
* [ ] ./deployment/engineyard.md
* [ ] ./deployment/bintray.md
* [ ] ./deployment/codedeploy.md
* [ ] ./deployment/boxfuse.md
* [ ] ./deployment/anynines.md
* [ ] ./deployment/azure-web-apps.md
* [ ] ./deployment/deis.md
* [ ] ./deployment/npm.md
* [ ] ./deployment/pages.md
* [ ] ./deployment/catalyze.md
* [ ] ./deployment/packagecloud.md
* [ ] ./deployment/openshift.md
* [ ] ./deployment/pypi.md
* [ ] ./deployment/custom.md
* [ ] ./deployment/s3.md
* [ ] ./deployment/chefsupermarket.md
* [ ] ./deployment/appfog.md
* [ ] ./deployment/bitballoon.md
* [ ] ./deployment/cloudfoundry.md
* [ ] ./deployment/gcs.md
* [ ] ./deployment/surge.md
* [ ] ./deployment/cloudfiles.md
* [ ] ./deployment/scalingo.md
* [ ] ./deployment/heroku.md
* [ ] ./deployment/launchpad.md
* [ ] ./deployment/lambda.md
* [ ] ./deployment/script.md
* [ ] ./deployment/bluemixcloudfoundry.md
* [ ] ./deployment/google-app-engine.md
* [ ] ./deployment/cloud66.md
* [ ] ./deployment/releases.md
* [ ] ./deployment/hackage.md
* [ ] ./deployment/modulus.md
* [ ] ./deployment/testfairy.md
* [ ] ./deployment/puppetforge.md
* [ ] ./deployment/elasticbeanstalk.md
* [ ] ./deployment/opsworks.md
* [ ] ./deployment/atlas.md
* [ ] ./deployment/rubygems.md
* [ ] ./deployment/firebase.md
* [ ] ./travis-pro.md
* [ ] ./sonarcloud.md
* [ ] ./language-specific.md
* [ ] ./build-stages.md
* [ ] ./triggering-builds.md
* [ ] ./multi-os.md
* [ ] ./encryption-keys.md
* [ ] ./coverity-scan.md
* [ ] ./running-build-in-debug-mode.md
* [ ] ./apps.md
* [ ] ./build-hacks.md
* [ ] ./encrypting-files.md
* [ ] ./hosts.md
* [ ] ./conditional-builds-stages-jobs.md
* [ ] ./getting-started.md
* [ ] ./caching.md
* [ ] ./migrating-from-legacy.md
* [ ] ./overview.md
* [ ] ./installing-dependencies.md
* [ ] ./status-images.md
* [ ] ./angular.md
* [ ] ./build-stages
* [ ] ./build-stages/share-files-s3.md
* [ ] ./build-stages/deploy-npm.md
* [ ] ./build-stages/matrix-expansion.md
* [ ] ./build-stages/share-docker-image.md
* [ ] ./build-stages/warm-cache.md
* [ ] ./build-stages/deploy-github-releases.md
* [ ] ./build-stages/deploy-heroku.md
* [ ] ./build-stages/using-yaml-aliases.md
* [ ] ./build-stages/deploy-rubygems.md
* [ ] ./build-stages/define-steps.md
* [ ] ./bower.md
* [ ] ./deployment.md
* [ ] ./best-practices-security.md
* [ ] ./what-is-travis.md
* [ ] ./customizing-the-build.md
* [ ] ./for-beginners.md
* [ ] ./browser-extensions.md
* [ ] ./cron-jobs.md
* [ ] ./github-oauth-scopes.md
* [ ] ./images
* [ ] ./images/travis_jwt.svg
* [ ] ./speeding-up-the-build.md
* [ ] ./ip-addresses.md
* [ ] ./developer.md
* [ ] ./browserstack.md
* [ ] ./gui-and-headless-browsers.md
* [ ] ./common-build-problems.md
* [ ] ./build-environment-updates.md
* [ ] ./addons.md
* [ ] ./docker.md
* [ ] ./repository-providers.md
* [ ] ./jwt.md
* [ ] ./notifications.md
* [ ] ./build-environment-updates
* [ ] ./build-environment-updates/2017-09-06.md
* [ ] ./build-environment-updates/2016-12-02.md
* [ ] ./build-environment-updates/2016-11-01.md
* [ ] ./build-environment-updates/2017-05-04.md
* [ ] ./build-environment-updates/2016-08-24.md
* [ ] ./build-environment-updates/2014-12-16.md
* [ ] ./build-environment-updates/2016-11-15.md
* [ ] ./build-environment-updates/2014-12-18.md
* [ ] ./build-environment-updates/2014-12-29.md
* [ ] ./build-environment-updates/2016-12-08.md
* [ ] ./build-environment-updates/2016-12-06.md
* [ ] ./build-environment-updates/2016-12-01.md
* [ ] ./build-environment-updates/2017-07-12.md
* [ ] ./build-environment-updates/2014-12-09.md
* [ ] ./build-environment-updates/2017-08-17.md
* [ ] ./build-environment-updates/2015-04-09.md
* [ ] ./build-environment-updates/2015-01-07.md
* [ ] ./build-environment-updates/2015-02-03.md
* [ ] ./sauce-connect.md
* [ ] ./code-climate.md
* [ ] ./chrome.md
* [ ] ./private-dependencies.md
* [ ] ./database-setup.md
* [ ] ./build-feeds.md
* [ ] ./languages
* [ ] ./languages/objective-c.md
* [ ] ./languages/perl.md
* [ ] ./languages/dart.md
* [ ] ./languages/erlang.md
* [ ] ./languages/nix.md
* [ ] ./languages/rust.md
* [ ] ./languages/csharp.md
* [ ] ./languages/smalltalk.md
* [ ] ./languages/groovy.md
* [ ] ./languages/python.md
* [ ] ./languages/crystal.md
* [ ] ./languages/ruby.md
* [ ] ./languages/go.md
* [ ] ./languages/r.md
* [ ] ./languages/d.md
* [ ] ./languages/scala.md
* [ ] ./languages/julia.md
* [ ] ./languages/javascript-with-nodejs.md
* [ ] ./languages/perl6.md
* [ ] ./languages/elixir.md
* [ ] ./languages/community-supported-languages.md
* [ ] ./languages/cpp.md
* [ ] ./languages/android.md
* [ ] ./languages/java.md
* [ ] ./languages/haxe.md
* [ ] ./languages/haskell.md
* [ ] ./languages/php.md
* [ ] ./languages/c.md
* [ ] ./languages/clojure.md
* [ ] ./firefox.md
* [ ] ./vagrant.md
* [ ] ./travis-lint.md
* [ ] ./sourceclear.md
* [ ] ./uploading-artifacts.md
* [ ] ./hostname.md
* [ ] ./ibm-power.md
* [ ] ./integration
* [ ] ./integration/platformio.md
* [ ] ./languages.md
* [ ] ./reference
* [ ] ./reference/trusty.md
* [ ] ./reference/osx.md
* [ ] ./reference/precise.md
* [ ] ./reference/overview.md
* [ ] ./ssh-known-hosts.md
* [ ] ./environment-variables.md

Related to https://github.com/travis-pro/team-jade/issues/645 and #1468

**Comment by MariadeAnton** [comment]
While at it, maybe it'd make sense to also answer this question? https://github.com/travis-ci/docs-travis-ci-com/issues/1500

`jobs.include`  vs `matrix.include` references.

**Comment by pradyunsg** [comment]
I think this is still relevant.

@stale reopen this?

**Comment by pradyunsg** [comment]
@stale Keep this open.

**Comment by Rakanfalroba** [comment]
1

**Comment by pradyunsg** [comment]
I'm pretty sure this isn't going to happen anytime soon. It's probably best to just let this close if no one responds by the time stale comes here again.
