### ISSUE TITLE
Add link to up-to-date list of supported JDKs to https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs

### ISSUE THREAD

**Issue by krichter722** [travis-ci/docs-travis-ci-com#1482]
The [Testing against multiple JDKs section of the docs](https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs) mentions

    - oraclejdk8
    - oraclejdk9
    - openjdk7

as an example of testing against multiple JDKs, however it's not clear whether this is the complete list or not.

**Comment by iriberri** [comment]
Hi @krichter722, thanks for opening this issue!

You can find the list of available JDKs in our environment pages

* For Trusty: https://docs.travis-ci.com/user/reference/trusty/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-images
* For Precise: https://docs.travis-ci.com/user/reference/precise/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-VM-images

Does this fully address your question?

**Comment by BanzaiMan** [comment]
@krichter722 https://docs.travis-ci.com/user/languages/java/#What-This-Guide-Covers points to the answers you seek (and what @iriberri pointed to).

**Comment by krichter722** [comment]
> @krichter722 https://docs.travis-ci.com/user/languages/java/#What-This-Guide-Covers points to the answers you seek (and what @iriberri pointed to).

Does that mean you don't even want links at the location where there're most useful? I don't think this is a good "Don't make me think" approach...

**Comment by plaindocs** [comment]
@krichter722 the issue is that there are multiple environments environments, with potentially different lists of JVMs. 

We are working on automating this information, and figuring out how best to display it usefully. In the meantime, we're providing information in one single place instead of spread across language and environment pages.

**Comment by krichter722** [comment]
> We are working on automating this information, and figuring out how best to display it usefully. In the meantime, we're providing information in one single place instead of spread across language and environment pages.

Good to hear. You can link an issue if there's one now or in the future and close this since work on a more general is in progress.
