### ISSUE TITLE
Conditionally install packages with apt plugin

### ISSUE THREAD

**Issue by NickeZ** [travis-ci/docs-travis-ci-com#1503]
I'm trying to stay on the container based infrastructure, that is, avoid using `sudo`. But I cannot figure out how to conditionally install packages. Right now I'm using the apt plugin to install doxygen/latex dependencies.. I would like to only install all the packages for doxygen/latex when it is the **cron** build type. Because I only generate/publish my docs daily, not with every commit.

**Comment by BanzaiMan** [comment]
There is no way to activate the addon conditionally. If you need to do that, you’d have to use ordinary commands (`sudo apt-get …` with bash `if` and others).

**Comment by NickeZ** [comment]
To bad.. so either I wait 1 minute on apt or I wait 1 minute on vm to boot..
