### ISSUE TITLE
Lower the PR doc's text density

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/docs-travis-ci-com#1516]
Currently https://docs.travis-ci.com/user/pull-requests (and possibly other intro docs) is quite dense. TOC and some reorganization would be helpful.

A related issue is a common confusion as to why two builds are triggered when a PR is opened. A link from the repo's Settings page to `/user/pull-requests` explaining why could be useful.

**Comment by joepvd** [comment]
Maybe it would be good to figure out what the common use case is. I think the following configuration is something a lot of people are often looking for:

```
branches:
  only:
  - master
  - /^v[0-9]+\.[0-9]+\[0-9]+$/
```

With PRs and Pushes enabled, this runs pushes (merge commits) on `master`, on (matching) tags, and on PRs.
