### ISSUE TITLE
Document group stable/edge/dev

### ISSUE THREAD

**Issue by edmorley** [travis-ci/docs-travis-ci-com#1539]
It would be good to document what effect `group: {stable, edge, dev}` has -- perhaps on the environment updates page?
https://docs.travis-ci.com/user/build-environment-updates/

From reading the source:
https://github.com/travis-ci/packer-templates/blob/a3a3143a92102e1cae90fa9fd63fa6925ba0e971/lib/image_tagger.rb#L53-L61
https://github.com/travis-ci/packer-templates/blob/a3a3143a92102e1cae90fa9fd63fa6925ba0e971/lib/image_tagger.rb#L76-L80

...it seems that:
* `dev` -> travis-cookbooks and packer-templates master branch (though does this include include test builds for PRs? if so that would be more risky to use)
* `edge` -> packer-templates master but travis-cookbooks uses whatever branch is set by `TRAVIS_COOKBOOKS_EDGE_BRANCH` (or failing that, `master`)
* `stable` -> quarterly manually selected image builds

Without knowing whether `TRAVIS_COOKBOOKS_EDGE_BRANCH` is set or not, it's hard to tell whether `edge` will get me master, or just a slightly more updated manually picked revision? (For example on the travis-cookbooks repo I see there is a `trusty-stable` branch - is that what is used for `edge`?)

There's also another gotcha worth mentioning: the `group` property only takes effect for GCE (`sudo: required`) jobs, since the docker infra only has the stable image set, which comes from:
https://github.com/travis-infrastructure/terraform-config/blob/7a1c3af1b66a6a1305332463be01f53eee97b2cc/aws-production-2/main.tf#L30

**Comment by edmorley** [comment]
So it looks like `group: edge` does indeed map to travis-cookbooks and packer-templates master branch, but only if the builds are passing, and only if the necessary files were modified in packer-templates to trigger a new build. (The builds were broken for a few weeks recently, which explains why the updated docker versions were not being seen in the `edge` images.)

**Comment by tooomm** [comment]
I'm pretty sure that isn't documented yet?
