### ISSUE TITLE
Quote version numbers in yaml 

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#1540]
As discussed in #1537 we need to quote version strings in yaml:

In YAML, - 7.10 would evaluate to version 7.1, and not 7.10.This affects *lots* of pages, but starting with the language pages would be a good idea.

**Comment by polyzen** [comment]
Perhaps single quotes should be enforced as versions do not require ["[the use of] escapings to represent ASCII and Unicode characters"](www.yaml.org/YAML_for_ruby.html#double-quoted_strings) (AFAIK).
