### ISSUE TITLE
Add Xcode build numbers

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#1548]
A suggestion from @naan:

> Also, it would be nice if this page contains not only Xcode public version, but also a build number:
>
> https://docs.travis-ci.com/user/reference/osx/

**Comment by cotsog** [comment]
Please keep it open as I believe it's easy to do. Just need to take the time to do it.

**Comment by plaindocs** [comment]
Hey @cotsog 

What build numbers are we talking about here? And where do they come from?

**Comment by plaindocs** [comment]
Hey @cotsog did we get around to doing this?

**Comment by cotsog** [comment]
@plaindocs Sorry for the delay!

Kicked my a** this morning: https://github.com/travis-ci/docs-travis-ci-com/pull/1965 😄
