### ISSUE TITLE
BluemixCloudFoundry is in docs, but not in gem

### ISSUE THREAD

**Issue by lornajane** [travis-ci/docs-travis-ci-com#1553]
I'm reading https://docs.travis-ci.com/user/deployment/bluemixcloudfoundry/ since I would like to deploy to Bluemix.  However I can't find any reference to this setup in the gem code itself and when I follow the instructions, I get an error:

```
$ travis setup bluemixcloudfoundry
unknown service bluemixcloudfoundry
```
I have v1.8.8 of the gem, am I doing something wrong?  If not should I just remove the docs?

**Comment by plaindocs** [comment]
Hey @lornajane 

Congratulations, you have found a glitch in the matrix. https://github.com/travis-ci/travis.rb/pull/475 I'll try to get that merged. 

In the meantime, configuring it manually instead of using `travis setup`  should work as planned.
