### ISSUE TITLE
Surefire tests not running on Travis CI 

### ISSUE THREAD

**Issue by ellenchristine** [travis-ci/docs-travis-ci-com#1566]
Here is the link to my most recent build: https://travis-ci.org/simplifycom/gateway-java-sample-code/builds/307987168

In the logs, you can see it isn't picking up the tests. 
![screen shot 2017-11-27 at 10 59 22 am](https://user-images.githubusercontent.com/796859/33278723-0dbce8c4-d362-11e7-8176-31b6a156034e.png)

I am using the default command `mvn test -B`. When I run that same command locally, the tests get picked up:

![screen shot 2017-11-27 at 11 00 27 am](https://user-images.githubusercontent.com/796859/33278969-a4b9a4ec-d362-11e7-8ebf-13bab16eb026.png)

Is there some configuration I need to add to the Travis YAML to get this to work?

**Comment by BanzaiMan** [comment]
This is not a docs issue. Please use travis-ci/travis-ci instead.
