### ISSUE TITLE
Categorize Build Environment updates by OS & reference / link in docs by infra

### ISSUE THREAD

**Issue by Lyoness** [travis-ci/docs-travis-ci-com#1576]
From @MariadeAnton 

As for referencing the build env updates in the docs - I'm thinking normally we do build env updates per OS, right? Like macOS vs Linux - so maybe we can have [categories in the build-env updates page](https://docs.travis-ci.com/user/build-environment-updates/) and show data per OS. So that it's a linkeable reference in the infra reference pages

Precise CI Environment Reference
Trusty CI Environment - 
[OS X CI Environment Reference]( https://docs.travis-ci.com/user/reference/osx/#Compilers-and-Build-toolchain)

**Comment by MariadeAnton** [comment]
Took a first stake at this at https://github.com/travis-ci/docs-travis-ci-com/pull/1577

Next up would be linking the specific updates in the infra reference pages?

**Comment by Lyoness** [comment]
Awesome!  
Let's sow the seeds for a separate Android column too for a future PR...

**Comment by MariadeAnton** [comment]
I'd say this is ready, once we have Android specific environment updates, give me a ping and we can add the category as we create the docs and the env section :) 

Thanks much!
