### ISSUE TITLE
Cache dynamic data?

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#1596]
We've now got multiple scripts that get data from various sources and generate yaml which we use in the build.

Any thoughts on some kinda generic caching mechanism we can use so that the build just falls back on the previous data instead of stopping the build?

**Comment by BanzaiMan** [comment]
This is a good idea, but due to the diverse nature of the tasks involved, adding recovery logic and proper caching mechanism to them will require some work. How often do the builds fail due to the failure to fetch external data?
