### ISSUE TITLE
Build Stages Share files example only works for Linux builds

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1599]
This example (https://docs.travis-ci.com/user/build-stages/share-files-s3/) shows how to configure your path and download the awscli to use this tool later in the build. However, the specified path there might not work for the macOS environment.

For example, for a build in Xcode9, using `pip install --user awscli` is installing the package in:

```
travis$ pip show awscli
Name: awscli
Version: 1.14.9
Summary: Universal Command Line Environment for AWS.
Home-page: http://aws.amazon.com/cli/
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /Users/travis/Library/Python/2.7/lib/python/site-packages
Requires: s3transfer, PyYAML, rsa, botocore, docutils, colorama
```

which is not in the $PATH for `ruby` , for example:

```
echo $PATH
/Users/travis/.rvm/gems/ruby-2.4.2/bin:/Users/travis/.rvm/gems/ruby-2.4.2@global/bin:/Users/travis/.rvm/rubies/ruby-2.4.2/bin:/Users/travis/.nvm/versions/node/v6.11.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/travis/.rvm/gems/ruby-2.4.2/bin:/Users/travis/.rvm/gems/ruby-2.4.2@global/bin:/Users/travis/.rvm/rubies/ruby-2.4.2/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/Users/travis/.debug:/Users/travis/.rvm/bin
```

In general, this could vary, so we should add at least a comment or other suggestions for this :-)

**Comment by MariadeAnton** [comment]
Thank you so much, @iriberri - pip is definitely not one of they by-default languages available in our macOS infra. 

Do you have another package in mind so that we can replace the example or create a specific one for macOS?
