### ISSUE TITLE
Python setup.py install failing

### ISSUE THREAD

**Issue by romanvm** [travis-ci/docs-travis-ci-com#1609]
I maintain a Python package `django-tinymce4-lite` and use Travis for testing and deploying the package to PyPI. However, since some time all builds started to fail due to `python setup.py build` or `python setup.py bdist_wheel` operations cannot be completed because copying files fails at some point, and it looks like it fails at different moments in different builds. Again, it is not a script failure but some filesystem operation failure.
Example of a failing build: https://travis-ci.org/romanvm/django-tinymce4-lite/builds/317940789

This build succeeded (I commented a problematic line) but creating a wheel package failed for the same reason: https://travis-ci.org/romanvm/django-tinymce4-lite/jobs/317944766

**Comment by BanzaiMan** [comment]
Sorry, but this is not a documentation issue. General Travis CI issues should go to https://github.com/travis-ci/travis-ci/issues. Thanks.
