### ISSUE TITLE
Improve the "Share files via S3" build stages example

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#1612]
https://docs.travis-ci.com/user/build-stages/share-files-s3/

Here are some suggestions [from Jim](https://secure.helpscout.net/conversation/486673969/64089?folderId=504986):

> Also, the example (https://docs.travis-ci.com/user/build-stages/share-files-s3/) seems a bit oversimplified:
>- The S3 directory name should incorporate the build number and repository name so that each build is independent.
>
>- There should be a mechanism to delete the directories used for old builds. Perhaps something could delete them automatically after some number of days.
>
> Perhaps the example could be updated to address or at least mention these 2 issues?

**Comment by plaindocs** [comment]
Thanks @cotsog 

The second point is not a doc issue though - unless we want to mention that so people can implement it.

**Comment by BanzaiMan** [comment]
@plaindocs The second point can be achieved by removing the intermediate files at the end of the build. See https://github.com/travis-ci/docs-travis-ci-com/pull/1634/commits/41d012a16f601eab897c125e6cbe5e90b4a028c2.
