### ISSUE TITLE
In "Build Environment Overview", describe how to tell what environment was used

### ISSUE THREAD

**Issue by mitchhentges** [travis-ci/docs-travis-ci-com#1628]
I want to know by looking at my Travis build whether I'm using a Linux container or VM. I can heuristically tell by looking at the `startup: ` line, but maybe there's some more explicit information in the log.

It would be :100" if the "Build Environment Overview" documentation described how to tell which OS environment was used based on the build log

**Comment by plaindocs** [comment]
Closed by #1648
