### ISSUE TITLE
ssh-known-hosts seems to encourage poor security practices

### ISSUE THREAD

**Issue by stefangotz** [travis-ci/docs-travis-ci-com#1649]
The ssh-known-hosts configuration option documented in https://github.com/travis-ci/docs-travis-ci-com/blob/master/user/ssh-known-hosts.md seems to encourage poor security practices. It may make Travis builds susceptible to man-in-the-middle attacks.

If I understand the effect of the ssh-known-hosts option correctly, it makes a Travis build instance retrieve an SSH server's key afresh every time the build instance starts. This would more or less defeat the purpose of the SSH known hosts feature.

The point of SSH's known hosts feature is to pin down the cryptographic identity of a server so that a man in the middle attacker cannot impersonate the server. On a regular computer, the standard approach of simply accepting and storing the server key on the first connection and then checking it on every subsequent connection makes sense because the client remembers and checks the server key for a long time. On short lived systems, such as Travis build instances, this approach makes less sense because almost every connection is the 'first' connection and therefore the build instance accepts any key the server (or an impersonator) presents for every single build.

Yes, of course such attacks are extremely unlikely. Still, how about updating the documentation to help users to make an informed decision about this? Would it be worth mentioning that there is a security vs. convenience trade-off here?

For short lived systems, the safer option is to obtain the server key ahead of time and to add that fixed key to the .known_hosts file of the Travis build instance. Basically, one could run ssh-keyscan on a local computer against the SSH server or git repo server of interest, get the new entries for that server from the local .known_hosts file, and configure Travis to add those entries to the .known_hosts file of each Travis build instance. That would pin down the server's cryptographic identity as SSH normally intends it to be done. And there might be other, more convenient alternatives to achieve the same effect.

**Comment by BanzaiMan** [comment]
We run `ssh-keyscan` to add the SSH host key. https://github.com/travis-ci/travis-build/blob/d08e1022dca73e813fc0ed8c73482b91005c9f82/lib/travis/build/addons/ssh_known_hosts.rb#L48 Do you have a better idea?

**Comment by BanzaiMan** [comment]
We also welcome your documentation PR if you have ideas for improvement. Thanks.

**Comment by stefangotz** [comment]
> We run ssh-keyscan to add the SSH host key. Do you have a better idea?

The security issue is not so much ssh-keyscan itself, but the fact that the server key is retrieved for every single new build.

On a regular computer, ssh-keyscan would be used once to store a server's key in known_hosts for a long time. From that point onward (so potentially for many years and lots of connections), every ssh/git/... access from that computer to the server would check whether the server still presents the same key from the known_hosts file or not. If the key is the same, everything is ok and the connection is established. If the key is different, either the server key did actually change or a man-in-the-middle attacker is trying to impersonate the server (e.g., to provide different git repo contents than the real server). In both cases, ssh refuses the connection to be on the safe side and to let the user figure out how to handle the situation.

The security of this mechanism relies on the server key to live in known_hosts for a long time and be used for many connections. When using ssh-keyscan in Travis build instances however, known_hosts is basically rebuilt from scratch for every single build. Also, it's only used for the few connections made during the build run. So if there is a man-in-the-middle attacker, ssh-keyscan obtains the attacker's key when the build starts and any ssh-based git/... connection to the server during the build then happily accepts the attacker's key and talks to the attacker's impersonated server.

Do I have a better idea? Let's see:

- **Who cares?** Probably only the most security conscious Travis users care about this issue. Still, the documentation should, in my opinion, inform also the average Travis user that the ssh-known-hosts option is (at least in its current form) a convenience feature which has security implications around man-in-the-middle attacks. I'll provide a PR for a documentation update.

- **What can users do?** Security conscious users can replace the ssh-known-hosts option with the following approach:
    1. First, obtain the server key outside of Travis, e.g., on their local computer
    2. Then, add setup code to their Travis configuration that copies that server key into the known_hosts file of each Travis build instance
I'll provide a PR for a documentation update.

- **What can Travis do?** Travis could change the implementation of the ssh-known-hosts option so that build instances do not obtain the server keys from the servers themselves every time they start up, but rather from some trusted sources that stores server keys for longer periods of time. That way, a man-in-the-middle attack could again be detected by a build instance because the key it obtained from the trusted source would differ from the key that the (malicious) server presented to it. The trusted source could be some form of key store/cache in Travis's internal infrastructure. That would require some serious design work to be both secure and scalable, though.

**Comment by BanzaiMan** [comment]
I think the addon can be improved to take the type and the ssh host key.

**Comment by stefangotz** [comment]
Yeah, that would be a really easy way of dealing with this issue! Nice!

**Comment by bogdanap** [comment]
Closed by https://github.com/travis-ci/docs-travis-ci-com/pull/1673
