### ISSUE TITLE
conflicting statements on debug mode

### ISSUE THREAD

**Issue by thurt** [travis-ci/docs-travis-ci-com#1664]
at this point in time, i have found conflicting information in the travis docs. there is a section here, https://docs.travis-ci.com/user/running-build-in-debug-mode/#Restarting-a-job-in-debug-mode-via-API, that says you can run in debug mode with public repos and it has example code showing domain `travis-ci.org`--however I am not able to get this example command to work. in contrast, the API documentation says it is actually NOT possible to invoke debug mode for `travis-ci.org` domains https://developer.travis-ci.com/resource/job#debug

**Comment by BanzaiMan** [comment]
https://developer.travis-ci.com/resource/job#debug is wrong.

**Comment by BanzaiMan** [comment]
If you are not getting the debug to start, then you might be invoking it wrong (URL, token, etc.) or the repository does not have the feature turned on.

**Comment by BanzaiMan** [comment]
https://github.com/travis-pro/developer/pull/50 resolves the inconsistency.

**Comment by thurt** [comment]
thank you! 

the information at https://developer.travis-ci.com/resource/job#debug has been updated
