### ISSUE TITLE
Document the effect of using `set -e` in .travis.yml or in scripts

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#1672]
Using `set -e` in .travis.yml or in scripts can cause weird behaviour on Travis CI. It would be nice to give visibility on this in our docs.

Thanks to @maelvalais for the suggestion!

**Comment by BanzaiMan** [comment]
This is discussed in https://docs.travis-ci.com/user/customizing-the-build/#Implementing-Complex-Build-Steps

> Note the `set -ev` at the top. The `-e` flag causes the script to exit as soon as one command returns a non-zero exit code. This can be handy if you want whatever script you have to exit early. It also helps in complex installation scripts where one failed command wouldn’t otherwise cause the installation to fail.

If you have ideas on where to put this for more prominence, I'm happy to discuss that with you.

**Comment by fcastilloec** [comment]
What about using `set -e` on `.travis.yml` itself, not on scripts used by Travis?
It seems that there's no problem when doing this on Linux, but OSX shows errors that shouldn't, specifically with `rvm`.
You can see [this comment](https://github.com/travis-ci/travis-ci/issues/6307#issuecomment-355956554) that mentions the exact problem I'm running into.

**Comment by maelvalais** [comment]
`set -e` does not seem to cause problems in scripts called from `.travis.yml`. However, inside `.travis.yml` itself, it may **break things** (unless we set `set +e` shortly after) as some internal travis (rvm-related) commands often fail causing the build to unexpectedly stop with no clear error (on osx mainly).

It would be good to mention that using `set -e` inside `.travis.yml` itself may break things 👍

**Comment by fcastilloec** [comment]
@maelvalais actually, using `set +e` immediately after a command is run under `set -e` on OSX also causes problems with `rvm`, I'm not sure why. This is not the case with Linux, where `set -e` and `set +e` work without problems inside `.travis.yml` itself.

**Comment by BanzaiMan** [comment]
RVM is not the only thing that can break when `set errexit` is set in `.travis.yml`. Just don't do it.

**Comment by maelvalais** [comment]
then maybe we could add something like

    Don't use 'set -e' in .travis.yml

in the docs? If possible using a warning sign or something 😁
