### ISSUE TITLE
"speeding up the build" still refers to VMs with 1.5 virtual cores

### ISSUE THREAD

**Issue by AliSoftware** [travis-ci/docs-travis-ci-com#168]
In [the paragraph "Parallelizing-your-build-on-one-VM"](http://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-build-on-one-VM), there is still mention about "Travis CI VMs run on 1.5 virtual cores"

As mentioned in the recent [blog post about the new container-based infrastructure](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) this is not true anymore.

_(Sorry for not making a PR, I'm not on my Mac right now)_

**Comment by MariadeAnton** [comment]
Hey @AliSoftware, thanks for reporting this. 

I think replacing it to ~ 2 virtual cores should be okay at the moment. At least, until we end up this migration: https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future in which 2 cores would be the default for all infras: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

@plaindocs, what do you think?

**Comment by plaindocs** [comment]
We can change this to ~ 2 for now.

When we refactor how we talk about Environments this sort of thing should be more clear.
