### ISSUE TITLE
correct some documentation

### ISSUE THREAD

**Issue by DanGrayson** [travis-ci/docs-travis-ci-com#1724]
The file `user/common-build-problems.md` says "If you expect the command to take more than 20 minutes, prefix `travis_wait` with a greater number", but then the example just following shows that the 20 is not used as a prefix, but instead is used as an additional argument after `travis_wait`.

**Comment by plaindocs** [comment]
Hi @DanGrayson thanks for pointing this out.

I think what it is suggesting is prefixing the command you want to take longer with `travis wait 35`. 

But it could definitely be more clear. Would you like to suggest some better wording?

**Comment by DanGrayson** [comment]
How about this?:

If you expect the command to take more than 20 minutes, prefix the command with `travis_wait n`, where `n` is the number of minutes to allow.
