### ISSUE TITLE
ccmenu (et al) feed for closed source projects by account not working

### ISSUE THREAD

**Issue by maxheld83** [travis-ci/docs-travis-ci-com#1753]
this part here:

> For closed source projects use `https://api.travis-ci.com/repos/<owner>.xml?token=<token>`

does not appear to work (at least with CCMenu on macOS).

I consistently get a "Cannot determine server type" error.

All the other ways documented work; you can add each closed source project, one at a time (which is cumbersome), but not in batch.

<img width="720" alt="ccmenu" src="https://user-images.githubusercontent.com/5372770/37400888-a77361a0-2786-11e8-860f-bad5b07ff8ac.png">

**Comment by plaindocs** [comment]
Hi @maxheld83 

Probably best to raise this with the https://github.com/erikdoe/ccmenu/issues menu folks! Cheers

**Comment by BanzaiMan** [comment]
This is not a docs issue, since the problem appears to exist with the API. Please open an issue at https://github.com/travis-ci/travis-ci/issues. Thank you.
