### ISSUE TITLE
Uploading Build Artefacts - Link 404

### ISSUE THREAD

**Issue by eddiejaoude** [travis-ci/docs-travis-ci-com#177]
This link:

http://docs.travis-ci.com/user/uploading-artifacts/ 

![screenshot 2015-01-06 06 43 00](https://cloud.githubusercontent.com/assets/624760/5625263/603050ca-956f-11e4-9516-172e34d5e822.png)

Returns a `404`:

![screenshot 2015-01-06 06 42 24](https://cloud.githubusercontent.com/assets/624760/5625269/6be9a362-956f-11e4-9957-cdbd2a567c02.png)

**Comment by henrikhodne** [comment]
Good catch, thanks for reporting it!
