### ISSUE TITLE
  sudo: enabled or   sudo: required

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/docs-travis-ci-com#1792]
https://github.com/travis-ci/docs-travis-ci-com/pull/1127 by @plaindocs introduced `sudo: enabled` into `user/getting-started`, while everywhere else it is `sudo: required`.

Which is correct/preferred?
Consistency would be good.

**Comment by BanzaiMan** [comment]
There is no single "correct" value, actually. Any value that evaluates to something other than `false` (in YAML) is accepted. This includes `true`, `""`, `required`, `enabled`.

Still, consistency is desirable.

**Comment by BanzaiMan** [comment]
```
Searching 187 files for "sudo: (?!(required|false))" (regex, case sensitive)

/Users/asari/Development/src/travis-ci/docs-travis-ci-com/user/getting-started.md:
  103  
  104    ```yaml
  105:   sudo: enabled
  106    ```
  107    {: data-file=".travis.yml"}

/Users/asari/Development/src/travis-ci/docs-travis-ci-com/user/installing-dependencies.md:
  140  
  141  ```yaml
  142: sudo: true
  143  dist: trusty
  144  

/Users/asari/Development/src/travis-ci/docs-travis-ci-com/user/build-stages/share-docker-image.md:
   13  
   14  ```yaml
   15: sudo: true
   16  dist: trusty
   17  

/Users/asari/Development/src/travis-ci/docs-travis-ci-com/user/reference/overview.md:
   78  
   79    - `services: docker`
   80:   - `sudo: required` or `sudo: true`
   81    - *any* other `sudo` command in your build script
   82    - *any* other `docker` command in your build script

4 matches across 4 files
```

**Comment by plaindocs** [comment]
The point stands that we should be consistent.

We should also distinguish between yaml and natural language. In the environment reference we talk about sudo enabled https://docs.travis-ci.com/user/reference/overview/#Sudo-enabled 

So probably we should standardize on `sudo: enabled` also. Because calling `sudo: required` "Sudo Enabled" feels odd to me.

@BanzaiMan can  you think of any reason not to?

**Comment by BanzaiMan** [comment]
Historically speaking it was introduced as `sudo: required`. So, I am leaning towards that. Having a new value without real benefit will lead to confusion for existing users and their configuration: "When did this change? Do we need to change it now?" I understand the weirdness of it, but I think it is something that we can overlook.

**Comment by plaindocs** [comment]
Sounds good to me. I'll just file this under human error (mine) and revert to `Required` everywhere.

**Comment by Mizux** [comment]
Please note that `sudo: false` is now deprecated
see  #2121 for details...

**Comment by Mizux** [comment]
since `sudo: false` become obsolete (see #2121) maybe you won't care of this ?

**Comment by plaindocs** [comment]
Hey @Mizux yeah, I think we can close this.

There is some work over in #2095 that removes most of those old references.
