### ISSUE TITLE
Docs should specify Travis CI config's YAML conformance details

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [travis-ci/docs-travis-ci-com#1831]
Refer https://github.com/travis-ci/travis-ci/issues/9600 for more info.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/9600#issuecomment-388053230

> Thanks for the information. I've tracked this down to Ruby's reliance on libYAML, which, at the moment, only supports YAML 1.1. 
> 
> See https://github.com/ruby/psych/issues/253 and https://github.com/yaml/libyaml/issues/20.
