### ISSUE TITLE
Hostname convention has changed for osx vms

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/docs-travis-ci-com#1832]
Docs say `hostname` should contain `jupiter` for `osx` jobs, but that's no longer the case, it's now `wjb`, e.g.:

```
hostname: 3bac9142-e7c5-461e-8183-3dce1e16987f@5634.wjb-2
```

https://travis-ci.org/svenfuchs/test/jobs/377343187#L2

**Comment by Lyoness** [comment]
Ok Sven, will update this.
