### ISSUE TITLE
How to fix api docs

### ISSUE THREAD

**Issue by khs1994** [travis-ci/docs-travis-ci-com#1849]
* https://developer.travis-ci.com/resource/cron#create

The last lines are repeated

![default](https://user-images.githubusercontent.com/16733187/40404945-fd55b59a-5e8c-11e8-8cd1-d1aff67dae8e.PNG)

**Comment by plaindocs** [comment]
Hi @khs1994  

Thanks for raising that. Seems to be in the API and not the API docs. We're tracking that here https://github.com/travis-ci/travis-api/pull/776
