### ISSUE TITLE
json: cannot unmarshal string into Go struct field RequestResponse.branch_name ...

### ISSUE THREAD

**Issue by HaraldNordgren** [travis-ci/docs-travis-ci-com#1858]
I'm getting issues from the API: "json: cannot unmarshal string into Go struct field RequestResponse.branch_name ...".

It started happening today.

This page https://developer.travis-ci.com/resource/requests#Requests does state that 'branch_name' will be a string.

But was this recently changed?

**Comment by BanzaiMan** [comment]
Sorry to hear about the issue. This seems like a bug, not a documentation issue, so would you open a new issue in https://github.com/travis-ci/travis-ci/issues instead?

**Comment by carlad** [comment]
@HaraldNordgren Would it be possible to post an example of the request you're making, including headers. We applied a [patch](https://github.com/travis-ci/travis-api/pull/766) to api last week which we believe addressed this issue, and are currently unable to reproduce the issue. It would be helpful to have more info about your actual request.

**Comment by HaraldNordgren** [comment]
I seem likely that https://github.com/travis-ci/travis-api/pull/766 is the root cause here.

**Comment by BanzaiMan** [comment]
Further discussion in https://github.com/travis-ci/travis-ci/issues/9672, please.

**Comment by carlad** [comment]
@HaraldNordgren Would it be possible to post an example of the request you're making, including headers.
