### ISSUE TITLE
travis_retry documentation is contradictory

### ISSUE THREAD

**Issue by jmerle** [travis-ci/docs-travis-ci-com#1861]
In the `travis_retry` [documentation](https://docs.travis-ci.com/user/common-build-problems/#travis_retry), the following example is made:

```yml
install: travis_retry pip install myawesomepackage
```

But two lines below that, you'll see the following:

> Note that `travis_retry` only works within the `script` step. It will not work in other steps, like `deploy`.

The example, however, uses the `install` step, so either the example or the line above is wrong.  Can someone shine some light on whether it's really limited to the `script` step?

The line above seems to be added in #1688.

**Comment by plaindocs** [comment]
Thanks for raising that @jmerle - I've fixed it in PR #1863.

You can use it in other steps, but not in deploy.
