### ISSUE TITLE
[Firefox][Bug] Search does not work

### ISSUE THREAD

**Issue by mjwsteenbergen** [travis-ci/docs-travis-ci-com#1880]
Expected:
![image](https://user-images.githubusercontent.com/5946409/41150902-72a05c2c-6b0f-11e8-8bd8-14e5a5135b73.png)

Actual:
![image](https://user-images.githubusercontent.com/5946409/41150865-5dedf7bc-6b0f-11e8-97c9-0c144bfb599a.png)

This is most likely caused by SwiftType, as it does not want to load:

`Loading failed for the <script> with source “https://swiftype.com/embed.js”.`

Have a great day!

**Comment by plaindocs** [comment]
Hi @mjwsteenbergen 

Thanks for point this out. Are you using any add blockers or javascript blockers by any chance?
