### ISSUE TITLE
Document travis_terminate

### ISSUE THREAD

**Issue by acnagy** [travis-ci/docs-travis-ci-com#1899]
In working on the Conditions docs - https://github.com/travis-ci/docs-travis-ci-com/pull/1884, we realized `travis_terminate` ([`travis-build` code here](https://github.com/travis-ci/travis-build/blob/4041ba116ddb3bdfd66ab8acbb7094dee28d6797/lib/travis/build/templates/header.sh#L191)) is not documented. Opening this issue to split this out of that discussion.

**Comment by tooomm** [comment]
Can somebody link to the documentation, please? (if this is done already)

**Comment by tooomm** [comment]
https://github.com/travis-ci/docs-travis-ci-com/issues/1899#issuecomment-422650014
