### ISSUE TITLE
PG::ConnectionBad: fe_sendauth: no password supplied when using postgresql 10

### ISSUE THREAD

**Issue by znz** [travis-ci/docs-travis-ci-com#1962]
I switched to PostgreSQL 10 and PostGIS 2.4 (same versions of https://hub.docker.com/r/mdillon/postgis/ ), but `rails db:setup` failed.
What is password for PostgreSQL installed from APT repository?

https://travis-ci.org/znz/memo-app-r/builds/410848230
```
$ bundle exec rails db:setup
fe_sendauth: no password supplied
Couldn't create database for {"adapter"=>"postgis", "encoding"=>"unicode", "pool"=>5, "database"=>"travis_ci_test", "username"=>"postgres", "port"=>5433, "host"=>"localhost"}
rails aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
```

**Comment by znz** [comment]
https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version does not say nothing about password.

**Comment by joepvd** [comment]
Hi @znz! We see that you are attempting to run postgres from tha apt repositories, which has not received a "treatment" from our side.

I think the following recipe should get you in the right direction: https://github.com/travis-ci/travis-ci/issues/9624#issuecomment-389537036

PostgreSQL 10 will be supported on the Xenial image (which has not yet been released, but is available for use. You could try with the following configuration:

```yaml
sudo: required
dist: xenial
addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10-postgis-2.4
```

Please let us know if that would not work out.
