### ISSUE TITLE
[julialang] Information outdated

### ISSUE THREAD

**Issue by thofma** [travis-ci/docs-travis-ci-com#1979]
The information at https://docs.travis-ci.com/user/languages/julia/ is outdated. The default script does not work with julia 1.0.
@tkelman @ninjin @staticfloat @simonbyrne

**Comment by simonbyrne** [comment]
See https://github.com/travis-ci/docs-travis-ci-com/pull/1970

**Comment by thofma** [comment]
Sorry, did not see the PR.
