### ISSUE TITLE
Arbitrary-directories anchor links don't go anywhere

### ISSUE THREAD

**Issue by bombledmonk** [travis-ci/docs-travis-ci-com#1983]
There seems to be many anchor links in the [caching docs](https://docs.travis-ci.com/user/caching/#configuration) pointing to #Arbitrary-directories that don't go anywhere. It seems this reference may have been removed?

![image](https://user-images.githubusercontent.com/4141691/44286617-55b6b500-a22f-11e8-9efa-0b3aa92cbec7.png)

**Comment by plaindocs** [comment]
Thanks for pointing this out.
