### ISSUE TITLE
Inaccurate documentation about OS X and JDK versions 

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1997]
Moved from: https://github.com/travis-ci/travis-ci/issues/10022

Reported by @mernst on August 23rd, 2017
----

The documentation [JDK and OS X](https://docs.travis-ci.com/user/reference/osx/#jdk-and-os-x) says that the default OS X image `xcode9.4` uses JDK 1.8.0_112-b16.  However, [this log](https://travis-ci.org/codespecs/test-daikon-staging-macosx/builds/419320059) uses the default image and [xcode 9.4.1](https://travis-ci.org/codespecs/test-daikon-staging-macosx/builds/419320059#L16) but [JDK 10](https://travis-ci.org/codespecs/test-daikon-staging-macosx/builds/419320059#L79).
**Request**: Could you please update the documentation, or change the xcode9.4 image?

I tried using the
```
jdk:
  - openjdk8
```
block in my `.travis.yml`, but [the build](https://travis-ci.org/codespecs/test-daikon-staging-macosx/builds/419420579) still used JDK 10.
**Request**:  If this doesn't work on OS X, please update [the documentation](https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks) to say that explicitly.

Finally, I put
```
osx_image: xcode9.3
```
in my `.travis.yml` file, and this gave me JDK 8.

**Comment by plaindocs** [comment]
Thanks @iriberri . 
@cotsog 

What do you folks think is the best thing to do here?

**Comment by mjm** [comment]
This was a mistake in the docs, which I saw in another issue (https://github.com/travis-ci/docs-travis-ci-com/issues/2022) and I've just corrected: https://github.com/travis-ci/docs-travis-ci-com/commit/11ccc5d7481b8be4eceb80d3b062a2eeeec50828

xcode9.4 has JDK 10, earlier images have JDK 8 (AFAIK).
