### ISSUE TITLE
broken link on /user/deployment/firebase/

### ISSUE THREAD

**Issue by kaycebasques** [travis-ci/docs-travis-ci-com#2009]
[Generating your Firebase token](https://docs.travis-ci.com/user/deployment/firebase/#generating-your-firebase-token) links here: https://github.com/travis-ci/travis-ci/issues/7869

But that page seems 404?

**Comment by plaindocs** [comment]
Hi @kaycebasques 

That link resolves ok to me, sounds like it might have been an intermittent network issue. Please reopen if you still cannot access that GitHub issue.
