### ISSUE TITLE
enable repositories via API 

### ISSUE THREAD

**Issue by jonschlinkert** [travis-ci/docs-travis-ci-com#201]
Is there a way to do this? I might be looking for the wrong terminology, but I can't find anything in the API docs about how to enable a project with Travis. I'd really like to create a node.js CLI to do it if it's possible.

**Comment by joshk** [comment]
This is already possible. https://github.com/travis-ci/travis.rb#enable

Also, could you please open issues on the travis-ci/travis-ci repo in the future.

Thanks, Josh
