### ISSUE TITLE
JDK versions are wrong for macOS builds

### ISSUE THREAD

**Issue by Azhrei** [travis-ci/docs-travis-ci-com#2022]
The documentation here https://github.com/travis-ci/docs-travis-ci-com/edit/master/user/reference/osx.md says that the `xcode9.4` image results in JDK8, but I just ran a build and it used build **10.0.1+10**.  I was going to fix this in the docs, but they use some kind of external substitution, so I'm stuck.

**Comment by mjm** [comment]
Whoops! If you still want to open a PR, the substitution is pulling data from https://github.com/travis-ci/docs-travis-ci-com/blob/master/_data/xcodes.yml. If you update it there, it should be changed in the page.

**Comment by mjm** [comment]
I went ahead and fixed this: https://github.com/travis-ci/docs-travis-ci-com/commit/11ccc5d7481b8be4eceb80d3b062a2eeeec50828

It should be live on the site soon. Thanks for bringing this to our attention!
