### ISSUE TITLE
I want to translate to Transitional Chinese

### ISSUE THREAD

**Issue by qas612820704** [travis-ci/docs-travis-ci-com#2057]
Hi,

I would like to learn Travis CI through this docs.

And translating into Transitional Chinese as well.

Is there some specifications do I have to comply with? or any tips?

**Comment by plaindocs** [comment]
Hi @qas612820704 

Thanks for your interest in translating the Travis CI docs. Translating such a significant body of text is a lot of work, and the translation will quickly fall out of date if it is unmaintained. 

What do you think about following our [tutorial](https://docs.travis-ci.com/user/tutorial/) and writing a blog post about that instead, optionally translating core concepts that you encounter?

If you do, let us know when it is live and we'll take a look and share it.
