### ISSUE TITLE
Incorrect YAML String Syntax Highlighting

### ISSUE THREAD

**Issue by Chris-Johnston** [travis-ci/docs-travis-ci-com#2089]
This is an issue with the syntax highlighting library (`prism.js`) that this website is using, which should be updated when it's issue is resolved.

<img src="https://user-images.githubusercontent.com/16418643/47633656-ee10c600-db0b-11e8-9b11-fcb552b3964d.png" width="300px" />

The YAML formatting [on this page](https://docs.travis-ci.com/user/languages/python) is currently broken, the last string under `python:` does not correctly get highlighted as a string. The source appears to be correctly formatted.

Looking at `prism.js`, when I update it to the latest version (1.15.0), the issue seems to have gotten worse:

<img src="https://user-images.githubusercontent.com/16418643/47634180-c15dae00-db0d-11e8-8313-3fd808f0838d.png" width="300px" />

All strings with comments on the same line don't get formatted correctly.

I've opened PrismJS/prism#1601 for this new issue. When this issue gets closed, the file `assets/javascripts/prism.js` should be updated to the latest version.

**Comment by BanzaiMan** [comment]
This feels rather strange to me. The coloring is certainly inconsistent, but it seems to go beyond the commented lines. Namely, `"2.6"` is a string and colored light green, but other things, such as `pip install …` and `pytest` in the example, are also strings but colored black.

**Comment by plaindocs** [comment]
Thanks for reporting @Chris-Johnston 
@BanzaiMan looks like the YAML colouring is different for quoted strings?
