### ISSUE TITLE
Add Documentation About Case Sensitivity

### ISSUE THREAD

**Issue by sinthetix** [travis-ci/docs-travis-ci-com#209]
File system on Linux worker is case sensitive and thus import/file system links need to match the case or they won't work.

This could betray users' expectations if they use machines with case insensitive file systems.

**Comment by BanzaiMan** [comment]
Note: this is documented in https://github.com/travis-ci/docs-travis-ci-com/blob/f07006f2b1ff8431a5f6491be5f7ff1ae49cbbb9/user/multi-os.md#L59, but it can be more searchable in relevant places.

**Comment by MariadeAnton** [comment]
I think we could link this as a FAQ, @plaindocs - thoughts?
