### ISSUE TITLE
user/uploading-artifacts.md doesn't describe how artifacts are versioned

### ISSUE THREAD

**Issue by davidillsley** [travis-ci/docs-travis-ci-com#211]
I'm trying to work out how to manage artifacts, and while S3 upload seems attractive, I'm unclear from the documentation if builds overwrite previous build artifacts, if they are added in separate folders (with some kind of build/date based naming?), or something else...

A simple couple of sentences in this doc would save me time and effort trying it out.

**Comment by Joshua-Anderson** [comment]
It will overwrite files by default, but you can change it to output to a folder that is programmitcally named folder so it doesn't .
