### ISSUE TITLE
Get an error on android and can't reach the log file

### ISSUE THREAD

**Issue by OfirKa** [travis-ci/docs-travis-ci-com#2116]
Hello,
I'm trying to run some instrumentation tests with Travis CI.
I am getting this error:

> Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
> Tests on test(AVD) - 7.0 failed: Instrumentation run failed due to 'Process crashed.'
> :core:connectedDebugAndroidTest FAILED
> * What went wrong:
> Execution failed for task ':core:connectedDebugAndroidTest'.
> > There were failing tests. See the report at: file:///home/travis/build/mobfox/MobFox-Android-SDK-Core/core/build/reports/androidTests/connected/index.html

I'm trying to understand why I am getting this error, and more than that, i'm trying to figure out how to reach the index.html file that is on your machine in order for me to test it.

Thanks!

**Comment by BanzaiMan** [comment]
Sorry to hear about the issue, but this is not a docs issue. Please use https://travis-ci.community.

Thanks.
