### ISSUE TITLE
Doc anchor has wrong case and leading slash

### ISSUE THREAD

**Issue by javabrett** [travis-ci/docs-travis-ci-com#2122]
I had a build timeout due to no output and got the standard message: https://github.com/travis-ci/worker/blob/a9bfe679aa5ec8b132a6cdc77b0eb53084619cfa/step_run_script.go#L156 including URL https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received .

The problems with this URL are:

1. `#Build-times...` should be `#build-times...` (lower-case).  Some browsers (Chrome and Firefox included) treat the IDs/anchors as case-sensitive (correctly).  See change https://github.com/travis-ci/docs-travis-ci-com/commit/b4e060909c15a0064e52a73bc6842602bea2c1ef#diff-dffe7ab2989d54b631c2933fe8002badR224 .
1. The `/` before `#` causes problems on Chrome and the anchor does not load.

I'd be happy to fix the case issue over in travis-ci/worker, but the slash issue seems more widespread?

**Comment by javabrett** [comment]
Commenting to un-stale the issue.

**Comment by plaindocs** [comment]
Hey @javabrett 

All of the anchors should be lower case in the docs. The link *in* worker must have slipped through the cracks, a PR to update it would be welcome. 

I'm not sure if the `/#` issue is present in the docs, or just in worker, but it should be findable and fixable with a regex. I'll take a look at that.

**Comment by plaindocs** [comment]
oooh. Not quite 1000 instances. 

https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received does work for me on Chrome, so I'm thinking it is the case issue only.

**Comment by javabrett** [comment]
This was fixed by https://github.com/travis-ci/worker/pull/581 .
