### ISSUE TITLE
Multiple Deployment Provider Ordering

### ISSUE THREAD

**Issue by clintonb** [travis-ci/docs-travis-ci-com#2143]
The documentation shows how to setup multiple deployment providers (https://docs.travis-ci.com/user/deployment/#deploying-to-multiple-providers); however, it does not go into any detail on ordering. Is deployment sequential, in the order defined in YAML, or is some other ordering used?

This detail is important to me because I want to push an image to Docker Hub, and use Elastic Beanstalk to pull and deploy it. This fails if, for example, the Elastic Beanstalk deploy runs before the image has been pushed.

**Comment by BanzaiMan** [comment]
Deployments are ordered and executed in order defined.

**Comment by clintonb** [comment]
@BanzaiMan I figured as much. Would you welcome a PR updating the docs to state that?

**Comment by BanzaiMan** [comment]
Of course!
