### ISSUE TITLE
Broken file type display in code blocks

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#2144]
In #1209 we added a file type display to the top right hand side code blocks with file types.

Somehow between commits 7fa88b921e2468c5d5eab246836c54250e286362 and 55731f04b16eb476b24a67bc4f30119eaaea8407 it started to display under the code block. AFAIK those commits do not affect any relevant files, ie CSS, template, etc. Also as AFAIK we're using prism from the GH repo, not fetching / updating it each time. 

* How it should look https://deploy-preview-2127--musing-lamport-7fb66c.netlify.com/user/tutorial/
  
  ![image](https://user-images.githubusercontent.com/3729517/49014855-bdab5e80-f181-11e8-8734-e9ae1dd0eb4a.png)

* How it looks now https://deploy-preview-2055--musing-lamport-7fb66c.netlify.com/user/tutorial/
  
  ![image](https://user-images.githubusercontent.com/3729517/49014880-d0259800-f181-11e8-9068-d67de09cd3b3.png)

This happened *before* the prism update in #2094.

I'm kinda lost.

**Comment by paulthegeek** [comment]
@plaindocs @MariadeAnton Merged, deployed, fixed 🎉
https://docs.travis-ci.com/user/tutorial/
