### ISSUE TITLE
"Clearing the cache" section says not possible via web interface

### ISSUE THREAD

**Issue by edmorley** [travis-ci/docs-travis-ci-com#215]
The current wording:
http://docs.travis-ci.com/user/caching/#Clearing-Caches

"Currently it is not possible to clear the cache via the web interface, but you can use our command line client to clear the cache:"

However this is now possible using:
``https://travis-ci.org/<org>/<project>/caches``

...which is accessible under the settings 'cog' icon on each project's page.

**Comment by edmorley** [comment]
Thanks! :-)

**Comment by BanzaiMan** [comment]
@edmorley Thanks for the report!
