### ISSUE TITLE
Add Support for how to run Google App Engine migrations

### ISSUE THREAD

**Issue by ZeroSoulEater** [travis-ci/docs-travis-ci-com#2173]
in my case, I try to deploy my rails project to the Google App Engine. I can deploy it but I can't figure a way out to run the migrations in the deployment process.

If I deploy it from my machine I have to run 
`bundle exec rake appengine:exec -- bundle exec rake db:migrate`

but if I do so in:

```
after_deploy:
  - bundle exec rake appengine:exec -- bundle exec rake db:migrate
```

I get the error: 
> You do not have permission to access app [eco-emissary-99515] (or it may not exist): Operation not allowed

and **eco-emissary-99515** is not the name of my project!

maybe you can provide an answer for me here or/and add it to your docs

**Comment by BanzaiMan** [comment]
Hi, there.

I'm afraid this is not a documentation issue. It is not clear to me what your Rake task is trying to do (or where the project name is coming from), but I suggest first examining that.

You can also try community site: https://travis-ci.community/.
