### ISSUE TITLE
Heroku deployment guide should recommend `heroku authorizations:create`

### ISSUE THREAD

**Issue by anp** [travis-ci/docs-travis-ci-com#2224]
Hello! Heroku's recent CLI updates have begun recommending not to use `heroku auth:token` for long-lived authorizations as is currently recommended in [the Travis/Heroku deployment guide](https://github.com/travis-ci/docs-travis-ci-com/blob/87ca95fc3241be251657b63aec50b4f7d2715fbb/user/deployment/heroku.md). For example, I got this output this morning:

```
$ heroku auth:token
...
 ›   Use heroku authorizations:create to generate a long-term token
...
```

The recommended command has more complicated output, however:

```
$ heroku authorizations:create
Creating OAuth Authorization... done
Client:      <none>
ID:          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Description: Long-lived user authorization
Scope:       global
Token:       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Updated at:  Fri Jan 11 2019 06:57:24 GMT-0800 (Pacific Standard Time) (less than a minute ago)
```

There is a `--json` flag available, but to work with that in a one-liner you'd probably need to install jq or something similar. It might make the docs a bit more complicated overall, but changing to this command will prevent other users from having subpar experiences where deployments mysteriously stop working.

**Comment by plaindocs** [comment]
That is a great suggestion! Would you care to open a pull request? I'd probably op for multiple lines instead of installing  `jq` for this.
