### ISSUE TITLE
Choose nixpkgs channel

### ISSUE THREAD

**Issue by mwillsey** [travis-ci/docs-travis-ci-com#2236]
Hello,

The docs for [Building a Nix Project](https://docs.travis-ci.com/user/languages/nix) says:

> The default channel for `nixpkgs` will be `nixpkgs-unstable`.

Can this be changed? Perhaps through a field like`nixpkgs: 18.09`?

This may already be the case, I have not tried. If it is, then it should be documented.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-build/pull/1631

Also, this is not a docs issue per se, so I'm closing this.

**Comment by mwillsey** [comment]
For what its worth, I've found a couple solutions to this that could hopefully be documented.

[Here's one](https://github.com/travis-ci/travis-ci/issues/8979) what involves `nix-channel`.

I did it another way by adding the following to `.travis.yml`:

```yaml
env:
  - NIX_PATH=nixpkgs=channel:nixos-19.03
```
