### ISSUE TITLE
Where does Cassandra version come from

### ISSUE THREAD

**Issue by dmetzgar** [travis-ci/docs-travis-ci-com#2238]
The documentation for [Cassandra database setup](https://docs.travis-ci.com/user/database-setup/#cassandra) says "Cassandra is provided by Datastax Community Edition and uses the default configuration." But the Datastax site says they [no longer provide](https://academy.datastax.com/planet-cassandra/cassandra) Datastax Community Edition. What version of Cassandra is Travis using?

**Comment by plaindocs** [comment]
Hey @metzgar, you've got a point there. I've updated the docs. Let me know if you need any more info.

**Comment by dmetzgar** [comment]
Thanks!
