### ISSUE TITLE
Docker updating to 18.06.1 (should be 18.09.1)

### ISSUE THREAD

**Issue by pascalandy** [travis-ci/docs-travis-ci-com#2250]
On page https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version there are an instruction to update to the latest docker version. I'm expecting **18.09.1** but I **18.06.1-ce**.

Something is off regarding the add-apt-repository.

Thanks!

**Comment by BanzaiMan** [comment]
Hello, there. This is not a docs issue. Please use https://travis-ci.community/ for usage support.

**Comment by pascalandy** [comment]
I'll be glad to do so. I click on Edit on Github on stumble onto this repo. So it's kind of confusing :-p

**Comment by BanzaiMan** [comment]
Thanks for the feedback. The button is intended for suggesting documentation improvements. We'll see how we can improve that.
