### ISSUE TITLE
XUnit sample should use test runner for .NET 4.0 instead of .NET 2.0?

### ISSUE THREAD

**Issue by kpstolk** [travis-ci/docs-travis-ci-com#226]
I noticed that the [XUnit sample](http://docs.travis-ci.com/user/languages/csharp/#xunit) uses the `xunit.console.exe` which is for .NET 2.0 as displayed in the build log:

> $ mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.exe MyProject/bin/Release/UnitTests.dll
> xUnit.net console test runner (64-bit .NET 2.0.50727.1433)
> Copyright (C) 2013 Outercurve Foundation.

But since most projects nowadays use .NET 4.0+ it might be better to set the default to [`xunit.console.clr4.exe`](http://stackoverflow.com/a/21442791/465942) which uses .NET 4.0 as displayed in the build log?:

> $ mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe MyProject/bin/Release/UnitTests.dll
> xUnit.net console test runner (64-bit .NET 4.0.30319.17020)
> Copyright (C) 2013 Outercurve Foundation.

**Comment by BanzaiMan** [comment]
Paging @joshua-anderson @akoeplinger @nterry

**Comment by kpstolk** [comment]
I just noticed that it is important to have the [xUnit.net version 1.9.2](https://www.nuget.org/packages/xunit/1.9.2) in your project because the recently released [version 2.0.0](https://www.nuget.org/packages/xunit/2.0.0) shows an error in the build log that `xunit.dll` can't be found. (I think that the DLL name has changed to xunit.core.dll).

So:
1. `xunit.console.clr4.exe` instead of `xunit.console.exe` is still relevant.
2. How can the xUnit version 2.0.0 version be used / supported?

**Comment by akoeplinger** [comment]
> xunit.console.clr4.exe  instead of  xunit.console.exe  is still relevant.

Good point: https://github.com/travis-ci/docs-travis-ci-com/pull/227

> How can the xUnit version 2.0.0 version be used / supported?

Right now you can't, there's a bug in Mono that shows up with how xunit 2.0 uses appdomains and it hangs after test execution. A fix is pending, you should just stick with 1.9.2 until it makes it into a release (also note that in xunit2, the console runner is now in it's own package xunit.runner.console and is called xunit.console.exe for the net4.0 version again :smile:, so this is all just a point in time thing)

**Comment by kpstolk** [comment]
Thanks for updating the sample code.

Is there a ticket or some more info about the xunit 2.0 issue?
And maybe it's an idea to add a note or something to the sample about this? I've spend quite some time until I figured out that I did not have the 1.9.2 version in my project..

**Comment by akoeplinger** [comment]
> Is there a ticket or some more info about the xunit 2.0 issue?

Here's the PR: https://github.com/mono/mono/pull/1654 (not sure if this fixes all of the bugs with xunit2).

> And maybe it's an idea to add a note or something to the sample about this?

Yeah, since it doesn't look like the fix will make it into the upcoming Mono 4.0 a note can't hurt. Done.

**Comment by NullVoxPopuli** [comment]
That PR has been merged - so is there a way to run with xunit 2.0?

**Comment by akoeplinger** [comment]
@NullVoxPopuli Assuming there are no other issues, you just install xunit 2.0 and run it as usual (check the xunit docs).
