### ISSUE TITLE
question about use all Ubuntu version?

### ISSUE THREAD

**Issue by liuyunbin** [travis-ci/docs-travis-ci-com#2260]
I wan't test all Ubuntu 12.04 and Ubuntu 14.04 and Ubuntu 16.04, what should I do? 

In my opinion, I could use three branch, but I think there should have better method.

thanks.

**Comment by BanzaiMan** [comment]
Sorry, but this is not a docs issue. If you want support on how to use Travis CI, please open a topic over at https://travis-ci.community.

Thanks.

**Comment by liuyunbin** [comment]
sorry and thanks.
