### ISSUE TITLE
The chef supermarket deployment needs and example

### ISSUE THREAD

**Issue by tas50** [travis-ci/docs-travis-ci-com#2267]
The chef supermarket deployment page at https://docs.travis-ci.com/user/deployment/chefsupermarket/ really needs an example showing how / where to put your client key. Without an example there isn't much chance people are going to figure out how to do this.

**Comment by plaindocs** [comment]
Hey @tas50 I think you're right! 

The text over in [dpl](https://github.com/travis-ci/dpl#chef-supermarket) includes which should be sufficient. I'll open a PR. 

```
dpl --provider=chef-supermarket --user-id=chef --client-key=.travis/client.pem --cookbook-category=Others
```

**Comment by tas50** [comment]
:( Stale bots don't help

**Comment by tas50** [comment]
Still not a helpful bot

**Comment by tas50** [comment]
Still not helpful
