### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by RDIL** [travis-ci/docs-travis-ci-com#2275]
Hi,
I found out that if you trigger a custom build, it seems that the `TRAVIS_COMMIT_MESSAGE` env variable doesn't sync with the custom commit message.  An example can be found [here](https://travis-ci.com/RDIL/area4/builds/100451468).  `!extra` was in the commit message so extra tests should have been run, but they were not.

**Comment by BanzaiMan** [comment]
Thanks for the report, but this is not a docs issue. For bugs, please use https://travis-ci.community. (I've already created this topic at https://travis-ci.community/t/travis-commit-message-is-not-overwritten-by-env-set-in-api-payload-it-is-always-set-by-the-git-data/2233.)

**Comment by RDIL** [comment]
Ah I see thanks
