### ISSUE TITLE
Make Private Dependencies doc easier to search for

### ISSUE THREAD

**Issue by aquaranto** [travis-ci/docs-travis-ci-com#229]
From this ticket: https://secure.helpscout.net/conversation/83797922/15066/

Aaron had an issue searching for this document http://docs.travis-ci.com/user/private-dependencies/.

He said it took him 30 mins before he gave up and pinged support. Any way we can make it easier to search for? (his search params were "travis-ci private modules")

**Comment by plaindocs** [comment]
Do you mean searching on the web generally? Or on docs.travis-ci.com ?

On docs.travis-ci.com putting "private" or "travis ci private" in the search box works just fine, so I'm assuming the web. Would be nice to be able to use that somehow...

Are we talking about npm modules? Any other likely search terms and keywords I need to add while I'm there?

**Comment by shellscape** [comment]
@plaindocs just piggy backing on this one; there don't seem to be any docs for Travis on installing Private Modules from npmjs.org. That's a newish, recent offering from them.

**Comment by plaindocs** [comment]
This kind of thing? http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules

**Comment by shellscape** [comment]
Yes, but for public repos you're not going to want to check in your auth token. That'd be a big security concern, and negate the use of private modules :)

I've been looking for a setting in Travis CI for the auth_token, npmrc to use, or the like for a particular repo.

**Comment by plaindocs** [comment]
If you'd like to make a pull request for those docs that would be awesome. I'm happy to give you feedback.

**Comment by shellscape** [comment]
> I've been looking for a setting in Travis CI for the auth_token, npmrc to use, or the like for a particular repo.

I'm not sure you understand. I can't find the docs that explains how to go about setting up travis for access to private modules without checking in/committing the private _authToken (which is a security risk to do so). So there's nothing to submit a PR for until someone can point out how that's done.

**Comment by plaindocs** [comment]
Would encrypting it work? http://docs.travis-ci.com/user/encryption-keys/

I'm not sure where you're adding your token. To `npm`? Or `.travis.yml`?

**Comment by MariadeAnton** [comment]
Seems Remy covered something similar in here: https://remysharp.com/2015/10/26/using-travis-with-private-npm-deps in case it helps clarifying things. 

@plaindocs I believe encrypting works as the auth_token for NPM needs to be used during build time to publish the package.

**Comment by MariadeAnton** [comment]
This issue has been overseeded by: https://github.com/travis-ci/docs-travis-ci-com/issues/254
