### ISSUE TITLE
List all whitelisted packages and sources

### ISSUE THREAD

**Issue by Joshua-Anderson** [travis-ci/docs-travis-ci-com#231]
It would be really nice to have a table of the whitelisted packages and sources. You could probably use JavaScript to fetch the json whitelist from the respective repositiories. You could use this data to populate a table with a searchbox so you can search to see if your package was whitelisted. If I have some spare time I might do this myself.

**Comment by MariadeAnton** [comment]
thank you @Joshua-Anderson, I think it's a great idea!

**Comment by plaindocs** [comment]
I'll close this for now, as I don't have time to implement it. If you do fancy putting something together @Joshua-Anderson I'm happy to work with you to merge it in.
