### ISSUE TITLE
AWS S3 artifacts page needs to mention artifacts bug #57

### ISSUE THREAD

**Issue by ehuelsmann** [travis-ci/docs-travis-ci-com#2313]
The documentation page https://github.com/travis-ci/docs-travis-ci-com/blob/master/user/deployment/s3.md really needs to mention travis-ci/artifacts#57. If you're in one of the unsupported regions (and their number is growing!), it takes an endless amount of time to discover that running `pip install --user --upgrade awscli` and using `aws s3 cp` to copy the assets out, works like a charm. And it's not even a workaround! (in my view, that is).

**Comment by mytinam** [comment]
I want my gmail fixed so I can send and respond to email tracking . Link in email to comfrim  email want work

**Comment by ehuelsmann** [comment]
It's not handled, it's it? It just fell off the table, right?

**Comment by mytinam** [comment]
I dont know what u talking about.  Could you please tell me a lil more my
phone has been hacked 1st of year when they hacked google they got my
identity email Social Security everything I had to freeze everything didn't
you cards and everything he's changed the settings on my phone and
everything I can't respond to emails so I hope you get this if you would
please explain to me what's going on and like I said they're working on my
email trying to get it fixed I might get it but when I go to respond it
says page can't be found or it's been blocked or something I don't know but
I appreciate it if you could tell me a little bit about this cuz I don't
understand and if I don't know maybe you can help me and tell me thank you

**Comment by ehuelsmann** [comment]
It's confirmed. The page doesn't mention it. So, stale bot, keep away.
