### ISSUE TITLE
Fetching public keys for travis-ci.COM doesn't work as it works with travis-ci.ORG

### ISSUE THREAD

**Issue by aasaru** [travis-ci/docs-travis-ci-com#2327]
https://docs.travis-ci.com/user/encryption-keys/
says repo public key can be fetched like this:
https://api.travis-ci.org/repos/travis-ci/travis-ci/key
and this works (without any loggin in)

However if I have a repo in travis-ci.com, then the following:
https://api.travis-ci.COM/repos/travis-ci/travis-ci/key
returns 401 Unauthorized

**Comment by BanzaiMan** [comment]
This should be documented. The relevant documentation is https://developer.travis-ci.com/resource/key_pair_generated#Key%20pair%20(generated).
