### ISSUE TITLE
Dropdown on Travis log for script section

### ISSUE THREAD

**Issue by jcohenadad** [travis-ci/docs-travis-ci-com#2339]
Hi,

I have a small feature request: Some sections of the `.travis.yml` file, when listed by bullet points, appear in the Travis log with a dropdown arrow capabilities. For example, if in `before_install` section I list three items, those items would appear in the Travis log as `before_install.1`, `before_install.2` and `before_install.3`.

Now, this feature seems to not be working for items listed in the `script` section, making it difficult to debug when there are a lot of items. 

Would it be possible to activate the dropdown feature for the `script` section as well?

p.s. Thank you so much for offering this wonderful service to the community!

**Comment by BanzaiMan** [comment]
Hello, there.

Thanks for taking time to open the issue, but this repository is for our docs site https://docs.travis-ci.com.

Feature requests such as this should go to https://travis-ci.community/ instead.

**Comment by jcohenadad** [comment]
Sorry about that, ticket opened [here](https://travis-ci.community/t/dropdown-on-travis-log-for-script-section/3141).
