### ISSUE TITLE
What happened to the "run docker locally" section?

### ISSUE THREAD

**Issue by linwoodc3** [travis-ci/docs-travis-ci-com#2342]
What happened to the `Running a Container Based Docker Image Locally` section?

It used to be on the troubleshooting page but it's gone now.

I got to it via archive.org at: https://web.archive.org/web/20180331074120/https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

Any reason why it's missing?

**Comment by plaindocs** [comment]
That would be because those docs were about Container Based, which has been deprecated. 
https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures 

Ask on https://travis-ci.community if you need more info on running Docker on the current infrastructure.

**Comment by Kyle-Falconer** [comment]
@plaindocs If local docker builds have been deprecated, then what's the replacement? How can I run a build locally (with or without docker)?

**Comment by muizzk** [comment]
Hello @Kyle-Falconer, this feature has since been replaced by [Debug Builds](https://docs.travis-ci.com/user/running-build-in-debug-mode/). I hope this helps
