### ISSUE TITLE
How to test R package with OpenBLAS as the R Blas?

### ISSUE THREAD

**Issue by jaredhuling** [travis-ci/docs-travis-ci-com#2359]
How does one test an R package in travis-ci with R (and the package) compiled under OpenBLAS? The new CRAN checks are testing for this and I want to make sure that all my packages meet the new CRAN testing standards but have not been able to figure out how to make it work.

**Comment by BanzaiMan** [comment]
For help on community-supported languages such as R, please use https://travis-ci.community/. (For R in particular, https://travis-ci.community/c/languages/r.)
