### ISSUE TITLE
MATRIX_EVAL documentation

### ISSUE THREAD

**Issue by jpan127** [travis-ci/docs-travis-ci-com#2368]
It seems like the proper way to override the default exporting of CC and CXX is to use `MATRIX_EVAL`, from the documentation on C / C++ usages.  It is somewhat obvious how it should be used, but I can't find any documentation on it.  I would suggest adding an explanation of it and what it is capable of.

**Comment by BanzaiMan** [comment]
There is nothing special about the name `MATRIX_EVAL` in https://docs.travis-ci.com/user/languages/cpp/. It is an environment variable that is `eval`'d in `before_install`, so that you would not have to override `before_install` in any of the jobs defined in `matrix.jobs`.

**Comment by BanzaiMan** [comment]
Perhaps it is more confusing to have it this way (that is, add `env` in each of `matrix.include`).

**Comment by jpan127** [comment]
Ah, you're right.  After using it more I realized it was nothing special.  Maybe something in the documentation explaining what it is used for can also shed light on how any variable name can be used.

On another note, I feel like it is kind of a bandaid over the fact that `CC and CXX` are exported and can potentially mask the user exporting these variables.

If there was a more standardized approach, maybe some setting `dont_export_compiler_env_var` would be more explicit and friendly.
