### ISSUE TITLE
Confusing basic concepts.

### ISSUE THREAD

**Issue by dongwangdw** [travis-ci/docs-travis-ci-com#2408]
Recently, I need use travis to build a pipeline. When to read the doc, I am a little confused with the basic concepts. And I found little about these kind basis concepts in the docs. If I missed something, please guide me please.

>phase - the sequential steps of a job. For example, the install phase, comes before the script phase, which comes before the optional deploy phase.
>job - an automated process that clones your repository into a virtual environment and then carries out a series of phases such as compiling your code, running tests, etc. A job fails if the return code of the script phase is non zero.
>build - a group of jobs. For example, a build might have two jobs, each of which tests a project with a different version of a programming language. A build finishes when all of its jobs are finished.
>stage - a group of jobs that run in parallel as part of sequential build process composed of multiple stages.

Above is the segment from the doc.
I can understand that the jobs are composed of phases.
Job is whole thing you want to do, including preparing the env, and doing the stuff.

What I am confused of are **build and stage.**? I find the stage in some file, but I can not understand what is the build?  From the description, I can not figure it out. 

The typical example I saw is as following:

```
pre_install:
install:
pre_script:
script:
jobs:
   include:
    stage: stage1
      script:
    stage:  stage2
    stage: stage3
```

What if I want to figure out the syntax where I can find the doc? Nothing about them mentioned in the docs.

Any help will be appreciated. Thanks in advance.

**Comment by Pezi777** [comment]
Hi dongwangdw, thank you for your contribution. 
You are right that it can be confusing. A build can have several jobs. Build stages is a way to group jobs, and run jobs in each stage in parallel, but run one stage after another sequentially. On https://docs.travis-ci.com/user/build-stages/ you find more information on build stages. I hope this will help you to understand the difference?
