### ISSUE TITLE
Document `group` key

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#2418]
In the #2389 there is some mention of `group: dev`.

We really  need better documentation of when to use `dev` and `edge` and what they mean.

Somewhere in https://docs.travis-ci.com/user/reference/overview/ would be a good place to start, maybe with an extra section in each Ubuntu release? 

@zhengphou might be able to help.

**Comment by zhengphou** [comment]
I'd propose to drop those tags for reasons:
1 we have our staging environment, any effort in development or testing stage should be in the staging env
2 It's confusing, users won't be able to tell exact difference and when to use it. 
3 No matter which tags we use, users will ask us for support when they running into issues.
