### ISSUE TITLE
travis can not reach rubygems-proxy.torquebox.com

### ISSUE THREAD

**Issue by mkristian** [travis-ci/docs-travis-ci-com#242]
several builds use gem artifacts from rubygems-proxy.torquebox.com, basically rubygems proxied and supplied as maven repository. these gems can be used via maven plugins and gradle plugins.

some builds which are currently failing: 

https://travis-ci.org/lookout/leafy
https://travis-ci.org/jruby/jruby

yesterday there was DOS attack on the host running  rubygems-proxy.torquebox.com - some IPs got blocked as countermeasure. it works again locally with me but travis-ci still only sees connection timeouts to connect to this server. it is possible that the external IP of the travis build servers are part of the blocked IP ranges. 

could you please let me know what IPs travis uses on outbound interfaces ?

then we can fix the IP ranges !!

alternatively and even better in for those few projects using gem artifacts is to add them to maven mirrors: #241

**Comment by MariadeAnton** [comment]
@mkristian the IP ranges we use are available here now: https://docs.travis-ci.com/user/ip-addresses/

Is this what you were looking for?

**Comment by plaindocs** [comment]
Closing this for now. Please reopen if it is still relevant.
