### ISSUE TITLE
consider updating maven to version 3.3.x

### ISSUE THREAD

**Issue by mkristian** [travis-ci/docs-travis-ci-com#243]
maven 3.3.x comes with extension support in  way that you can use ruby DSL pom-files which some jruby based projects are using, including jruby project itself. they have to use a maven wrapper instead of the installed maven BUT this has some limits since there is some /etc/mvnrc file which exports MAVEN_HOME which interferes with the maven running via the maven wrapper.

it is save to remove at least the MAVEN_HOME export of the maven setup since the ```mvn``` executable will set it as needed.

the current maven setup of travis does not allow to run invoker tests with maven wrapper since they start picking the maven from MAVEN_HOME env. the current workaround is to add to travis.yml:

```yaml
before_script:
  - export MAVEN_SKIP_RC=true
```

**Comment by BanzaiMan** [comment]
See also: https://github.com/travis-ci/travis-ci/issues/3778

**Comment by mkristian** [comment]
@BanzaiMan OK

what about the mvnrc file ? shall I make a new issue for this to keep it separated ?
