### ISSUE TITLE
Create Linux build environment reference

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/docs-travis-ci-com#2435]
As it is right now, we have Operating System guides for macOS, Windows and then the different Ubuntu distributions that we support. I believe we should have an Ubuntu Linux reference page to walk people through the current default and the newer / older options available, as well as their planned availability. 

This would help simplify our side-bar menu: 

![image](https://user-images.githubusercontent.com/3729517/61522548-dc14e180-aa12-11e9-86d0-39ae3ea2cbb6.png)
 
And group Precise, Trusty, Xenial and Bionic together as the different xcode images are grouped and the future windows images will too. 

What do you think @Pezi777 and @biancawilk? Thank you!

**Comment by rock5teady** [comment]
Yea

**Comment by Pezi777** [comment]
It's already there (https://docs.travis-ci.com/user/reference/linux/) as it was implemented by https://github.com/travis-ci/docs-travis-ci-com/pull/2434
