### ISSUE TITLE
Clarification for the NPM instructions:

### ISSUE THREAD

**Issue by pygy** [travis-ci/docs-travis-ci-com#246]
https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/deployment/npm.md

says:

> For a minimal configuration, all you need to do is add the following to your `.travis.yml`:
> 
> ```
> deploy:
>   provider: npm
>   email: "YOUR EMAIL ADDRESS"
>   api_key: "YOUR API KEY"
> ```

Where "YOUR API KEY"  is the result of `echo -n "username:password" | base64` optionally encrypted.

I suppose that the username/password pair is the npm one, but what about the email address?

---

As a side note,  accepting non-encrypted credentials is IMO doing a disservice to your users.

**Comment by thepatrick** [comment]
I'll echo this, what email is this asking for?

From my own custom deployment script I know that `npm publish` just needs a .npmrc with `//registry.npmjs.org/:_authToken=API_KEY`.

**Comment by plaindocs** [comment]
According to https://github.com/travis-ci/dpl#npm it is the npm email.

But I'll investigate and clarify.

**Comment by BanzaiMan** [comment]
These option values are passed on to `~/.npmrc`.

**Comment by pygy** [comment]
@plaindocs thanks for docs fix :-)
