### ISSUE TITLE
Explain filename extension compatibility (.yml/.yaml)

### ISSUE THREAD

**Issue by mk-pmb** [travis-ci/docs-travis-ci-com#2478]
The docs pages always use `.yml`, while the authors of YAML [ask us to](https://yaml.org/faq.html)

> Please use ".yaml" when possible.

so could we add a little explanation to the tutorial whether `.yaml` is accepted as well, or why not? (If I were to decide, I'd even give `.yaml` precedence in case both exist.)

**Comment by mk-pmb** [comment]
Any updates on this?

**Comment by Montana** [comment]
I don't see a reason to make multiple requests to check for `.travis.yml` then -> `.travis.yaml`. Logically doesn't make sense. 

The explanation is, I'll put it for you in "styleguide" terms, different companies have styleguides on how they want their code written. For example if I was writing JavaScript, and I was used to one convention, but the company I was working for was used to another, it may look like this: 

``` JavaScript
// bad
const item = new Object();
```

Above, would be the way they wouldn't want you to create an object in JavaScript, but below is company convention: 

```JavaScript
// good
const item = {};
```

I hope this clears things up a bit, there's a lot of things that are "convention" or "best practices" or "practical standards" but in real life scenarios, these are not always followed. 

I hope this makes a bit more sense now. 

- Montana

**Comment by Montana** [comment]
I don't see a reason to make multiple requests to check for `.travis.yml` then -> `.travis.yaml`. Logically doesn't make sense. 

The explanation is, I'll put it for you in "styleguide" terms, different companies have styleguides on how they want their code written. For example if I was writing JavaScript, and I was used to one convention, but the company I was working for was used to another, it may look like this: 

``` JavaScript
// bad
const item = new Object();
```

Above, would be the way they wouldn't want you to create an object in JavaScript, but below is company convention: 

```JavaScript
// good
const item = {};
```

I hope this clears things up a bit, there's a lot of things that are "convention" or "best practices" or "practical standards" but in real life scenarios, these are not always followed. 

I hope this makes a bit more sense now. 

-Montana

**Comment by mk-pmb** [comment]
Thanks! A style guide or company convention would solve the question for a reason ("why?"). It's been a long time but I can't remember asking about the reason or justification (yet), so afair this issue was just about documenting what Travis expects.
