### ISSUE TITLE
Provide more actionable options when document is not found

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/docs-travis-ci-com#248]
Currently, we only see 404 when the document is not found: http://docs.travis-ci.com/foobar

While this is correct, perhaps we can be more helpful by returning the search results which are possibly related to the specified path.

**Comment by lislis** [comment]
I added the search box for docs in a42a334c16a524092e0. @BanzaiMan wdyt?

**Comment by BanzaiMan** [comment]
@lislis Looks good!
