### ISSUE TITLE
Fetching public key API is broken

### ISSUE THREAD

**Issue by techtonik** [travis-ci/docs-travis-ci-com#2498]
https://docs.travis-ci.com/user/encryption-keys/#fetching-the-public-key-for-your-repository

https://api.travis-ci.org/repos/travis-ci/travis-ci/key gives `{"file":"not found"}`.

**Comment by techtonik** [comment]
The documentation could also mention encryption algorithm.

**Comment by BanzaiMan** [comment]
This is still valid.
