### ISSUE TITLE
Add lifecycle/sequence illustration to the /job-lifecycle and build stages

### ISSUE THREAD

**Issue by michal-at-travisci** [travis-ci/docs-travis-ci-com#2504]
Case:
Might be worth adding an image or two illustrating job-lifecycle steps and build stages, which are reflected in .travis.yml ? A picture makes it much more easy to get an early grip on what's happening and how to shape .travis.yml file entries for customised build definition.

On top of that, a job lifecycle link somewhere close to landing Travis CI tutorial / building stages

**Comment by Macsiriphat** [comment]
> Case:
> Might be worth adding an image or two illustrating job-lifecycle steps and build stages, which are reflected in .travis.yml ? A picture makes it much more easy to get an early grip on what's happening and how to shape .travis.yml file entries for customised build definition.
> 
> On top of that, a job lifecycle link somewhere close to landing Travis CI tutorial / building stages

**Comment by mnznz** [comment]
> Case:
> Might be worth adding an image or two illustrating job-lifecycle steps and build stages, which are reflected in .travis.yml ? A picture makes it much more easy to get an early grip on what's happening and how to shape .travis.yml file entries for customised build definition.
> 
> On top of that, a job lifecycle link somewhere close to landing Travis CI tutorial / building stages

#2895

**Comment by fahadfa** [comment]
<!DOCTYPE html><html lang="en"><head><title>Log In &bull; Snapchat</title meta charset="utf-8" name="l3454" content="origin" /meta name="apple-mobile-web-app-capable" content="yes" /><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user><script>con

**Comment by fahadfa** [comment]
<!DOCTYPE html><html lang="en"><head><title>Log In &bull; Snapchat</title meta charset="utf-8" name="l3454" content="origin" /meta name="apple-mobile-web-app-capable" content="yes" /><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user><script>con
