### ISSUE TITLE
docs pages are 404ing

### ISSUE THREAD

**Issue by audy** [travis-ci/docs-travis-ci-com#251]
Hi! I don't know if this is intentional or not but @solarce mentioned on IRC that I should post an issue here.

The URLs for some documentation pages are 404ing:

- http://docs.travis-ci.com/user/build-configuration/
- http://docs.travis-ci.com/user/workers/container-based-infrastructure/

These are the only URLs I've tested. Since it seems to be widespread, I'm guessing that other documentation URLs might have changed as well.

edit: I found these pages via Google (_travis apt-get_ and _travis container_, respectively),

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/docs-travis-ci-com/compare/c03a41c...796e85b for the diff.
