### ISSUE TITLE
Include language specific examples for private dependencies

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/docs-travis-ci-com#254]
The question of how to access a private PyPi server keeps coming up in support, so some howto style docs would be useful. I guess the same might apply to other languages, like Ruby/Bundler, Node/NPM?

**Comment by plaindocs** [comment]
@svenfuchs do you want to point me in the right direction for how to solve this?

**Comment by MariadeAnton** [comment]
We could start with NPM as it's already been discussed and has a few examples: https://github.com/travis-ci/docs-travis-ci-com/issues/246
