### ISSUE TITLE
Docs mention IRC as a support channel

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/docs-travis-ci-com#255]
Is this still up to date? 

![image](https://cloud.githubusercontent.com/assets/2208/8127845/21eee4fa-10fa-11e5-917b-ad5b959cf23c.png)

http://docs.travis-ci.com/user/getting-started/

**Comment by BanzaiMan** [comment]
Yes. I get on every now  and then.

**Comment by roidrage** [comment]
Removed the mentions of IRC as support channels.
