### ISSUE TITLE
Explain that jobs is just an alias for matrix

### ISSUE THREAD

**Issue by hakito** [travis-ci/docs-travis-ci-com#2557]
I took me several hours to get a matrix build for a language _minimal_ running because the documentation does not mention that _jobs_ is just an alias for _matrix_ and so my _matrix_ definition is simply ignored when i specify a _jobs_ section.

I just found the nescessary hint when looking at the [schema](https://github.com/travis-ci/travis-yml/blob/master/schema.json).

**Comment by noloader** [comment]
Also see [Issue 1500](https://github.com/travis-ci/docs-travis-ci-com/issues/1500).
