### ISSUE TITLE
What is Python v5.9 ?!?

### ISSUE THREAD

**Issue by cclauss** [travis-ci/docs-travis-ci-com#2569]
At the bottom of the table at the bottom of https://docs.travis-ci.com/user/languages/python/#python-versions there is an entry that says `16.04 | x86_64 | python-5.9.tar.bz2`

Perhaps we need a `python-3.9-dev` but I do not believe that Python 4 or 5 exists yet.  ;-)

**Comment by MariadeAnton** [comment]
This definitely looks like a typo on somewhere along the way of the auto generated version list - thanks so much for spotting @cclauss!

@BanzaiMan could you take a look?

**Comment by BanzaiMan** [comment]
Probably a failed attempt at creating a PyPy archive of some sort. I'll remove the archive.

**Comment by ammaraskar** [comment]
Just fyi the 5.9 listing is still up.

**Comment by BanzaiMan** [comment]
@ammaraskar Thanks for pointing that out. I've _*really*_ fixed the issue this time. ;-)
