### ISSUE TITLE
Is there any way to mock location using an android emulator in travis?

### ISSUE THREAD

**Issue by freakyblue** [travis-ci/docs-travis-ci-com#2596]
Usually you need to add the mock_locations permission manually or use `adb shell appops set com.example.my.package android:mock_location allow` to grant this permission. But if you add this line to my `.travis.yml` it does not change anything. You still get the error
`V/InstrumentationResultParser: java.lang.SecurityException: Requires ACCESS_MOCK_LOCATION secure setting`

Could you please add an explanation of the solution to the docs?

**Comment by freakyblue** [comment]
I tried it [here](https://github.com/freakyblue/GPSDemo) but it looks like in travis' `adb` some permissions (or AppOps) are missing (e.g. `mock_location`).

`adb shell pm list permissions` lists all permissions of adb, usually including this line:
`permission:android.permission.ACCESS_MOCK_LOCATION` but if I execute that command in travis, the list of permissions is much shorter and I can not use the command. 
```
adb shell appops set com.example.my.package android:mock_location allow  
  Error: Unknown operation string: android:mock_location
```

**Comment by michal-at-travisci** [comment]
Hi @freakyblue !
Thanks for writing. Just for sake of analyzing: pointing to `.travis.yml` is less useful than a link to exact build, where things failed for you, as there are a log and a configuration that was used for this specific build available. Is this the same build as reported in community forum? If not, could you provide links to exact builds or even build jobs you are running?
Cross referencing to keep items together: https://travis-ci.community/t/how-can-i-add-mock-location-permission-to-android-jobs/6162/8
