### ISSUE TITLE
xenial/bionic has out-of-date supported php version

### ISSUE THREAD

**Issue by adaamz** [travis-ci/docs-travis-ci-com#2606]
Does anybody know which php versions I can install? The doc seems out-of-date as I can install php 7.3 on xenial with no problem.

**Comment by AlonaHlobina** [comment]
For the Xenial image we have preinstalled PHP language versions:
- 5.6, 5.6.40, 
- 7.1, 7.1.27
- 7.2.15 is the default one.
Please see: https://docs.travis-ci.com/user/reference/xenial/#php-support
The latest PHP versions like 7.3 and 7.4 can be used, but they are not pre-installed. 
For dynamic runtime selection, phpenv is available.

**Comment by adaamz** [comment]
Yeah, that is the question. Because when I include php 7.3/7.4 in versions, it works.
