### ISSUE TITLE
Mention OS on infrastructure pages

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/docs-travis-ci-com#265]
It would be good if pages like http://docs.travis-ci.com/user/workers/standard-infrastructure/ mentioned which OS is running.

For our standard and docker/container based infrastructure this would be 12.04 as of writing.

**Comment by plaindocs** [comment]
I'm phasing these Worker pages out in favour of one CI Environment page. OS Versions are covered in http://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

**Comment by svenfuchs** [comment]
Ah, I haven't seen these pages. Ok, that's cool.

However, the matrix seems a little confusing. The default environment is Docker for more recently hooked up repos, isn't it? And it's only the default for old repos. http://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

/cc @joshk

**Comment by plaindocs** [comment]
Yeah, the source material is old. We're going to have a slight headache with default switching from non docker to docker whichever way we put it. But I think a comment to that effect, along with an easy way for people to check with one they are in should cover it.

**Comment by MariadeAnton** [comment]
@plaindocs is /user/workers still relevant? What's the short-term plan for it? Is it going to be deleted and replaced by /ci-environment?

**Comment by plaindocs** [comment]
These have been deleted.
