### ISSUE TITLE
Travis CI Django Build Fails

### ISSUE THREAD

**Issue by OliBarrington** [travis-ci/docs-travis-ci-com#2650]
For the past few days, I have been working with Travis CI to automatically run my test cases. However, I cannot get it to work.

Running my test cases locally works great. I use the command:

`python manage.py test myApp
`

My travis.yml file is as follows...

```
language: python

os: linux

python:
 - "3.5.2"

services: postgresql


install:

 - pip install -r requirements.txt

script: 

 - python manage.py test myApp
```

`django.db.utils.ProgrammingError: column myApp_userdocument.createdOn does not exist`

I have tried running migrate before running the script with no luck. Does anything look blatantly wrong with my travis file?

**Comment by Montana** [comment]
Hello @OliBarrington, 

I updated your post so it's in code format and easier for others to read if they run into this problem! If I were you I'd use  `makemigrations.` When only running migrate it won't help you, you have to run `makeigrations` as well.

So you're .travis.yml file should look something like this: 

```
script: 
 - python manage.py makemigrations
 - python manage.py migrate
 - python manage.py test myApp
```
Create your DB before `makemigrations`, so also under `before_script`

`before_script:
  - psql -c 'create database travis_ci_test;' -U postgres`

That should work for the Django build. If you need anymore help please report back, and I'll gladly assist you more. 

-Montana (Travis CI Staff)

**Comment by OliBarrington** [comment]
@Montana Many thanks! That did the trick.

**Comment by Montana** [comment]
No problem! Glad I could assist you. If you have anymore problems as stated before, be sure to stop by and I'll be here. 

-Montana (Travis CI Staff)
