### ISSUE TITLE
Yaml with bash: escaping quotes in string

### ISSUE THREAD

**Issue by OliBarrington** [travis-ci/docs-travis-ci-com#2657]
I want to execute command in travis file, it's executed by bash from yaml configuration file:

```
before_script:
 - psql -c 'create role "user" WITH LOGIN PASSWORD '1234'' -U postgres
```
But apparently I get the error: ERROR:  syntax error at or near ""1234"" and I just don't know how to escape quotes: '

**Comment by Montana** [comment]
Hey @OliBarrington, 

This isn't a YAML issue, it only really involves the shell launched by your Travis build at hand.

So remember that single quotes inside single quotes in a shell string (specifically) are escaped as double single quotes, so try this and this should do the trick for you! 

```ruby
psql -c 'create role "user" WITH LOGIN PASSWORD ''1234''' -U postgres
```

-Montana (Travis CI Staff)
