### ISSUE TITLE
Document issues around un-authorized organizations

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/docs-travis-ci-com#267]
![image](https://cloud.githubusercontent.com/assets/2208/8254590/338673cc-169a-11e5-9c2d-a2addf126bc0.png)

This link at the bottom of the left sidebar on the profile page goes to https://github.com/settings/connections/:id, which (I guess) should show Travis CI (Pro) as an "Authorized application" for the current user. If it doesn't, then Travis CI has a problem syncing organization memberships (and repos?) ... I guess.

All of this is kinda unclear even to me (Josh: "tbh, it is all confusing"), and GitHub's docs seem less than helpful, too, e.g. https://help.github.com/articles/about-third-party-application-restrictions/

I think it would be good for us to have a way more simple explanation of what's relevant to the user, how it works on GitHub, how it works on Travis CI, and how they can review things and resolve common problems.

Then link to that page on our own documentation, and only link to that arcane GitHub settings page from there.

**Comment by plaindocs** [comment]
I tend to agree. Unless you already have admin access to the github org you won't be able to change it anyway, right?

Do you have a list of common problems at all?

We do have http://docs.travis-ci.com/user/github-oauth-scopes/ which is vaguely relevant.
