### ISSUE TITLE
Travis conditional on branch after_success

### ISSUE THREAD

**Issue by TheDFury** [travis-ci/docs-travis-ci-com#2708]
In my Travis script I have the following:

```yaml
after_success:
- ember build --environment=production
- ember build --environment=staging --output-path=dist-staging
```

After both of these build, I conditionally deploy to S3 the one that is appropriate, based on the current git branch.

It works, but it would save time if I only built the one I actually need. What is the easiest way to build based on the branch, specifically the base branch? I've been trying to figure this out for some days now.

**Comment by Montana** [comment]
Hey @TheDFury. 

You should use the `test` command in the `after_success` section of your build instruction file. So your `.travis.yml` file would look like this:

```yaml
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    ember build
```
Alternatively you can deploy using a bash script in `after_success` and the script will check the branch using Travis environment variables:

```shell
#!/bin/sh

if [[ "$TRAVIS_BRANCH" != "master" ]]; then
  echo "We're not on the master branch."
  # This will analyze the current branch TheDFury and react accordingly
  exit 0
fi
```
Add the script somewhere in the build instruction, like so: 

```yaml
after_success:
- ./scripts/deploy_to_s3.sh
```
Then you'll be on your way to a successful deployment, and just like in any *nix distro, don't forget to change permissions via `chmod u+x` so it's read and writable. If you run into further problems try reading the the official [Travis Documentation](https://docs.travis-ci.com/user/environment-variables/) about environment variables. 

Please stop back by if you have any issues whatsoever, myself or another talented member of the Travis CI staff will get back to you. 

-Montana (Travis CI Staff)

**Comment by TheDFury** [comment]
Sorry I posted this on the forums too, I appreciate the help the bash script seemed to continue the deployment

**Comment by Montana** [comment]
Great to hear @TheDFury, 

If you need anymore help don't hesitate to ask and I'll be more than glad to help you. 

-Montana (Travis CI Staff)
