### ISSUE TITLE
Android is supported on xenial, too

### ISSUE THREAD

**Issue by timbru31** [travis-ci/docs-travis-ci-com#2717]
The docs state that the Android is only supported on Trusty (https://github.com/travis-ci/docs-travis-ci-com/blob/master/user/languages/android.md#L31), but it works on Xenial, too. However, currently not on Bionic.

**Comment by timbru31** [comment]
Not stale.

**Comment by michal-at-travisci** [comment]
Hi @timbru31 
At the moment we are not willing to extend or support more distributions with the Android builds. If it works on Xenial it's great! We'd love to see your PR with suggested change to the documentation!

**Comment by xskipy** [comment]
To add to this, it is not actually working on xenial. Travis just allows it as configuration and then switches back to Trusty. Check your build configuration
