### ISSUE TITLE
build-config-imports is confusing re merging of keys

### ISSUE THREAD

**Issue by ankon** [travis-ci/docs-travis-ci-com#2733]
https://github.com/travis-ci/docs-travis-ci-com/blob/156eb078f595aa28d96eee32adb1a1f7424422af/user/build-config-imports.md#L100-L102

This says things will be overwritten, but later on the default is called "deep_merge_append", which sounds more like stuff is getting appended -- which is a lot more sensible IMVHO.

This should be clarified:
- What's the default?
- What do these modes _mean_?

**Comment by svenfuchs** [comment]
@ankon thanks for the report! this was an oversight when rewriting this part of the documentation. i'll get this fixed.

**Comment by svenfuchs** [comment]
should be fixed here: https://github.com/travis-ci/docs-travis-ci-com/pull/2737

thanks again for the report, @ankon!
