### ISSUE TITLE
Undefined method where on "Job"

### ISSUE THREAD

**Issue by bmitchinson** [travis-ci/docs-travis-ci-com#2747]
https://docs.travis-ci.com/user/enterprise/platform-tips/#cancelling-or-resetting-stuck-jobs

![image](https://user-images.githubusercontent.com/33632286/79051578-8f071a00-7bf6-11ea-9b9e-01f038c60ffc.png)

**Comment by Montana** [comment]
Hello @bmitchinson, 

Could post the whole output in Markdown? 

Thanks, 

Montana.

**Comment by bmitchinson** [comment]
It's advised to use `Job.where` to reset stuck jobs here in the docs https://github.com/travis-ci/docs-travis-ci-com/blob/master/user/enterprise/platform-tips.md#cancelling-or-resetting-stuck-jobs

Here's my attempt, which is what was shown in the image above.

```
travis console
>> Job.where(queue: 'builds.linux', state: 'queued').all
NoMethodError: undefined method `where' for Job:Travis::Client::Namespace::Curry
from (pry):1:in `run'
>>
```

**Comment by BanzaiMan** [comment]
Please contact us through the Enterprise support channel. Thanks.
