### ISSUE TITLE
How to unit-test for failed file deletion?

### ISSUE THREAD

**Issue by SolarUltima** [travis-ci/docs-travis-ci-com#2762]
Hey Travis CI GitHub! 

I have an `os.remove()` in my code that sometimes, when ran locally, fails due to `OSError 13 - Permission Denied` - thus I've set up a `try-except`. My automated testing (Travis CI) is ran on Linux VM instances, so I don't know how to make `os.remove` fail there for sake of coverage.

What are my options - how do I force the `except` block to execute? Alternatively, how do I delete-protect a file with Python?

Note: Removing it in the test code before calling the test method isn't an option; the method itself fetches files to be removed:

```python
from pathlib import Path

paths = [str(x) for x in Path("directory/").iterdir() if 'abc' in x.stem]
if len(paths) > 0:  # if files are removed beforehand, len(paths) == 0
    try:
        [os.remove(p) for p in paths]
    except:
        pass  # stuff here

```
-SolarUltima

**Comment by Montana** [comment]
Hey nice to see you again @SolarUltima, 

You in theory usually can use `unittest.mock.patch` to patch `os.remove` and specify `OSError` as a `side_effect`, the example I laid out below should be of use:

```python
from unittest.mock import patch

...

with patch('os.remove') as mock_remove:
    mock_remove.side_effect = OSError('Permission Denied')
    try:
        [os.remove(p) for p in paths]
    except OSError as e:
        pass # handle error here
```

**Comment by SolarUltima** [comment]
as usual @Montana youre a hero! thank you so much

**Comment by BanzaiMan** [comment]
Happy to hear that @Montana was able to help.

Going forward, please direct all your "How do I do X?" questions to https://travis-ci.community. This repository is for documentation issues.
