### ISSUE TITLE
RethinkDB Example in "Installing Depdencies" is wrong

### ISSUE THREAD

**Issue by thejsj** [travis-ci/docs-travis-ci-com#279]
The [Installing dependencies](http://docs.travis-ci.com/user/installing-dependencies/) page lists RethinkDB as an example of a requirement that has a Launchpad PPA. But this is no longer supported. Instead, [RethinkDB has it's own repository](http://rethinkdb.com/docs/install/ubuntu/). 

Executing the code in this page installs a version of RethinkDB that is very old and is missing a lot of features. RethinkDB is currently working on removing the Launchpad PPA.

**Comment by plaindocs** [comment]
Thanks!
