### ISSUE TITLE
 Was there a patch related to jdk?  It does not build.

### ISSUE THREAD

**Issue by avolt** [travis-ci/docs-travis-ci-com#2792]
It does not build.

I am currently using jdk 8 and until now the build was normal.  last friday. 

However, today it is not suddenly built.

Was there a patch related to jdk?  

I'm sorry I didn't speak English well

[LOG]

resolvconf

install_jdk
Installing openjdk8
travis_setup_java: command not found
0.00s
ssh_key
Installing SSH key from: default repository key
Using /home/travis/.netrc to clone repository.
git.checkout
6.43s$ git clone --depth=50 --branch=master https://github.com/day2life/TB_api.git day2life/TB_api
0.01s
Setting environment variables from repository settings
$ export AWS_ACCESS_KEY=[secure]
$ export AWS_SECRET_KEY=[secure]
$ export TERM=dumb
cache.1
Setting up build cache
$ java -Xmx32m -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
$ javac -J-Xmx32m -version
javac 11.0.2
before_install
0.00s$ chmod +x gradlew
4.46s$ ./gradlew assemble
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine java version from '11.0.2'.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
The command "eval ./gradlew assemble " failed. Retrying, 2 of 3.
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine java version from '11.0.2'.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
The command "eval ./gradlew assemble " failed. Retrying, 3 of 3.

**Comment by Montana** [comment]
Hey @avolt, 

Can you direct your question to the Travis CI community forums? I'll be happy to help you there. 

https://travis-ci.community/

**Comment by Montana** [comment]
I solved this on the forum.
