### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by MaiHameed** [travis-ci/docs-travis-ci-com#2797]
Hello!

The page link to the OpenShift x Travis quickstart is broken. It's in the `user/deployment/openshift.md` file. The `Travis CI Quickstart` is supposed to take me to https://hub.openshift.com/quickstarts/26-travis-ci but redirects to https://catalog.redhat.com/software/containers/explore, could the link be updated to the new quickstart article home?

Thanks!

**Comment by BanzaiMan** [comment]
@MaiHameed Hello, there. https://docs.travis-ci.com/user/deployment/openshift has a handy "Improve this page" link on the upper right corner! We would love to have your PR.

**Comment by MaiHameed** [comment]
That sounds great if I knew where the article's new home is

**Comment by boomtow** [comment]
humhub\humhub[commented](Open)
