### ISSUE TITLE
Jekyll cant find gems in my Gemlock file 

### ISSUE THREAD

**Issue by SolarUltima** [travis-ci/docs-travis-ci-com#2798]
I'm very ware that I'm running the risk that this question is already answered somewhere else, but because I don't know the origin of this issue I'm not sure what to search for to find the answer.

I'm running bundle and Jekyll locally which is obviously localhost, which works perfectly fine. But when I install on Travis-CI, it presents me with the error Could not find public_suffix-4.0.4 in any of the sources. However, public_suffix-4.0.4 is clearly in my Gemfile.lock. Working with EventHandlers, so this would be ideal for any advice.

```yaml
Could not find public_suffix-4.0.4 in any of the sources
```
```yaml
script:
- gem install jekyll
- bundle install --full-index 
- bundle exec jekyll build -d _build
```
Gemfile in question 

```# frozen_string_literal: true


source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.0"
Gemfile.lock

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.6)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.7)
    ffi (1.12.2)
    forwardable-extended (2.6.0)
    http_parser.rb (0.6.0)
    i18n (1.8.2)
      concurrent-ruby (~> 1.0)
    jekyll (4.0.0)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (>= 0.9.5, < 2)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 1.8)
    jekyll-sass-converter (2.1.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.1.0)
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.2.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.3.6)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.4)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rouge (3.18.0)
    safe_yaml (1.0.5)
    sassc (2.2.1)
      ffi (~> 1.9)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    unicode-display_width (1.7.0)
```

```
PLATFORMS
  ruby
```

```
DEPENDENCIES
  jekyll (~> 4.0)
```

```
BUNDLED WITH
   2.1.4
```

**Comment by Montana** [comment]
If another `bundle install` didn't work, delete the `Gemfile.lock` then try specifying the version for `public_suffix` in the actual `Gemfile`, make sure the `env var` are defined as well, and on a more important note, correctly, this is a common user error as well. Looking at your `.travis.yml` file, you need to do the following: 

```ruby
gem "public_suffix", "~> 4.0.4"
```

Then run:

```ruby
bundle update jekyll
bundle install
bundle exec jekyll serve
```
See if then Jekyll finds your conditions. I see you also in the community support. I encourage you in the future to use the Travis CI community forums, I'd love to help you there and I'll always be available for you.

**Comment by SolarUltima** [comment]
@Montana, 

thank you so much! this absolutely solved my problem. and will do I sometimes read the documentation here and post my problems here. I will go to forums now.

**Comment by Montana** [comment]
Great, glad I could solve this for you. As stated above I look forward to helping you on the community forum.

**Comment by bsgreenb** [comment]
Giancuomo Massamillion D'Castillo Tortuilliani
