### ISSUE TITLE
macOS Build Environment: Add Xcode 11.5 and remove Xcode 6.4

### ISSUE THREAD

**Issue by cclauss** [travis-ci/docs-travis-ci-com#2804]
https://docs.travis-ci.com/user/reference/osx/#macos-version does not list Xcode 11.5 and lists Xcode 6.4 which has been gone for more than a year.

https://github.com/travis-ci/docs-travis-ci-com/blob/master/_data/xcodes.yml shows that 11.5 is currently available.

https://github.com/travis-ci/docs-travis-ci-com/search?q=osx_images&unscoped_q=osx_images

**Comment by cesar-cs** [comment]
Thanks, @cclauss! Created the [PR #2808 ](https://github.com/travis-ci/docs-travis-ci-com/pull/2808) to fix that.
