### ISSUE TITLE
Explain log size limits

### ISSUE THREAD

**Issue by krichter722** [travis-ci/docs-travis-ci-com#281]
The command output is limited to ~4 MB and is stripped after with the message `The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).`. This makes travis unsuitable for a bunch of projects and the user expects a tweak to overcome this or a statement that this limitation is definite (see https://api.travis-ci.org/jobs/69127489/log.txt?deansi=true for an example).

**Comment by joshk** [comment]
Hi @krichter722 

Just so I can understand, are you wanting some documentation to explain the log limit?

Thanks

Josh

**Comment by krichter722** [comment]
A statement that allows to evaluate the usability of travis for certain projects. One should be able to evaluate whether it's possible to display necessary information of the build and eventual failure - in the given example travis isn't suitable.

**Comment by joshk** [comment]
Hi @krichter722 

I will look into adding this information early next week.

Currently the log limit is there for web ui rendering purposes, as well as fair use (eg. not uploading 100 megs of logs).

Thanks a bundle

Josh

**Comment by gheinrich** [comment]
Perhaps there could be an option in Travis to allow users to choose to retain either the first 4MB of logs (default) or the *last* 4MB of the log (in order to be able to analyze test failures for example).

**Comment by joshk** [comment]
Hi @gheinrich, thanks for the input. That sounds like a feature request, which would best go in our main issues repo (https://github.com/travis-ci/travis-ci). Feel free to open an issue there :)

**Comment by krichter722** [comment]
The feature request should be opened in the main repo (this issue is only about the docs, but should be put on hold if a new feature is on the way). Do you @gheinrich want to open the new issue or should I (would make more sense if you did since you already have an idea)?

**Comment by gheinrich** [comment]
Sorry for the long response time, I have filed an enhancement request on the main repo.

**Comment by lynchlee** [comment]
could someone  tell me the solution please .....,

**Comment by io7m** [comment]
> the last 4MB of the log (in order to be able to analyze test failures for example).

I'd love to see this. I currently have a project that exceeds the log file size limits:

https://github.com/io7m/r2

The build is failing and I can't see why because the log is truncated.

**Comment by patduin** [comment]
Instead of the log to warn changes, can we use something like: https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#redirectTestOutputToFile
For Travis builds?

As a dev I kind of like chatty logs when running tests in the IDE, it really helps catching bugs. I don't like having to change it back and forth all the time and accidentally pushing it if I don't pay attention.

**Comment by wibobm** [comment]
No out of control recursive build here.  Just UnitTests doing their thing but the log gets truncated and can't see why the tests have failed.
