### ISSUE TITLE
Actual notification settings are missing from the documentation

### ISSUE THREAD

**Issue by bandesz** [travis-ci/docs-travis-ci-com#302]
In the notifications documentation page (http://docs.travis-ci.com/user/notifications/) there is the following part:

```
And it will by default send emails when, on the given branch:

* a build was just broken or still is broken
* a previously broken build was just fixed

You can change this behaviour using the following options:
```

But the options are missing after this. Could you please list them?

Thanks.

**Comment by jkrnak** [comment]
As I found, the docs are mentioning for IRC integration, that I can use `on_success` and `on_failure`. I was a bit sceptic why isn't this implemented for the other integrations, so I tried it for hipchat. Seemingly it is supported.

**Comment by plaindocs** [comment]
Fixed. Please let me know if anything else is not clear.
