### ISSUE TITLE
Add more info to "OS X Build Environment" on the different OS X images

### ISSUE THREAD

**Issue by solarce** [travis-ci/docs-travis-ci-com#316]
Currently http://docs.travis-ci.com/user/osx-ci-environment/ only details the 10.9 environment (which is the default) but adding a note on the newer 10.10 images available, which is detailed in http://docs.travis-ci.com/user/languages/objective-c/#Xcode-6.4 would  be helpful

(I will work on)

**Comment by plaindocs** [comment]
Awesome. Feel free to ping me if you want me to look over the text.

**Comment by andrewhavens** [comment]
I also ran into this issue. I was trying to figure out how to specify a newer version of Xcode. This documentation lead me to believe only Xcode 6.1 was supported. https://docs.travis-ci.com/user/osx-ci-environment/#Xcode

However, I found this other documentation which mentions that you can specify a newer version as an `osx_image`: https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions

**Comment by MariadeAnton** [comment]
This was fixed here https://github.com/travis-ci/docs-travis-ci-com/pull/565 🎉
