### ISSUE TITLE
Clarify APT addon usage

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/docs-travis-ci-com#337]
In http://docs.travis-ci.com/user/apt/

As the docs start with "When using the container based infrastructure" which might mislead users as it's also available in our legacy infrastructure as a (BETA).

**Comment by plaindocs** [comment]
Do you have any more info on that?

**Comment by MariadeAnton** [comment]
Just that our apt addon is available in legacy, container-based and trusty infrastructures. @BanzaiMan  could you confirm?

**Comment by BanzaiMan** [comment]
APT addon is available everywhere. There is no configuration option to disable it based on the infrastructure.

APT addon is _motivated_ by the containers, so it is most relevant there.

**Comment by mafagafogigante** [comment]
This would have saved me some time a few days ago. @MariadeAnton I also think that the first sentence should be about the addon itself and its availability. The way the text currently is places just too much emphasis on a limitation of the container based infrastructure.

I hope everyone agrees that this is an advancement.

**Comment by plaindocs** [comment]
Right, I suggest we merge in be8651f2793a8e23b0f7b9cfa72c3fa64e69a03b and after that I'll look at moving `/user/apt/` into `user/installing-dependencies/` entirely, and rewriting for clarity.

@BanzaiMan @MariadeAnton thoughts?

**Comment by BanzaiMan** [comment]
@plaindocs :+1: on both points.
