### ISSUE TITLE
Add a note about `after_script:` effect on build result when a step in it fails

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#338]
> From my YML file's "after-script:" block I was calling a shell script that invoked a ruby script. The ruby script would fail (exit code 1), but the build would still end with 0 and be classified as successful.
> ...
> Eventually I tried calling the script from within the "script:" block and this did the trick.

See the [following ticket](https://secure.helpscout.net/conversation/114189710/19293/) for context.

I think we should add a note about this in the [Breaking the Build section](http://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build).

**Comment by plaindocs** [comment]
@cotsog are you saying we need to make it more explicit that external scripts should be called in `script:` not `after-script:` ?

Or are you saying that external scripts called in 

"When any of the steps in the before_install, install or before_script stages fails with a non-zero exit code, the build is marked as errored." 

do NOT make the build step return an error code?

**Comment by cotsog** [comment]
@plaindocs: Sorry for the delay and for not being more clear.

What I meant is we should add a note that a failing command in `after_script:` won't affect the build result i.e. a command returning a non-zero exit code in `after_script` won't fail the build.

Does this makes more sense now? Let me know if not.

Thanks!
