### ISSUE TITLE
[ci skip] for the build matrix

### ISSUE THREAD

**Issue by tarekziade** [travis-ci/docs-travis-ci-com#342]
it would be nice to be able to skip some of the builds when we change for example only the docs.

e.g. I have a build that builds the docs and validates it, but I want to skip the other builds that run tests on the code.

**Comment by roidrage** [comment]
Thanks for opening this issue, but this is the issue tracker for our docs. Feature requests should go to https://github.com/travis-ci/travis-ci

**Comment by tarekziade** [comment]
oops sorry
