### ISSUE TITLE
Mention how to install and use Ruby on non-Ruby build images

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#348]
See this [ticket](https://secure.helpscout.net/conversation/116727410/19576/) for really detailed context.

The idea is the user was confused why the `rvm:` section in his `.travis.yml` file was not taking into account in his Elixir build image.

I think it would be nice to mention the recipe somewhere e.g. either a note in the [Ruby language page](http://docs.travis-ci.com/user/languages/ruby/) or in a new section that could be titled: How to install other language runtimes.

**Comment by plaindocs** [comment]
OK, so the way to install languages not included in a particular image is to do it in `before_install`?

I don't think this is Ruby specific at all, so will probably add it to the build environment somewhere, and link it from FAQ or something.
