### ISSUE TITLE
Update Settings UI image on Environment Variables page

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#350]
This [image](http://docs.travis-ci.com/images/settings-env-vars.png) is outdated:

![image](https://cloud.githubusercontent.com/assets/149366/9667604/bbbbae92-524a-11e5-94e1-68562767ae94.png)

It should be updated with a new screenshot.

It's on the `Environment Variable` page > `Defining Variables in Repository Settings` section.

URL is http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by MariadeAnton** [comment]
![image](https://cloud.githubusercontent.com/assets/3729517/9681513/e5d27fd0-52fe-11e5-8eb3-62b0a6e72f91.png)
Hey @plaindocs - here's a recent screenshot!
