### ISSUE TITLE
Improve documentation on headless browser testing

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#354]
See [#19846](https://secure.helpscout.net/conversation/118835080/19846/#thread-308512897).

The customer suggested we improve the documentation about setuping `xvfb`:

http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)

**Comment by MariadeAnton** [comment]
Hey @plaindocs! 
Actually this one refers to http://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server 

I think user was confused because this part is also needed:

```
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
````

to run headless tests without starting a web server after that.

**Comment by plaindocs** [comment]
Yes, I see the problem. Thanks.

**Comment by plaindocs** [comment]
@cotsog @MariadeAnton does either of you have a simple example using Firefox but not using a webserver? I think that might be a good thing to add.

Other feedback welcome.

**Comment by MariadeAnton** [comment]
I do not have a simple example using Firefox but not using a webserver. @cotsog, do you?

**Comment by ankon** [comment]
This PR un-did #311 completely, and it is not clear why one should manually start the server, if `xvfb-run` works just as well -- and considerably easier.

As this PR is still open, maybe someone involved that can see the original issue could shed a bit of light on what actually was the problem?

FWIW: I'm trying to debug issues where Xvfb reports errors when starting, but would like to avoid to switch from xvfb-run to this magic if possible.

**Comment by davehunt** [comment]
Both Chrome and Firefox now natively support headless mode. See #1538 for the documentation of Firefox, and there's already documentation for Chrome.

**Comment by MariadeAnton** [comment]
Thanks so much for the help, @davehunt! We're all set now with Firefox too 😊 

For `xvfb` - there's a PR and review on the works at https://github.com/travis-ci/docs-travis-ci-com/pull/1206 - @ankon, please feel free to take a look 👀  there and let us know what you think!
