### ISSUE TITLE
Improve Gradle caching documentation

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#358]
Gradle downloaded dependencies caching has some quirks that should be documented. Indeed you need to delete the changing lock file in order to not reupload the cache after every build.

Here is what you should put in your .travis.yml file:

````
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
````

**Comment by jamespedwards42** [comment]
Thanks @cotsog . Was looking everywhere for info on this.

**Comment by elincoln** [comment]
Also add to those docs: if you use a Gradle wrapper (e.g. for Android), consider caching the wrapper download.  Complete example below:  
```
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
```

**Comment by plaindocs** [comment]
@cotsog and @elincoln any possible downsides to lazily leaving the wrapper line in for Java and Groovy as well as Android?
