### ISSUE TITLE
Mention `--user` option for `pip install`

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/docs-travis-ci-com#361]
`pip install` by default installs things to `/usr/local` which requires `sudo` on our Docker based infrastructure.

In order to work around that limitation people can use `pip install --user` instead, which will install things to the home directory.

**Comment by plaindocs** [comment]
So if there is a `requirements.txt` in a Python project, the contents will be installed *as if* ` pip install -r requirements.txt` was run.

But on a the docker based infrastructure you need to explicitly use 

`install: pip install --user -r requirements.txt`

correct?
