### ISSUE TITLE
defining "node" or "stable" as a nodejs version fails

### ISSUE THREAD

**Issue by hennr** [travis-ci/docs-travis-ci-com#362]
The doc at http://docs.travis-ci.com/user/languages/javascript-with-nodejs/ reads:

"Specifying node or stable will run using the latest stable Node.js release and specifying iojs will run using the latest stable io.js release."

Neither defining "node" nor "stable" as a nodejs version works for me. Defining "iojs" or "0.12" does work well.
Am I missing something or is the doc simply wrong?

**Comment by plaindocs** [comment]
All of these seem to work fine for me.

```
language: node_js
node_js:
      - "0.12"
      - "stable"
      - "node"
```

**Comment by hennr** [comment]
That snippet does at least not validate here:
https://lint.travis-ci.org/

It says:
in node_js section: value stable is not a valid version
in node_js section: value node is not a valid version

**Comment by BanzaiMan** [comment]
@hennr Thanks for opening the issue. The linter needs to be updated to recognize these values. Do you mind opening a new issue at https://github.com/travis-ci/travis-ci/issues/new?

**Comment by hennr** [comment]
Hi @BanzaiMan, I can open a new issue, no problem.
I wasn't only checking the linter though but tried to use the config with "stable" and "node" as a version which did not succeed either.
Do you have that config working somewhere?

**Comment by hennr** [comment]
I rechecked this config and it works nicely, only the linter then...
New issue is #4852

**Comment by StephanBijzitter** [comment]
Thanks for reporting this, while linting my configuration file I thought I was going crazy
