### ISSUE TITLE
Docs describe non-existent `travis setup bintray`

### ISSUE THREAD

**Issue by denisw** [travis-ci/docs-travis-ci-com#364]
[user/deployment/bintray.md](https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/deployment/bintray.md) says that the encryption of the Bintray API key could be done with the command `travis setup bintray`. However, this command does in fact not exist, and I couldn't find any trace of it having ever existed in the repository of the Travis CLI client.

**Comment by plaindocs** [comment]
I've removed the mention of `travis setup bintray`  while I investigate further. f979bbef4f3e327c7428177ae257c426e61d13d9

**Comment by MariadeAnton** [comment]
@plaindocs I believe `travis setup bintray` is not available, even thought bintray deployment is.

Taking as a reference the deployment providers listed as compatible at https://github.com/travis-ci/travis.rb#setup

**Comment by plaindocs** [comment]
I think we can close this. Thanks @denisw for bringing this to my attention.
