### ISSUE TITLE
Instructions for using apt addons do not work

### ISSUE THREAD

**Issue by mauritsvanrees** [travis-ci/docs-travis-ci-com#366]
This is about this page: https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/apt.md

Following the example, you run into validation errors. See this issue in travis-yaml:
https://github.com/travis-ci/travis-yaml/issues/58
The error you get from travis-lint is:
```
in addons section: unexpected key apt, dropping
```

I don't know if this is an issue in travis-lint or if the documentation is missing a line that somehow registers the apt addon.

**Comment by BanzaiMan** [comment]
This is an issue with the linter, which is pretty outdated right now. The addon works as described in the document. If it doesn't, please reopen this issue.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-yaml/pull/65 (which is also outdated) aims to fix that.

**Comment by mauritsvanrees** [comment]
It really fails on Travis, at least when last I tried it. See this build:
https://travis-ci.org/zestsoftware/zest.releaser/builds/77654728

The error you get there is:
```
ERROR: An error occured while trying to parse your .travis.yml file.
Please make sure that the file is valid YAML.
http://lint.travis-ci.org can check your .travis.yml.
The error was "did not find expected key while parsing a block mapping at line 8 column 3".
```

Or is it *only* working when you have `sudo : false' ` in there? I think I tried that, but I can try again.

**Comment by BanzaiMan** [comment]
@mauritsvanrees Your YAML file has a problem. https://github.com/zestsoftware/zest.releaser/blob/6c4a0b927855649d2c2b7c8c0ac916cbaa366a9a/.travis.yml#L15

**Comment by mauritsvanrees** [comment]
Oh man, how can I not have seen those two spaces? Trying it out now.

**Comment by mauritsvanrees** [comment]
You are right. I had removed the `before_install` which used to install stuff with apt, and replaced it with the apt addon, but I totally failed to notice that `before_install` did much more. Fixed now and Travis is running along fine now.

Well spotted. Thanks a lot!
