### ISSUE TITLE
options available to notify failed migrations during heroku deploys

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/docs-travis-ci-com#374]
@plaindocs would this fit in a troubleshooting section at http://docs.travis-ci.com/user/deployment/heroku/? Or maybe somewhere else?

When running db:migrate fails silently after deploys to [Heroku](http://docs.travis-ci.com/user/deployment/heroku/), it's useful to use a logging add-on services for the apps hosted on Heroku, like [Papertrail](https://elements.heroku.com/addons/papertrail) or [Logentries](https://elements.heroku.com/addons/logentries). 

These add-ons have email notification systems that can be triggered when certain string matches occur in your logs. 

A sample string to trigger the e-mail notification could be: 'this and all later migrations canceled' .

**Comment by kris-luminar** [comment]
@MariadeAnton I like this. Small refinement though:
~~When running db:migrate fails silently after deploys to Heroku~~
Currently, running `rake db:migrate` after deploys to [Heroku](http://docs.travis-ci.com/user/deployment/heroku/) doesn't trigger Travis's email notifications. If you need to be notified when these fail, it's useful to use a logging add-on services for the apps hosted on Heroku, like [Papertrail](https://elements.heroku.com/addons/papertrail) or [Logentries](https://elements.heroku.com/addons/logentries).
+1
