### ISSUE TITLE
Appfog redirect loop broke builds

### ISSUE THREAD

**Issue by tripleee** [travis-ci/docs-travis-ci-com#384]
My [recent pull request](https://github.com/travis-ci/docs-travis-ci-com/pull/383) was marked as a [failure](https://travis-ci.org/travis-ci/docs-travis-ci-com/builds/85287434) because of this:

    Checking 438 external links...
    Ran on 126 files!
    - ./_site/user/deployment/appfog/index.html
    * External link https://www.appfog.com/ failed: 302 Number of redirects hit maximum amount
    rake aborted!
    HTML-Proofer found 1 failure!

The failing link (obviously) wasn't introduced by my diff, so should not cause my pull request to be rejected. (There's [another one in the queue](https://github.com/travis-ci/docs-travis-ci-com/pull/382) which seems to be affected by the same problem, too.)

**Comment by plaindocs** [comment]
Yep, I'm aware of that particular link issue. I'll look into this and the PR. Thanks!
