### ISSUE TITLE
Trusty beta: Mention mysql 5.5 client is installed

### ISSUE THREAD

**Issue by edmorley** [travis-ci/docs-travis-ci-com#396]
The docs say mysql isn't available:
http://docs.travis-ci.com/user/trusty-ci-environment/#Data-Stores

However mysql 5.5 is installed by default:
```
mysql --version
mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3
```
(https://travis-ci.org/mozilla/treeherder/builds/86627226#L54)

Thanks :-)

**Comment by blaxter** [comment]
Actually that's the client, not the server (which is not installed). If you try to include mysql service you will get the following error:

    $ sudo service mysql start

    mysql: unrecognized service

As expected.

**Comment by edmorley** [comment]
> Actually that's the client, not the server (which is not installed)

Ah that makes sense, thank you :-)
Is it worth mentioning in the docs that the client is installed?

**Comment by BanzaiMan** [comment]
Sorry for the delay. We are not providing MySQL at the moment. I've removed the mention of MySQL with https://github.com/travis-ci/docs-travis-ci-com/commit/d71108826c0de8387ce57c5c0519c7bce08e5cac.

**Comment by BanzaiMan** [comment]
I'm closing this for now; without the server locally, I am not sure mentioning the client is of much use.

**Comment by plaindocs** [comment]
Thanks for picking that up @BanzaiMan
