### ISSUE TITLE
Include info about the shell builds run under.

### ISSUE THREAD

**Issue by carlad** [travis-ci/docs-travis-ci-com#418]
A user contacted support with the following request:

> The docs at http://docs.travis-ci.com/user/ci-environment/ are very useful, but they are missing one important thing. You don't specify the shell which our Travis scripts run under! I assume it's bash, because you mention ~/.bashrc. Could you list the version as well?

I'm not sure if we need to add any of this info. Listing the version might not be wise as the version of bash used could change. It's also possible for a user to add `echo $BASH_VERSION` to their `travis.yml` if they want the bash version listed in their build log.

**Comment by BanzaiMan** [comment]
This will be added in the "Build system information" fold on the next build image rollout. https://github.com/travis-ci/system_info/commit/72e912685f456d5e56bc28ac0a6999b215c67111

Adding a new environment variable seems unnecessary.

`bash` is explicitly mentioned in a couple of places, but it is a good idea to add mentions at relevant places.
