### ISSUE TITLE
Running MongoDB service in container based infrastructure

### ISSUE THREAD

**Issue by stremlenye** [travis-ci/docs-travis-ci-com#430]
I have such build definition:
```yaml
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
services:
  - mongodb
```
and seems like tests have no chance to access mongo service on a url "mongodb://127.0.0.1:27017" as far as log include such text:
```sh
$ sudo service mongodb start
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
```

**Comment by BanzaiMan** [comment]
Is this a doc issue? Shouldn't it go to https://github.com/travis-ci/travis-ci/issues?

**Comment by stremlenye** [comment]
Probably – docs also don't help with it :)
But thank you for notice – I'll move it to the repo you've suggested.
