### ISSUE TITLE
Mention "push builds" needs to be enabled to populate the cache on an upstream branch

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#433]
With a development workflow where "push builds" are disabled and caching is used, the cache for the upstream branch (where all PRs are merged) won't be populated hence the builds on that branch won't have the speedup caching is supposed to lead to.

**Comment by plaindocs** [comment]
@cotsog could you give me some more info here?

If you disable Build Pushes, you would only build when triggered manually through the web? So wouldn't you just have a "slower" cache?

**Comment by MariadeAnton** [comment]
Closing this in favour of https://github.com/travis-ci/docs-travis-ci-com/issues/416, as there's a user subscribed.
