### ISSUE TITLE
Webhook notification doc inconsistent with actual behavior

### ISSUE THREAD

**Issue by rickypai** [travis-ci/docs-travis-ci-com#434]
According to http://docs.travis-ci.com/user/notifications/#Webhook-notification, notification are always sent on start by default (`on_start: [always|never|change] # default: always`), however, we weren't getting any start notifications from our enterprise travis until I set `on_start: always`. I'd just make a PR but I'm not sure what the actual default is.

**Comment by joshk** [comment]
Hi @rickypai 

Thanks for reporting this. This will be fixed in the next release of Travis CI Enterprise.

**Comment by MariadeAnton** [comment]
Has this been fixed on Travis CI enterprise already?
