### ISSUE TITLE
Please describe how to connect to push the coverage results to Coveralls

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [travis-ci/docs-travis-ci-com#446]
Hi,

You have example of "Using Code Climate with Travis CI", I would like to have similar for Coveralls.
If you need more specific use case, I'm using Python code.

Thanks,
Velizar

**Comment by MariadeAnton** [comment]
@VelizarVESSELINOV thank you! 

Do you have an example build using Coveralls for us to document? Or is that exactly what you're looking for?

**Comment by MariadeAnton** [comment]
I'm closing this one out for now - if anyone wants to add/clarify any more info about Coveralls to work on this, please feel free to add a comment here!
