### ISSUE TITLE
[Perl 6 Docs] Improve Sample .travis.yml File

### ISSUE THREAD

**Issue by zoffixznet** [travis-ci/docs-travis-ci-com#480]
The .travis.yml file offered on Perl 6 setup page (https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/languages/perl6.md) can be improved.

As a source to pick from, I present https://github.com/ugexe/P6TCI

Ugexe's version provides `--ll-exception`` on testing as well as asks panda to send test reports.

**Comment by BanzaiMan** [comment]
Thanks. We welcome your PR!

**Comment by BanzaiMan** [comment]
If you have suggestions, please open a PR. Thank you!
