### ISSUE TITLE
Document TRAVIS_TEST_RESULT in environment variable list

### ISSUE THREAD

**Issue by glenjamin** [travis-ci/docs-travis-ci-com#508]
This variable is mentioned in https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle and https://blog.travis-ci.com/after_script_behavior_changes/

It's not listed on https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

It would be great to get this included - including the fact that it's available in the `scripts` section, and shows the result so far.

**Comment by blueyed** [comment]
It is listed on https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables by now, but the documentation does not cover that it can be accessed in the `scripts` section, and shows the result so far.
