### ISSUE TITLE
Should Code Climate repo token be encrypted?

### ISSUE THREAD

**Issue by afeld** [travis-ci/docs-travis-ci-com#525]
On the [Code Climate instructions](https://docs.travis-ci.com/user/code-climate/), the examples show putting the `repo_token` directly in the `.travis.yml`. Since this token presumably gives write access to the test coverage on Code Climate, this seems like it's not a good idea for open source repositories...right? Seems like the instructions should be changed to [use a `secure` field](https://coderwall.com/p/5mtq6q/encrypt-your-code-climate-repo-token-for-public-repositories-on-travis-ci), or set this token via an environment variable.

Worth noting, Code Climate gives the same advice at the bottom of their Test Coverage setup page:

![screen_shot_2016-03-15_at_5_16_06_pm](https://cloud.githubusercontent.com/assets/86842/13794351/c88a3f42-ead1-11e5-89d3-227ad135e467.png)

Thoughts?

/cc @mrb @davidebest

**Comment by plaindocs** [comment]
Code climate docs are now hosted by Code Climate.

**Comment by afeld** [comment]
Ok, submitted the suggestion there. Thanks!
