### ISSUE TITLE
Add web UI terms

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#538]
A page listing settings available in the UI would make these things easier to find. "Build pushes" for example.

**Comment by plaindocs** [comment]
* `Sync Account` button.
* `Build only if .travis.yml is present` button.
* `Limit concurrent jobs` button.
* `Build pushes` button. 
* `Build pull requests` button.

Environment variables.

Also clicking on the button text flips the button, which is annoying to me (but probably pretty niche) and clicking cache settings produces "There was an error while loading data." (presumably cos there are no caches, but still not a nice message)

Am I missing any?

**Comment by MariadeAnton** [comment]
I'd add the options available in *More Options*:

![image](https://cloud.githubusercontent.com/assets/3729517/14242007/20cdd632-fa4f-11e5-8a35-fcc633aa5a9a.png)


For .com repos there's an extra field for SSH Keys: https://docs.travis-ci.com/user/private-dependencies/#Using-an-existing-key

![image](https://cloud.githubusercontent.com/assets/3729517/14241975/f648f284-fa4e-11e5-9c40-dc6a7f518998.png)

thoughts?

**Comment by plaindocs** [comment]
I was getting the error I mentioned above when clicking Caches, but I saw something flash past in slack that people were working on that?

**Comment by MariadeAnton** [comment]
@plaindocs, that's right. There was an issue with caches that caused the error message "There was an error while loading data.": https://github.com/travis-ci/travis-ci/issues/5855

This is the correct message that will be shown when there are no caches:

![image](https://cloud.githubusercontent.com/assets/3729517/14421568/b228d4a0-ffd2-11e5-9f2f-7eaae5e4d0e0.png)

**Comment by MariadeAnton** [comment]
Just following up on this, ping me if you need any more info, @plaindocs!
