### ISSUE TITLE
Document GitHub Releases provider's `overwrite` option in docs

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/docs-travis-ci-com#543]
https://github.com/travis-ci/travis-ci/issues/5854#issuecomment-205431536

> [B]y default, we do not overwrite existing files. (I think this is a recent update described in https://github.com/travis-ci/dpl#github-releases but not in https://docs.travis-ci.com/user/deployment/releases).

**Comment by plaindocs** [comment]
@MariadeAnton wanna check if you're happy with that last commit (already merged) and close if so?

**Comment by MariadeAnton** [comment]
awesome! Thank you @plaindocs!
