### ISSUE TITLE
Link Travis Pro in TOC

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#544]
It seems this page:

https://docs.travis-ci.com/user/travis-pro

is not linked in the TOC and it contains interesting information about the permissions needed to do things on Travis CI.

Would it be possible to just link the page in the TOC or rather create a new "Permissions" page?

**Comment by plaindocs** [comment]
hey @cotsog I'll have a look at what we say about pro permissions here. We do cover pro in 

https://docs.travis-ci.com/user/github-oauth-scopes/

as well.

**Comment by MariadeAnton** [comment]
Hi @cotsog,

We recently improved our TOC and I believe this should be fixed now here:

![image](https://cloud.githubusercontent.com/assets/3729517/16583910/eff74db0-42b8-11e6-99d7-f18c55bbac4e.png)

Please feel free to reopen if there's something yet missing!

**Comment by cotsog** [comment]
Awesome! Thank you!
