### ISSUE TITLE
Unclear about how to enabled firefox

### ISSUE THREAD

**Issue by marcoscaceres** [travis-ci/docs-travis-ci-com#559]
[The docs](https://github.com/travis-ci/docs-travis-ci-com/blob/fc72429d3b06558f97ea1172098f609ac805ba32/user/firefox.md) are unclear about how to enable firefox because of the text " (as part of the before_install stage)"

That reads like:

```
before_install:
  addons:
    firefox: "39.0"
```

Or is it just?:
```
addons:
  firefox: "39.0"
```

**Comment by BanzaiMan** [comment]
The latter. `addons` should go to the top level. Did you see any example in the docs that has the former form?

**Comment by marcoscaceres** [comment]
@BanzaiMan, I got that, but I landed on the help page from Google. It would be great to have full context to quickly be able to drop in and out of the documentation (and just copy and paste). I had to go and search for similar examples in GitHub Search to answer my query. 

Doing trial/error on travis is also not ideal, because it takes at least a minute to spin up an instance. 

So, the docs should remove (or move) "as part of the before_install stage" because that's confusing... and should instead just say "Just add the following to your .travis.yml file:".

**Comment by BanzaiMan** [comment]
Ah, thanks for the feedback. I see how that is confusing.

**Comment by BanzaiMan** [comment]
@plaindocs Could you take a look?

**Comment by marcoscaceres** [comment]
Send a PR with some proposed text https://github.com/travis-ci/docs-travis-ci-com/pull/560

**Comment by plaindocs** [comment]
Cheers @marcoscaceres and @BanzaiMan I'll take a look.
