### ISSUE TITLE
Mention custom_json for AWS OpsWorks deployment

### ISSUE THREAD

**Issue by joecorcoran** [travis-ci/docs-travis-ci-com#594]
https://github.com/travis-ci/dpl#opsworks

Maybe @BanzaiMan has an opinion on whether this should be public or not? I'm not familiar with OpsWorks generally but I just stumbled across it when dealing with [this support ticket](https://secure.helpscout.net/conversation/206125512/29530/).

**Comment by BanzaiMan** [comment]
In general, in docs, we can lag behind what's in the dpl documentation. We should do better in keeping up.

**Comment by plaindocs** [comment]
If you add a doc ticket when merging the DPL feature in and assign it to me I'll try to make sure I get to it. Working on reducing doc ticket delays generally. 

Alternatively, throw some relevant text into a doc PR and I'll review it.

**Comment by plaindocs** [comment]
@joecorcoran We do have https://docs.travis-ci.com/user/deployment/opsworks is the AWS sorting misleading do you think?
