### ISSUE TITLE
Problem with suggested Gradle caching configuration

### ISSUE THREAD

**Issue by himikof** [travis-ci/docs-travis-ci-com#609]
We are seeing Gradle cache (configured according to #358) rebuilt on every build in [intellij-rust/intellij-rust](https://travis-ci.org/intellij-rust/intellij-rust) repository. The problem seems to be the `$HOME/.gradle/caches/2.13/plugin-resolution/cache.properties.lock` file.

Maybe removing of this file (or, possibly, all lock files) should be added to the `before_cache` section in the recommended configuration?

**Comment by matklad** [comment]
To be more precise, every build ends with

```
64.77s
change detected (content changed, file is created, or file is deleted):
/home/travis/.gradle/caches/2.13/plugin-resolution/cache.properties.lock
changes detected, packing new archive
.
.
.
.
.
.
.
uploading archive
```

**Comment by matklad** [comment]
Quick experimenting showed (`travis-cache` branch) that simply removing one more lock is not enough.

Will try 

```
  - rm -f $HOME/.gradle/caches/*/plugin-resolution
```
