### ISSUE TITLE
Update Cache documentation regarding PRs

### ISSUE THREAD

**Issue by carlad** [travis-ci/docs-travis-ci-com#622]
We need to add information to clarify the logic behind how caches are created and stored for PRs.

https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches. 

Remove the bullet point " - Pull requests use the cache of the target of the pull request."

Add the following text underneath the bullet list: 

"Caches for a Pull Request

When we run a build for a PR with caching turned on the caching logic will check for 3 caches: 1) for the PR itself, 2) for the PR's target branch, and 3) for the repository's default branch (master).

If it cannot find a suitable cache, it will install things from scratch, uploading a new cache (for the PR itself) at the very end of the build.

This is a known shortcoming pattern with caches on PRs and "build pushes" turned off: Neither the master branch cache nor the target branch cache will ever be created because these are builds for git push events."

**Comment by plaindocs** [comment]
@carlad are those three in order? What happens if there are multiple caches? Or would that not matter?

**Comment by carlad** [comment]
@svenfuchs can you take a look at Sam's question above...

**Comment by svenfuchs** [comment]
@plaindocs yes, it checks these three caches in this order, and will use the first one that it can find
