### ISSUE TITLE
Link http://maven.travis-ci.org is broken

### ISSUE THREAD

**Issue by stonio** [travis-ci/docs-travis-ci-com#627]
Link http://maven.travis-ci.org mentioned in  page [The Build Environment](https://docs.travis-ci.com/user/ci-environment/#Maven-version) is broken.

**Comment by plaindocs** [comment]
@BanzaiMan know anything about this?

**Comment by BanzaiMan** [comment]
I don't know anything about it. The mention goes all the way back to https://github.com/travis-ci/docs-travis-ci-com/commit/66994794b8259c4f448293d8255171f61c5ba088. I think we should just remove this.

**Comment by plaindocs** [comment]
Thanks @stonio !
