### ISSUE TITLE
Deploy System Info To the Docs?

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#629]
As a fairly reasonable thing to implement, if we were to run a build on each type of infrastructure, for each language, and deploy the resulting https://github.com/travis-ci/system-info/ file to somewhere, we could then include them in the relevant Language doc page, as a tab selection code block (or whatever https://jqueryui.com/tabs/ type thing, probably folded initially).

Thoughts? Would it be useful? @MariadeAnton @BanzaiMan @anarosas @lislis

**Comment by lislis** [comment]
Interesting. I didn't know about `system-info`. Is this live somewhere? Is there more documentation/ information about this?
Aside from that, that would be a very cool thing to implement/ have around and with Cron Jobs that's even easier. 
Big 👍

**Comment by plaindocs** [comment]
It writes the file `/usr/share/travis/system_info`, which `travis-build` finds and displays in the "Build System Info" fold in the build logs.

**Comment by BanzaiMan** [comment]
@lislis https://github.com/travis-ci/system-info/ is a utility that gets run during the build image provisioning time. It collects certain information about the build image, and puts it in a file, which `travis-build` displays at build execution time in "Build System Information" fold.

The file is only available on the build image; it is not stored anywhere yet. The rationale at the time for not including this in the docs was that it can get stale. The build image will **always** have the most accurate information.

**Comment by plaindocs** [comment]
Yeah, but if we're generating it daily...

**Comment by BanzaiMan** [comment]
@plaindocs I discourage you from doing that. These files do not change often enough to warrant such a maneuver.

What we need to do is to grab the existing files now, then automate the process to update those files (wherever they end up) when the new build images go live.

**Comment by plaindocs** [comment]
@BanzaiMan :-) understood. I'm not really concerned about *how* we implement it, but I would really like to have that info displayed in place in the docs. 

If we can easily grab the files once when the image goes live great! If we can't and we can put something 'ugly' in place easily until we have a better way, I'd be ok with that also :-p.
