### ISSUE TITLE
Document required GitHub permissions to access the billing page for an organization

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#678]
We have a lot of support requests regarding how to access the [billing page](https://billing.travis-ci.com) and it's a bit tricky and not documented at this time if I'm correct.

In order to access the billing page for an organization, a user needs to have the Administrator rights to at least one of the organization's repositories.

This information could probably be put under a Billing FAQ section or under [Travis Pro](https://docs.travis-ci.com/user/travis-pro/), WDYT?

Thank you!

**Comment by acnagy** [comment]
Completely agree! I was discussing a similar issue question with someone just on Friday. 

I like the idea of including a billing FAQ age under [Travis Pro](https://docs.travis-ci.com/user/travis-pro/) as you mentioned, but I could also see making it more generic to reflect ownership + permissions in general. For example, questions like "who sets up Travis for an organization's repository?", regardless if it's a pro or open-source project, fits into a similar category. Maybe we should put a Billing-specific FAQ on [Travis Pro](https://docs.travis-ci.com/user/travis-pro/) (and include a shout-out to upgraded open-source plans), and then build an additional page/sections somewhere else?

**Comment by plaindocs** [comment]
@acnagy do you want to get me a bullet list of billing + permissions things you'd like me to cover (if they come with answers even better :-p) and I'll figure out where to put them?

@cotsog I'll add in the Billing page of course.

**Comment by acnagy** [comment]
My apologies for completely losing track of this one! I'm thinking our new `billing` page should include info on the following: 

## .com: 
 - Where to sign-up: https://travis-ci.com/plans, methods of payment accepted (credit card)
 - FAQs from billing page
 - Contact email (currently success@travis-ci.com,) for billing questions (e.g. if you expect to need more concurrency, if there is an issue with billing, etc.)
- where to manage subscription: http://billing.travis-ci.com/
- education subscriptions: http://education.travis-ci.com/

### .org
 - How many concurrent jobs are allowed for standard oss subscription (5) 
 - Contact email (currently success@travis-ci.com) for billing questions (e.g. if you expect to need more concurrency) 

### permissions
 - Who should set up Travis for an org? org owner/admin; What to do if you need to move a user subscription to an org, or vice-versa: contact support@travis-ci.com
 - Who can edit billing info? admins
 - Do we build forks? nope, well, not at least on the same subscription (yes, you can setup your own trial/subscription for a fork)
 - Can you get a subscription for a single repo, separately? Subscriptions are org- or user-level

Ok! That's it for my ideas now - will come back and edit if I think of anything else. @cotsog Can you think of anything to add?

**Comment by MariadeAnton** [comment]
From previous chats, the page could also include information about: 

* Educational accounts

* Trial

**Comment by bopoh13** [comment]
I already registered for **.org**, now I received an invitation from **.com**.
What is the difference between these sites?
