### ISSUE TITLE
Addition to the "My Pull Request isn't being built" section

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#690]
[We had a case recently](https://secure.helpscout.net/conversation/234307757/32789/?folderId=30784) where a user was not getting builds on his PRs. The cause was that the GitHub webhook of his repo wasn't registered to listen to pull request events. This could be fixed from our side but it would be interesting to investigate if this can be fixed by the user e.g. on the GitHub website.

Hence, I'm opening this issue to add this information in the [Building Pull Requests page](https://docs.travis-ci.com/user/pull-requests) if it's doable.

Thanks!

**Comment by MariadeAnton** [comment]
@cotsog thanks for opening this issue! 

Do you happen to know how the webhook was created?

**Comment by cotsog** [comment]
@MariadeAnton: I've looked some more and I don't think it's possible via the GitHub web UI. Internally, we are using [this API](https://developer.github.com/v3/repos/hooks/).
