### ISSUE TITLE
Consider adding a note about using the -r/--repository option when encrypting environment variables

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#691]
We often tell the customers to add `-r repo` or `--repository repo` to their `travis encrypt` command when they are having troubles encrypting their environment variables. It might be a bug in our CLI but it could also be caused by a user mistake e.g. not running it in the right directory locally, `--org` vs `--pro`.

To mitigate these issues and perhaps reduce support a bit, I suggest we mention the usage of `-r`/`--repository` option when calling `travis encrypt`.

This information could be mentioned on [the environment variables page](https://docs.travis-ci.com/user/environment-variables/) for example.

Open to discuss further.

Thanks!

**Comment by plaindocs** [comment]
Hi @cotsog - any chance of a follow up on this?
