### ISSUE TITLE
Update PostgreSQL version installed by default 

### ISSUE THREAD

**Issue by anarosas** [travis-ci/docs-travis-ci-com#696]
We should update the Postgres version that is now installed by default to 9.5

https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version

HelpScout ticket: https://secure.helpscout.net/conversation/238091774/33434/?folderId=30784

**Comment by MariadeAnton** [comment]
Related: https://github.com/travis-ci/travis-ci/issues/4264

**Comment by MariadeAnton** [comment]
This is now live! see: https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version
