### ISSUE TITLE
Slack notifications also accept template

### ISSUE THREAD

**Issue by joepvd** [travis-ci/docs-travis-ci-com#707]
https://github.com/travis-ci/travis-tasks/blob/b85f0c2672e373bfafd31430ad5dbb3a6fabe5a8/lib/travis/addons/slack/task.rb#L64

This is currently not in documentation.

**Comment by plaindocs** [comment]
I assume same template as for IRC? 
https://docs.travis-ci.com/user/notifications/#IRC-notification

**Comment by plaindocs** [comment]
Without digging through a lot of unfamiliar code I'm not sure if all of these addons use the same template. The hipchat one mentions an `html` option that the irc one does not.
