### ISSUE TITLE
Possible typo in Go's dependency management docs

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#724]
Is it possible that the following phrase [in Go's dependency management docs](https://docs.travis-ci.com/user/languages/go/#Dependency-Management) should say `make` instead of `true`?

> If any of the following files are present, the default install step will be simply `true`: ...

Asking for a friend who Go like @meatballhat or @henrikhodne.

Thanks!

**Comment by plaindocs** [comment]
Yeah, that is pretty confusing. I don't know Go, but uploading a go project with a Makefile should give us some info. 

brb

**Comment by plaindocs** [comment]
https://travis-ci.org/plaindocs/playing_with_travis/builds/158463022#L162

Looks like what that actually means, is the default install step is indeed `true` and then `make` is run after that ?

**Comment by henrikhodne** [comment]
That's correct, nothing (well, `true`, which is effectively nothing) will be run in the install step if you're using a Makefile. The reason being that we don't have a good guess for what to use to install dependencies if the standard go toolchain isn't used.

**Comment by plaindocs** [comment]
Just to confirm, `make` is run, because of the existence of the `Makefile`, but if none of those 4 files exist we don't guess?

**Comment by plaindocs** [comment]
Fixed in 79cdb813
