### ISSUE TITLE
Add notice about Cassandra  in Trusty image

### ISSUE THREAD

**Issue by anarosas** [travis-ci/docs-travis-ci-com#730]
We should add a notice about Cassandra, not being available in Trusty images here:
https://docs.travis-ci.com/user/database-setup/#Cassandra

the notice should be something like the message in this section:
https://docs.travis-ci.com/user/trusty-ci-environment/#Data-Stores

> services that are included with our Precise images are not included in the Trusty mega images but some may be added in the coming months, in the meantime install them manually if you need them

**Comment by MariadeAnton** [comment]
This would also apply to other services like MySQL, which we should add to: https://docs.travis-ci.com/user/trusty-ci-environment/#Data-Stores

possibly related to: https://github.com/travis-ci/docs-travis-ci-com/issues/702

**Comment by plaindocs** [comment]
Cassanda *is* now available on Trusty.
