### ISSUE TITLE
Could not authorize build request

### ISSUE THREAD

**Issue by kolpav** [travis-ci/docs-travis-ci-com#733]
My builds suddenly stopped working. I found nothing on google this is the error message I am getting ![this](https://cloud.githubusercontent.com/assets/19467143/18559958/db58240c-7b79-11e6-93e0-f909e7a4be5a.png)

**Comment by MariadeAnton** [comment]
Thanks for reporting, @kolpav!

First off, have you been able to figure this out already? If not, could you please send us an email at support@travis-ci.com ?

 "Could not authorize build request for ... " usually means that the account run out of trial builds or has not an active subscription on travis-ci.com 

We'll look into documenting the possible messages in the Requests page soon, thank you!

**Comment by kolpav** [comment]
You are right I have run out of trial builds and got confused by vague error message. Thank you

**Comment by jmichaelprobert** [comment]
@MariadeAnton - Just ran into this myself. A better message would be very helpful.

**Comment by bj97301** [comment]
Seriously please have better message...

**Comment by stevebauman** [comment]
Is it possible to transfer a subscription to an organization?

**Comment by muizzk** [comment]
@stevebauman please can you send the details of this to support@travis-ci.com and we can follow up on your reply. Thanks

**Comment by stevebauman** [comment]
You've fixed it - the subscription has been transferred. Thanks so much for your quick assistance @muizzk!

**Comment by khose** [comment]
It's 2020 and the message still shows: "Could not authorize build request for.." 4 years seems a reasonable time frame to fix an error message. I lost one day verifying token permissions and testing in other repos because of this.

**Comment by mustafa-travisci** [comment]
Hello @khose , it seems like you have run out of trial builds on your personal account. That is the reason you are getting this error message. Please reach us from support@travis-ci.com so that we can help you out! Thanks

**Comment by Xonshiz** [comment]
Was getting this message and stumbled upon this thread. I am on free subscription of Travis. The main culprit was that my repository was `private`. As soon as I made it `public`, the builds triggered just fine.

**Comment by tannerhallman** [comment]
This happened to me because I created an organization where I imported my repos but the organization didn't have any plan selected. I selected the free plan and the build started after another trigger.

**Comment by Verron** [comment]
> This happened to me because I created an organization where I imported my repos but the organization didn't have any plan selected. I selected the free plan and the build started after another trigger.

For anyone who comes here from google, this was the fix for me. 

If things were working prior to migrating from travis-ci.org to travis-ci.com and you get the error message `Could not authorize build request for`. Go to travis-ci.com (make sure it isn't travis-ci.org), Click User (top right) > Settings > Your Organization > Plan then choose your plan.

**Comment by biphasic** [comment]
For me selecting a plan for the organisation the repo belongs to (different than your personal plan) did the job.

**Comment by cdown** [comment]
> This happened to me because I created an organization where I imported my repos but the organization didn't have any plan selected.

This looks like a fairly serious, non-intuitive oversight for the .org to .com migration. I also found that the only error message I was getting was "Could not authorize build", and without this thread there would have been absolutely no way to know that no plan was selected.

**Comment by tannerhallman** [comment]
Absolutely agree. It almost caused me to give up!

**Comment by gerardnico** [comment]
I don't understand why you should select the free plan. If there is no plan chosen, just select the free plan. 

If you have an organization, you should select the free plan and select it on the next page one more time to select it effectively.

This is so confusing.

**Comment by zongzi531** [comment]
Why is there such a design, since I clicked "FREE", why is there such a situation as expired?
