### ISSUE TITLE
Running-a-Container-Based-Docker-Image-Locally docs

### ISSUE THREAD

**Issue by leto** [travis-ci/docs-travis-ci-com#744]
I followed the directions at https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally but they don't quite work.

It says to `su - travis` and then git clone into / , but the travis user does not have permissions to do that. I got around this by cloning as root and then chown'ing. What is the preferred way to do this?

**Comment by plaindocs** [comment]
We've updated those docs so I'm closing this issue.
