### ISSUE TITLE
Upgrade default Ruby version

### ISSUE THREAD

**Issue by simonewebdesign** [travis-ci/docs-travis-ci-com#753]
As documented [here](https://github.com/travis-ci/docs-travis-ci-com/commit/94fb22598ddb4725c7791efc89923c6e12df2778#diff-2c3dac7b79331d19b6ec8e0d119c1e1eR71) it seems the default Ruby version is 1.9.3, which is [old and no longer supported](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/).

Would it be possible to change it?

**Comment by BanzaiMan** [comment]
We have plans to update the default Ruby to something newer, but there are many things that need to consider before that happens.

I'm closing this issue, though, because this is not a documentation issue. It belongs in https://github.com/travis-ci/travis-ci/issues.

**Comment by simonewebdesign** [comment]
Yeah, I wasn't sure where to open the issue — so many repositories!

Where can I track the progress on this?
