### ISSUE TITLE
Tags will not be built if multiple tags are pushed

### ISSUE THREAD

**Issue by joepvd** [travis-ci/docs-travis-ci-com#763]
Travis CI does not receive a webhook event when more than three commits are tagged. So if you do `git push --tags`, and more than three tags that are present locally, are not known on GitHub, Travis will not be told about any of those events, and the tagged commits will not be built.

https://github.com/travis-pro/team-teal/issues/1415

**Comment by MariadeAnton** [comment]
This has been documented as a note in https://docs.travis-ci.com/user/common-build-problems/#I-pushed-a-commit-and-can%E2%80%99t-find-its-corresponding-build 

Thanks so much, @joepvd !

**Comment by pvinis** [comment]
Documentation is not a fix or an explanation.
Why is that happening?
Who's fault is it?
Who could fix this?
Is there a suggested workaround?

**Comment by MariadeAnton** [comment]
Thanks, @pvinis!

If you push more than 3 tags at the same time, no create event will be triggered, as documented by GitHub here: https://developer.github.com/v3/activity/events/types/#createevent

The suggested workaround is to push tags individually or in blocks of 3 tops. If you notice this after pushing more than 3 tags at the same time, I'm afraid the only workaround is creating a new tag and pushing that one individually

@plaindocs would it be worth to complete our docs with the external reference to GitHub docs for completeness?

**Comment by pvinis** [comment]
Oh interesting. Thanks for the reference. I think it's important to at least say it's because of github and they way the hooks work, with a link, so people see that its something and not just travis not being "good enough".

The workaround makes sense. Thank you again.

**Comment by MariadeAnton** [comment]
Of course, thank you for the quick reply and pointing this out.
