### ISSUE TITLE
OS X to macOS

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#766]
In _all_ the docs! Right?

CC @aquaranto @meatballhat

**Comment by aquaranto** [comment]
Sounds like a great Scavenger Hunt 😀. 👍 from me. Any objections @MariadeAnton or @meatballhat?

**Comment by BanzaiMan** [comment]
To be really pedantic, macOS refers to 10.12 (and later), which is not yet deployed on our platform.

**Comment by plaindocs** [comment]
Pedantic in this context (and most of them here on docs-travis-ci-com) is AWESOME! 

So we don't actually need to retro fit this?

**Comment by BanzaiMan** [comment]
I am not quite sure, to be honest. However, Sierra support is imminent, so it is prudent to plan now, even if there is no immediate action to take.

I don't know if there is a single term that refers to all the 10.x releases at this point. Maybe we can say Mac throughout, after introducing the term "Mac" as (OS X or macOS).

**Comment by acnagy** [comment]
I vote using the new term once we have 10.12+ deployed ✋ Sounds good to me to switch to 'Mac' from 'OS X' as well, since as macOS becomes more common, it's going to get less and less correct sounding (even if the new name only references 10.12 and later)

**Comment by robertpeteuil** [comment]
There are many examples of Apple retroactively referencing earlier versions of OS X as MacOS.  

For example this marketing page states ["Peer-to-peer AirPlay requires a Mac (2012 or later) with macOS Yosemite or later..."](https://www.apple.com/ae/macbook/wireless/)

There is a summary of some of these statements in this thread on [stack exchange](https://apple.stackexchange.com/questions/256088/is-apple-changing-os-x-branding-to-macos-retroactively)
