### ISSUE TITLE
Contradiction regarding whether --retry=3 is in the default bundler command.

### ISSUE THREAD

**Issue by bardiharborow** [travis-ci/docs-travis-ci-com#768]
[user/common-build-problems.md](https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/common-build-problems.md):

> You can add the --retry option with the number of retries you'd like to use. _Note: this may become a default in the future on Travis CI._

[user/languages/ruby.md](https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/languages/ruby.md):

> The default command run by Travis CI is:
> bundle install --jobs=3 --retry=3

**Comment by plaindocs** [comment]
Thanks for picking up on hat! Fixed in the PR.
