### ISSUE TITLE
Document Ruby 2.3 Support

### ISSUE THREAD

**Issue by acnagy** [travis-ci/docs-travis-ci-com#776]
We have Ruby 2.3 on some infra (Trusty, sudo-enabled), but it appears nowhere in the docs. @cotsog did a nice test build to show: https://travis-ci.org/cotsog/travis_ci_prod_regular/jobs/170798730

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/docs-travis-ci-com/pull/767

**Comment by cotsog** [comment]
Was documented in https://github.com/travis-ci/docs-travis-ci-com/commit/1470f027d1d3e441561216c608aee9f519842a7b#diff-59341367ad69f7bd58902df32ee48600

See https://docs.travis-ci.com/user/reference/trusty/#Ruby-images.
