### ISSUE TITLE
Firefox addon documentation could mention how to use it when older Firefox already exists

### ISSUE THREAD

**Issue by backspace** [travis-ci/docs-travis-ci-com#797]
The [Firefox addon documentation](https://docs.travis-ci.com/user/firefox/) talks about how to install Firefox when a VM doesn’t already have it, but you can see someone in [this StackOverflow answer](http://stackoverflow.com/questions/34602565/install-latest-version-of-firefox-on-travis-and-run-with-protractor/34703838#34703838) using `$PATH`-wrangling to override the existing version with the new one:

```
echo "Extracting firefox and setting PATH variable..."
tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
export PATH="/tmp/firefox:$PATH"
echo "Using firefox version `firefox --version`"
```

This seems like a common enough scenario that it should be explicitly documented, or perhaps the process needs improving…?

**Comment by BanzaiMan** [comment]
The current wording is:

> Our 64-bit Linux VMs include a version of Firefox.
> 
> While Firefox is not pre-installed on OS X images, you can use this addon to set it up for use on your builds.

In addition, the SO answer is a bit misleading, because the addon takes care of `$PATH`. See https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/firefox.rb and the example build https://travis-ci.org/BanzaiMan/travis_production_test/builds/175875665#L180.

I don't think there is much to improve here.

**Comment by BanzaiMan** [comment]
Oh, this reminds me… There is a strange case of wrong Firefox selection https://github.com/travis-ci/travis-ci/issues/4649. That might be worth documenting.

**Comment by backspace** [comment]
I think the value of the `$PATH` change in the StackOverflow answer is that it places it at the beginning rather than the end, so it overrides the installed version.

I guess if there’s no explanation of what the addon actually does in the documentation, a link to the code would be helpful for people to see?

**Comment by plaindocs** [comment]
I'm not sure a link to the code is the right way to go here. If you think mentioning that the addon changes `$PATH` is worthwhile we can do so?

**Comment by backspace** [comment]
I don’t know, really. I see now after looking again that `$PATH` is only changed on macOS, not on Linux. So the manipulation of `$PATH` that was described in that StackOverflow answer makes sense, as presumably the `ln` will fail because Firefox is already present on Linux, keeping the old version as the one used by Protractor or Selenium.

I just think that if people are creating unofficial and possibly-outdated documentation via StackOverflow answers and I found that answer in my own attempt to answer a support email, it indicates a lack in the documentation. But if others don’t agree, we can just close this.

**Comment by plaindocs** [comment]
> I just think that if people are creating unofficial and possibly-outdated documentation via StackOverflow answers and I found that answer in my own attempt to answer a support email, it indicates a lack in the documentation. 

Agreed. But I'd much rather explain the issue than just throw in a code example of something that people think should 'just work'.

**Comment by BanzaiMan** [comment]
The `$PATH` manipulation on Linux is not necessary because it goes to `/usr/local/bin`, which is already on `$PATH`.

The same cannot be sad on the Mac, because `firefox` executable lives in `/Applications`.

**Comment by BanzaiMan** [comment]
With the addon, `firefox` correctly points to `/usr/local/bin/firefox` on Linux. https://travis-ci.org/BanzaiMan/travis_production_test/builds/175875665#L185

**Comment by backspace** [comment]
hmm, well I can’t explain then what happened with [this job](https://admin.travis-ci.com/job/56068693) where the person has `firefox: latest` but the Protractor logs show Firefox 31. Do you know why that might be happening?
