### ISSUE TITLE
Document new command to run on the keychain to make keys/certificates accessible on macOS Sierra

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#805]
More details available here: https://github.com/travis-ci/travis-ci/issues/6791#issuecomment-261071904.

Still waiting for the confirmation that it works for our customers.

@solarce suggested adding it under [Common Build Problems](https://docs.travis-ci.com/user/common-build-problems/).

@plaindocs, @MariadeAnton: thoughts?

**Comment by MariadeAnton** [comment]
@cotsog also, and as mentioned about the recommendation to now run xcodebuild instead of xctool, would it make sense to add a note on https://docs.travis-ci.com/user/languages/objective-c/ about how/when should we use it? e.g. versions > xcode8

**Comment by MariadeAnton** [comment]
@cotsog just a quick follow-up about code sign in macOS Sierra, is the latest comment the best solution? See https://github.com/travis-ci/travis-ci/issues/6791#issuecomment-265387673

Thanks!

**Comment by cotsog** [comment]
@MariadeAnton: unfortunately, it's not. This one is specific to Fastlane.

**Comment by jtroest** [comment]
So what is the Travis recommended workaround for this issue? I am completely stuck unable to code sign any apps in Travis at the moment.

**Comment by cotsog** [comment]
@jtroest: sorry for the troubles. A draft version of our documentation on how to fix this is available in this PR: https://github.com/travis-ci/docs-travis-ci-com/pull/914.

If it still doesn't work, could you send us an e-mail at support [at] travis-ci [dot] com? Please make sure to include the name of your repository and a link to a build log on travis-ci.org or travis-ci.com showing your latest attempt.

Thanks!

**Comment by cotsog** [comment]
https://github.com/travis-ci/docs-travis-ci-com/pull/914 was merged and is available here:

https://docs.travis-ci.com/user/common-build-problems/#Mac%3A-macOS-Sierra-(10.12)-Code-Signing-Errors
