### ISSUE TITLE
Adapt code climate integration doc to the ruby code climate test reporter 1.0

### ISSUE THREAD

**Issue by thegcat** [travis-ci/docs-travis-ci-com#810]
See https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions.

**Comment by plaindocs** [comment]
Closing this due to to #794 please reopen if you think that isn't correct.

**Comment by thegcat** [comment]
Oh, I had skimmed through open tickets but it seems I missed that one. That nails it, thanks!
