### ISSUE TITLE
A small typo in copy 

### ISSUE THREAD

**Issue by sgoldens** [travis-ci/docs-travis-ci-com#812]
Within the docs page for Building a Node.js project: [Using .nvmrc #](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Using-.nvmrc
)

I am guessing "nodjs" is a typo, probably meant to be "nodejs", "node_js" or "Node.js", from this sentence in the Using .nvmrc section:

> The .nvmrc file is only read when node_js key in your .travis.yml files does not specify a _**nodjs**_ version.

**Comment by plaindocs** [comment]
I reckon you're right. Looks like it should be straight "nodejs". Would you like to submit pull request to fix it?

**Comment by BanzaiMan** [comment]
It should be:

```
`node_js`
```

**Comment by plaindocs** [comment]
This has been fixed for a while now.
