### ISSUE TITLE
iOS Builds failing randomly

### ISSUE THREAD

**Issue by jgimenez** [travis-ci/docs-travis-ci-com#820]
Exactly the same code, once fails, once passes... could you please help me find the reason?

* https://travis-ci.org/bugfender/BugfenderSDK-iOS/builds/178298491
* https://travis-ci.org/bugfender/BugfenderSDK-iOS/builds/178307974

Thanks!

**Comment by plaindocs** [comment]
Hi Jordi, Thanks for reporting! Could you send these over to support@travis-ci.com? Our support team will be happy to take a look.
