### ISSUE TITLE
Add a note about not supporting Mercurial

### ISSUE THREAD

**Issue by anarosas** [travis-ci/docs-travis-ci-com#823]
We should add a note somewhere about Travis not supporting Mercurial
Maybe something like this, but for Mercurial? 
https://docs.travis-ci.com/user/customizing-the-build/#What-git-Repository-Providers-can-I-use

This comes as a request from https://secure.helpscout.net/conversation/280711111/44729/?folderId=30784

**Comment by MariadeAnton** [comment]
This was fixed on https://github.com/travis-ci/docs-travis-ci-com/pull/834 🎉
