### ISSUE TITLE
.travis.yml Key Reference

### ISSUE THREAD

**Issue by wheelerlaw** [travis-ci/docs-travis-ci-com#874]
Looking for a reference for all the possible keys in the `.travis.yml` and their possible values and what they do. This obviously has to exist, but I cannot locate it, and I've spent too long trying to find it.

**Comment by BanzaiMan** [comment]
Thanks for taking the time to open this issue. There is no comprehensive reference list at this time yet. We should have one.

**Comment by wheelerlaw** [comment]
I see, ok. Since you guys are effectively creating your own DSL, its only fair that a complete grammar be published. I can get the ball rolling on such, but I would just need to know where to get started on looking for the usages of the keys and their possible values.

**Comment by sxlijin** [comment]
If I'm not mistaken, this information is tucked away in [travis-build](https://github.com/travis-ci/travis-build), starting in [init.rb](https://github.com/travis-ci/travis-build/blob/master/init.rb) with a lot of information scattered throughout [lib/travis/build](https://github.com/travis-ci/travis-build/tree/master/lib/travis/build).
