### ISSUE TITLE
Missing deploy target documentation

### ISSUE THREAD

**Issue by joepvd** [travis-ci/docs-travis-ci-com#888]
The following deploy targets are [defined in the `dpl` deployment tool](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider) but are not documented:

* [x] [azure_webapps](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/azure_webapps.rb)
* [x] [bitballoon](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/bitballoon.rb)
* [x] [catalyze](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/catalyze.rb)
* [x] [chef_supermarket](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/chef_supermarket.rb)
* [x] [cloud_files](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/cloud_files.rb)
* [x] [cloud_foundry](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/cloud_foundry.rb)
* [x] [code_deploy](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/code_deploy.rb)
* [x] [divshot](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/divshot.rb)
* [x] [elastic_beanstalk](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/elastic_beanstalk.rb)
* [x] [engine_yard](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/engine_yard.rb)
* [x] [firebase](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/firebase.rb)
* [x] [gae](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/gae.rb)
* [x] [nodejitsu](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/nodejitsu.rb)
* [x] [ops_works](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/ops_works.rb)
* [x] [puppet_forge](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/puppet_forge.rb)
* [x] [scalingo](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/scalingo.rb)
* [ ] [transifex](https://github.com/travis-ci/dpl/tree/v1.8.27/lib/dpl/provider/transifex.rb)

**Comment by plaindocs** [comment]
Ouch!

**Comment by plaindocs** [comment]
* [] `generic` re https://github.com/travis-ci/docs-travis-ci-com/issues/910

**Comment by plaindocs** [comment]
* [ ] bluemix re #925

**Comment by plaindocs** [comment]
Cloud Files is listed under Rackspace Cloudfiles.

**Comment by plaindocs** [comment]
Clound Foundry under BlueMix  Cloud Foundry

**Comment by plaindocs** [comment]
Code Deploy under AWS Code Deply

**Comment by plaindocs** [comment]
Divshot no longer exists. https://github.com/travis-ci/dpl/issues/583

**Comment by plaindocs** [comment]
Kinda nice to see the situation is not quite as bad as we initially thought. :fireworks:

**Comment by plaindocs** [comment]
Engine yard is already documented.

**Comment by plaindocs** [comment]
Google App Engine is already documented.

**Comment by plaindocs** [comment]
Nodejitsu is no more, added a small note in Modulus.

**Comment by plaindocs** [comment]
Ops Works is listed under AWS OpsWorks.
