### ISSUE TITLE
yarn uses different cache dir

### ISSUE THREAD

**Issue by klaemo** [travis-ci/docs-travis-ci-com#893]
Hey there,

running `yarn cache dir` reveals that yarn uses `$HOME/.cache/yarn` for its cache on travis.
Enabling yarn caching on travis on the other hand caches `$HOME/.yarn-cache`
```yml
cache: yarn
```

I think either the documentation needs to be updated to reflect that users should set the cache like this:
```yml
cache:
  directories:
    - $HOME/.cache/yarn
```

Or, alternatively the behavior of the cache setting needs to be updated to actually cache `$HOME/.cache/yarn`.

**Comment by BanzaiMan** [comment]
This appears to be a recent change. https://github.com/yarnpkg/yarn/issues/2255

**Comment by plaindocs** [comment]
@BanzaiMan what is the best fix here? Leave as is till we update to a version of yarn using the new changes?
