### ISSUE TITLE
Update local testing instructions for Trusty images

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/docs-travis-ci-com#900]
https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally instructs to use images on quay.io, but they are only Precise images. The doc should be updated for Trusty.

**Comment by plaindocs** [comment]
This is kinda done - but also needs fixing up.

**Comment by BanzaiMan** [comment]
#1159 is the most recent PR.

**Comment by BanzaiMan** [comment]
I'm going to go ahead and merge this. We'll finesse content once we have it out.
