### ISSUE TITLE
Document `language: generic`

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/docs-travis-ci-com#910]
The only current mention of this is in multi-os doc.

This is worth mentioning either as a section the languages page, or a page of its own.

**Comment by acnagy** [comment]
There are a [few different ways](https://github.com/travis-ci/packer-templates/blob/master/cookbooks/travis_ci_connie/attributes/default.rb#L60-L67) to end up in the same place as `language: generic`. Is it worth listing them all?

**Comment by BanzaiMan** [comment]
@acnagy IMO, yes, all except for `__connie__`, which is an obscure implementation detail that is likely to change over time.

**Comment by hessam61** [comment]
Is there a difference between minimal and generic for language?  Any update on adding documentation for either of these languages? It seems that minimal is no longer supported, isa that correct?

**Comment by Wilfred** [comment]
Apparently there's `language: bash` too, according to [this comment](https://github.com/travis-ci/travis-ci/issues/5175#issuecomment-215016943). It's not clear if there's any advantage of using that.

**Comment by Wilfred** [comment]
OK, it looks like `bash` and `generic` are equivalent. See [this PR](https://github.com/travis-ci/travis-build/pull/306/files). [This PR](https://github.com/travis-ci/travis-yaml/pull/33/files) suggests that `sh` and `shell` are equivalent too.

[This comment](https://github.com/travis-ci/travis-ci/issues/2856#issuecomment-58609666) suggests that Ruby is the default if you don't use generic, so I imagine the build will be a little slower.

Finally, the only documentation mention of `generic` is [in this section of the multi-os docs](https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)), as mentioned above.

**Comment by MariadeAnton** [comment]
We've introduced a language tag switch and now `language: minimal` is available instead.
Using `language: minimal` in either container-based and fully virtualized infras, it comes with fewer pre-installed languages and services and more disk space.

As Anna mentioned, language: generic points to the same image as `language: bash`, `language: sh` and `language: shell`. 

As a first step we're updating our multiOS docs to reflect this here: https://github.com/travis-ci/docs-travis-ci-com/pull/1647

And we're working on documenting this option in our language and infrastructure reference docs.

Thanks much for your patience y'all!

**Comment by MariadeAnton** [comment]
As an extra note - this time claryfing `languague: generic`.

Using `language: generic` with our stable, Trusty image, will point to a complete image so that someone can use many/none programming language: 

https://github.com/travis-ci/packer-templates/blob/master/cookbooks/travis_ci_garnet/attributes/default.rb#L136-L151

**Comment by Wilfred** [comment]
@MariadeAnton just to clarify: is `bash` different from `minimal`, and if so, how?

**Comment by plaindocs** [comment]
Somewhat related to https://github.com/travis-ci/docs-travis-ci-com/issues/862

**Comment by MariadeAnton** [comment]
@Wilfred the image in which they run and default script commands run by Travis CI will be the same. 

The difference comes in with `language: generic` which points to our a larger image which contains more runtimes and services, and runs the same script as minimal - https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/generic.rb

https://github.com/travis-ci/travis-build/blob/master/lib/travis/build.rb#L41-L42

**Comment by edmorley** [comment]
Still relevant

**Comment by tooomm** [comment]
Can you please reopen or link me to the docs @BanzaiMan ?

**Comment by LondonAppDev** [comment]
I've just started using Travis CI and I was a bit confused by the choice of languages. I run all CI steps within docker containers, so I was looking for a `language` option with minimal dependencies to try and speed up the builds. 

After reading the [full list](https://docs.travis-ci.com/user/languages/) of languages (as defined [here](https://docs.travis-ci.com/user/getting-started/#selecting-a-different-programming-language)) I assumed it was not possible to run travis builds without dependencies for a specific language. 

After quite a bit of digging/search I found there is also `generic` and `bash`.

As a new user to travis I definitely feel it would be beneficial if there was a full list of `language` options in one place.

**Comment by DeeDeeG** [comment]
_For those coming here from search engines (Google, Yahoo DuckDuckGo...)_

The pull request #1989 by @plaindocs added documentation for this.

**See this page:** https://docs.travis-ci.com/user/languages/minimal-and-generic/

**Comment by dwijnand** [comment]
Would be nice if these were linked somehow in https://docs.travis-ci.com/user/languages/.  Took me a wild roundabout way to finally find that doc page.

**Comment by DeeDeeG** [comment]
I agree with @dwijnand. (I had meant to make a pull request for this, but I couldn't figure out exactly how to do it, so I gave up!)

**Comment by jabl** [comment]
So is the "language: generic" image a superset of all the various "language: foo" images, or is it somewhere in between minimal and the language-specific images?

In this case we're running tests in docker, but before firing up docker we're running a node-based dockerfile linter, so we need access to the "npm" tool to install it. Unfortunately "language: minimal" doesn't work because it doesn't have npm. So what is the best "language: " tag to choose here?

**Comment by G00fY2** [comment]
The documentation is also wrong about stating only `language:generic` has jvm support. Actually _trusty_ and _bionic_ have preinstalled jdk in `language:minimal`. If I am not totally thats because the recipe here: https://github.com/travis-ci/packer-templates/blob/master/cookbooks/travis_ci_ubuntu_1804_minimal/recipes/default.rb#L46
