### ISSUE TITLE
Select different build for chron jobs.

### ISSUE THREAD

**Issue by dlewissandy** [travis-ci/docs-travis-ci-com#921]
This issue is motivated by the desire to have fast integration builds that can be run for each pull request (e.g. running smoke tests and building only using the most recent compiler) and more exhaustive builds that run on chron jobs  ( more testing and larger build matrix ).   

Presently, both the cron and pull request triggered events utilize the same travis.yml file.     Although it is possible to conditionally execute tests by testing the TRAVIS_EVENT_TYPE environment variable, there does not appear the necessary syntax to conditionally include/exclude the jobs in the build matrix.    For example:

```
matrix:
    include:
        - os: osx
           event-type: [ chron ]
```

As an alternative to introducing additional syntax to the travis.yml file, the same objective could be achieved by allowing a user to select the yml file that they wish to execute for each chron job.

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue, but this is not a repository for requesting new features. Please use https://github.com/travis-ci/travis-ci/issues/ for that. (Be sure to search for existing issues as well.)

Thanks again.

**Comment by dlewissandy** [comment]
Thank you.   I added my feature request to the travis-ci issue board.
