### ISSUE TITLE
Add Swift as language guide

### ISSUE THREAD

**Issue by schayes04** [travis-ci/docs-travis-ci-com#922]
It'd be great to add Swift as a language for the getting started guide. Or maybe just add relevant info in with Objective-C? I'm not sure the differences but as a new person coming to the site it'd be good to have at least a mention of Swift

**Comment by BanzaiMan** [comment]
Currently Swift is just an alias for Objective-C. There is no difference.

**Comment by schayes04** [comment]
Great! So does it make sense to rename to Objective-C/Swift? Or to add a note somewhere? Since a search for swift in documentation turns up completely empty

**Comment by plaindocs** [comment]
Marking this as fixed for now - please reopen if necessary.
