### ISSUE TITLE
Mark beta features

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#926]
I'd like to propose we use some variation of the following markup as the only way to indicate beta features

> BETA Apt addons is in beta

Maybe @lislis could provide some distinctive formatting if we give the quote a beta class?

That way we can find them easier, and could list them on a page if that might be a useful thing.

@MariadeAnton thoughts?

**Comment by lislis** [comment]
@plaindocs sorry I'm missing some context. Where in the docs would that appear?

**Comment by plaindocs** [comment]
Sorry, I'm having a low context day apparently. 

Previously we'd used free text, usually in the section, title to indicate when a feature is beta.

I'm suggesting standardising on markdown blockquote, followed by BETA followed by text.

> BETA some text

An example of a normal blockquote is in https://docs.travis-ci.com/user/customizing-the-build/ starting with "When using custom scripts "

That way we could reliably grep out any pages containing beta features, and if we give those notes a CSS class can format them distinctly as well.

**Comment by lislis** [comment]
Ah, understood. Well, everything is possible with a simple CSS class ;)

We're using a yellow-ish badge in the web UI, should go for similar coloring in the docs?

![screen shot 2017-01-20 at 14 41 32](https://cloud.githubusercontent.com/assets/1006478/22151522/a4e5b624-df1e-11e6-9283-90c4a5426115.png)

**Comment by plaindocs** [comment]
OK

```
> BETA Awesome new feature that does some stuff.
{: .beta}
````
results in 
```
<blockquote class="beta">
  <p>BETA Awesome new feature that does some stuff.</p>
</blockquote>
```

https://github.com/travis-ci/docs-travis-ci-com/tree/sw-beta

Is the BETA redundant here? Probably right?
