### ISSUE TITLE
Draw more attention to the node versions you can actually use

### ISSUE THREAD

**Issue by lislis** [travis-ci/docs-travis-ci-com#940]
I think over the last couple of weeks I had to tell a lot of people that they can use more versions of node than are listed in our docs. 
Most don’t read until the paragraph with nvm https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against 
@plaindocs Any idea how we can make that more prominent? or not as easy to overread?

**Comment by BanzaiMan** [comment]
How about dropping the list altogether? This would force the users to actually read, no?

**Comment by BanzaiMan** [comment]
The following section `Available versions` is also lengthy and perhaps redundant.

**Comment by plaindocs** [comment]
On more general level than just node, this is a pain point for docs + support - so definitely something we need to improve. Also related to https://github.com/travis-pro/team-sapphire/issues/503

One option would be to be more explicit, something like 

|   | Environment X | Environment Y | 
| ------------- | ------------- | ------ |
| Ipre-installed  | 1,2,4  | 3,4 5, |
| Available to download  | 3,4,5  | 1,2,3,4 | 

Another option is to not list minor versions in the docs at all, and say we support 4.latest, 5.latest, 6.latest and others, check your build environment to find out which.

I'm not very keen on 'forcing' people to read, but rather try to make the right information available to them where and when they need it (easier said than done).

@BanzaiMan I can clean up that section + list immediately if that helps in the short term.
