### ISSUE TITLE
C# Documentaion : NUnit.Runners is obsolete, replaced by NUnit.Console

### ISSUE THREAD

**Issue by zwrawr** [travis-ci/docs-travis-ci-com#943]
The NUnit Runners package is now obsolete and should be replaced with the NUnit Console package.
The documentation for C# needs to be updated to reflect this.

[NuGet NUnit.Runners](https://www.nuget.org/packages/NUnit.Runners/)
[NuGet NUnit.Console](https://www.nuget.org/packages/NUnit.Console/)

**Comment by BanzaiMan** [comment]
Paging @joshua-anderson @akoeplinger @nterry for opinions.
