### ISSUE TITLE
Can I add new log fold sections?

### ISSUE THREAD

**Issue by jpritikin** [travis-ci/docs-travis-ci-com#949]
When showing the log, travis folds sections up into 1 line. For example, Worker information is summarized as 1 line and you can click the expander to see the details.

When I run our test suite, it generates tons of output. Is there any way to tell travis to fold the output?

Thanks.

**Comment by BanzaiMan** [comment]
It's not currently documented, but you can use this to achieve it. https://github.com/travis-ci/travis-rubies/blob/9f7962a881c55d32da7c76baefc58b89e3941d91/build.sh#L38-L44 (Undocumented, but unlikely to change.)

Do note that you cannot nest folds.
