### ISSUE TITLE
Docker: document steps to update to last version

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#953]
Docker 1.13 was released a couple of weeks ago and there are people trying to use its new features in Travis CI. It could be useful to document the steps required to update to the latest version (1.13 now, since we have 1.12).

@cotsog suggested adding these lines to the .travis.yml file:

```
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker --version # for verification
```

**Comment by plaindocs** [comment]
Sure - do you want to make a PR or shall I do it?

**Comment by iriberri** [comment]
@plaindocs I'm happy to add the changes myself! I'll try to send you a PR later today. :)
