### ISSUE TITLE
matrix include conditional on branch?

### ISSUE THREAD

**Issue by jpritikin** [travis-ci/docs-travis-ci-com#959]
I have a matrix include clause to build a binary that is deployed. However, we only want to bother with this step if we're on the `master` branch. I added a branch condition to the deploy step, but this still wastes precious osx resources building a binary that isn't deployed when the branch is not `master`. Is there a way to make the matrix include clause dependent on the branch?

**Comment by MariadeAnton** [comment]
Hi @jpritikin! At the moment, this is not a built-in feature but there might be some workarounds available to help with this, can you write us at support@travis-ci.com to evaluate your use case further? Thank you!

There's a similar feature request at https://github.com/travis-ci/travis-ci/issues/7149 - feel free to add your 👍
