### ISSUE TITLE
Multi column list

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#962]
Hey @lislis - related to your Nodejs issue, could you possible whip up a CSS class to give a 2 or 3 column `UL` for things like the list of node versions in 

https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Available-Versions

Anything else that would improve the readability / display of a list like that?

**Comment by plaindocs** [comment]
#940

**Comment by lislis** [comment]
@plaindocs here you go! https://github.com/travis-ci/docs-travis-ci-com/pull/964
