### ISSUE TITLE
Add a note about private submodules in common build problems for cloning git submodules

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#968]
At this section of the documentation: https://docs.travis-ci.com/user/common-build-problems/#Git-cannot-clone-my-Submodules we're suggesting using HTTPS over SSH when cloning submodules:

```
Git cannot clone my Submodules #

If your project uses Git submodules, make sure you use public Git URLs. For example, on GitHub, instead of

git@github.com:someuser/somelibrary.git
use

https://github.com/someuser/somelibrary.git
Otherwise, Travis CI builders won’t be able to clone your project because they don’t have your private SSH key.

```

I think this could be a bit confusing as this wouldn't work right away for private dependencies (it requires to configure a token or a user/password.

What about adding a note below linking to the [private dependencies page](https://docs.travis-ci.com/user/private-dependencies/) so that in this case, people knows how to set up a token/password or use SSH instead?

**Comment by plaindocs** [comment]
Related to #881

**Comment by plaindocs** [comment]
I'll add a link to the private dependencies.
