### ISSUE TITLE
Document TRAVIS_BRANCH behaviour for tagged commits

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/docs-travis-ci-com#971]
Comes from https://github.com/travis-ci/travis-ci/issues/4745 and https://github.com/travis-ci/travis-ci/issues/7326

When tagging a commit, git does not store the branch from which it was tagged. Git and GitHub only know the commit ref & the tag name and that's what Travis CI gets.

From @BanzaiMan's explanation:

> Tags on git are associated with a commit object, not a branch. You can tag a commit without any regards to the branch. You can tag a detached commit.

> GitHub's API reflects this: https://developer.github.com/v3/git/tags/ When we are notified of the new tag, the payload does not contain any information about the branch at all.

**Comment by sw-carlin** [comment]
@plaindocs your PR only address PR triggered builds. It didn't touch upon tag triggered builds.
