### ISSUE TITLE
Document how to install multiple LLVM versions

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#975]
A suggestion coming from https://secure.helpscout.net/conversation/318211762/49356/:

>https://github.com/micro-os-plus/eclipse-test-projects/blob/master/synthetic-posix-tests-micro-os-plus/scripts/travis.sh
>
>
>for LLVM on Ubuntu it is simple, they provide multiple versions for different system versions, see http://apt.llvm.org.
>
>for GCC I use the 'ppa:' you recommend in your documentation.
>
>```
>dist: trusty
> sudo: false
>
>addons:
>  apt:
>    sources:
>      - ubuntu-toolchain-r-test
>      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main' key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
>      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
>    packages:
>      - g++-5
>      - g++-6
>      - clang-3.8
>      - clang-3.9
>
>language: cpp
>```

**Comment by ilg-ul** [comment]
please be aware that the helpscout.net links are not publicly available, requiring a login. perhaps copying the content here would be better.

**Comment by cotsog** [comment]
@ilg-ul: thanks for the feedback! I've modified the issue description above with the content.
