### ISSUE TITLE
job priorities?

### ISSUE THREAD

**Issue by Leooo** [travis-ci/docs-travis-ci-com#976]
in Travis, is there a way to set job priorities? We have a big app partitioned taking lots of jobs to complete, and we don't want to prevent other apps to run their smaller tests in our shared Travis, i.e. their jobs should have higher priority than ours.

**Comment by acnagy** [comment]
Hey @Leooo good question.... right now, no way to prioritize jobs, that said, you can might want to try [limiting the number of concurrent builds](https://docs.travis-ci.com/user/customizing-the-build#sts=Limiting-Concurrent-Builds) for some of your lower priority apps. Perhaps give that a try? If it doesn't work, please send us an email over at support@travis-ci.com or open an issue in the main [Travis CI repo ](https://github.com/travis-ci/travis-ci/issues) (this repo's just for the docs) and we'll see what we can recommend instead. Thanks so much!

**Comment by Leooo** [comment]
@acnagy thanks, tried that already (limiting to 6 concurrent jobs for a partition of 12), but it will still queue the other jobs so will have to still wait for all the jobs to finish before someone else can run tests.. Will add the question in the repo you mentioned.
