### ISSUE TITLE
Add a link to this repo issues page in the documentation

### ISSUE THREAD

**Issue by ilg-ul** [travis-ci/docs-travis-ci-com#978]
Perhaps you could add a link to this tracker in the documentation pages themselves, this repository is relatively hidden and it might help finding it, possibly saving some email interactions.

**Comment by plaindocs** [comment]
Yeah, that is a good idea. Should be easy enough to add an 'edit on github' banner to each page.

**Comment by ilg-ul** [comment]
yes, that's even better. 

I saw this in the Jekyll site, and I used a similar method for http://micro-os-plus.github.io, with an 'Improve this page' link.

**Comment by plaindocs** [comment]
@lislis any thoughts on styling an 'improve this page' link? Straight text like in the link above, or the black ribbon on the corner thingie?

More examples:
https://sendgrid.com/docs/User_Guide/dashboard.html
http://micro-os-plus.github.io/
http://ionicframework.com/docs/api/directive/ionTabs/
https://jekyllrb.com/docs/home/

**Comment by ilg-ul** [comment]
my designer skills are limited, but isn't the black ribbon a bit to macabre?

**Comment by lislis** [comment]
My initial thought was something like this:

![screen shot 2017-02-22 at 12 47 36](https://cloud.githubusercontent.com/assets/1006478/23210288/324a291c-f8fd-11e6-9c2d-92efda3a4224.png)

But I'd like to have a pen icon as well as it seems like a sort of convention?

**Comment by plaindocs** [comment]
Pen icon sounds good to me. 

Do people have opinions on "improve" vs "edit" ?

**Comment by lislis** [comment]
I got a new design including icon :)
![ebc44790-f8e6-11e6-8f1b-a798fe441dc9](https://cloud.githubusercontent.com/assets/1006478/23219196/ba5b2c72-f91e-11e6-8da9-69d05b3fe85b.png)

I think improve is nicer and hints at "please think about if this change adds something useful"

**Comment by plaindocs** [comment]
Looks great, and I'm :+1: on improve also.

**Comment by ilg-ul** [comment]
> icon

is this icon part of a standard font, some corporate identity?

to me it looks very thin, and points to the wrong direction. are you left handed? ;-)

**Comment by lislis** [comment]
The icon comes straight from our designer and is more in-line with the icons we use in the main app.

I don't think there is a wrong or right way to point a pen, just a more established way to point pen icons ;) left and right handed people can hold their pens anyway they want.

**Comment by ilg-ul** [comment]
> just a more established way to point pen icons 

yes, for those used to GitHub (which for me is a reference site), pen icons point to the left. you can see it several times on this page.

**Comment by lislis** [comment]
We have the pen for convention, so I think it's ok to break convention with the pointing direction :)
@plaindocs I have a PR ready https://github.com/travis-ci/docs-travis-ci-com/pull/983

**Comment by plaindocs** [comment]
Merged. Thanks for raising the issue @ilg-ul and thanks for implementing so quickly @lislis .
