### ISSUE TITLE
In cache section: ccache does not come preinstalled in OS X images

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#984]
https://docs.travis-ci.com/user/caching#ccache-cache

I thought it could be interesting to add a mention here, as ccache is not available by default in the OS X infrastructure.

**Comment by iriberri** [comment]
We got a suggestion about mentioning to add `/usr/local/opt/ccache/libexec` to the path too when installing `ccache` via `brew`. Reopening to include this too! :)

**Comment by plaindocs** [comment]
@iriberri do you mean to `$PATH` or to the cache key in `.travis.yaml` ?

I'm guessing the first option. But that sounds kinda wrong according to https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html

**Comment by iriberri** [comment]
@plaindocs thanks for your response!

Yes, I mean prepending this to the `$PATH`.

I don't think the link you've posted is related. I'm talking about the `libexec` folder that ships with the `ccache` install. The folder may not have the best name, but the docs state it's meant to be placed in the PATH so it can override default compiler calls (e.g. `gcc`, `g++`) and invoke them using `ccache` as a wrapper.

By having these wrappers on the `$PATH`, all builds in the system will default to using `ccache` without the user needing to modify their Makefile. Otherwise a user would need to edit the Makefile and replace `gcc` calls with `ccache gcc`. Does this make sense? I'm sorry I didn't include this info in my previous comment!

**Comment by HalfWall** [comment]
who are you

**Comment by HalfWall** [comment]
who are you

**Comment by peternewman** [comment]
@plaindocs your example actually appends, rather than prepends the ccache folder to path, so it will find the normal binaries in /usr/bin or wherever first and hence not use ccache.

I've fixed this here:
https://github.com/travis-ci/docs-travis-ci-com/pull/1270

I think when this is in, this issue can be closed.

**Comment by iriberri** [comment]
Thanks for pointing this out, @peternewman! That was a good catch :)

**Comment by iriberri** [comment]
Closing (via https://github.com/travis-ci/docs-travis-ci-com/pull/1270)

**Comment by peternewman** [comment]
Thanks for merging @iriberri .
